const rows = {
  ko: ['방문 분석 설정', '공개 페이지 이용 통계', '허용하면 Google Analytics가 쿠키를 사용해 공개 페이지의 방문·이용 통계를 수집합니다. 거부해도 모든 기능을 이용할 수 있으며, 이 버튼에서 언제든 변경할 수 있습니다. 광고는 꺼져 있습니다.', '분석 허용', '분석 거부', '닫기', '개인정보 처리방침', '현재: 분석 허용', '현재: 분석 미허용', '선택을 저장하지 못했습니다. 브라우저 저장소 설정을 확인해 주세요.', '선택은 180일간 보관됩니다. 작성 중인 문서, 비공개 작업 공간, URL의 검색값·인증 토큰은 분석에 보내지 않습니다. Google에 전달된 이전 통계는 동의 철회만으로 삭제되지 않습니다.'],
  en: ['Analytics settings', 'Public-page usage statistics', 'If you allow, Google Analytics uses cookies to collect visits and usage statistics on public pages. Declining does not limit any features. Change your choice here at any time. Advertising is disabled.', 'Allow analytics', 'Decline analytics', 'Close', 'Privacy policy', 'Current: analytics allowed', 'Current: analytics not allowed', 'Your choice could not be saved. Check your browser storage settings.', 'Your choice is stored for 180 days. Draft documents, private workspaces, URL query values and authentication tokens are not sent to analytics. Withdrawing consent does not delete statistics already sent to Google.'],
  de: ['Analyseeinstellungen', 'Nutzung öffentlicher Seiten', 'Wenn Sie zustimmen, verwendet Google Analytics Cookies, um Besuche und die Nutzung öffentlicher Seiten zu erfassen. Eine Ablehnung schränkt keine Funktionen ein. Sie können Ihre Wahl hier jederzeit ändern. Werbung ist deaktiviert.', 'Analyse erlauben', 'Analyse ablehnen', 'Schließen', 'Datenschutzerklärung', 'Aktuell: Analyse erlaubt', 'Aktuell: Analyse nicht erlaubt', 'Ihre Wahl konnte nicht gespeichert werden. Prüfen Sie den Browserspeicher.', 'Ihre Wahl wird 180 Tage gespeichert. Dokumententwürfe, private Arbeitsbereiche, URL-Abfragewerte und Authentifizierungstoken werden nicht übermittelt. Ein Widerruf löscht keine bereits an Google gesendeten Statistiken.'],
  ja: ['アクセス解析設定', '公開ページの利用統計', '許可すると、Google Analytics が Cookie を使用して公開ページの訪問・利用統計を収集します。拒否しても全機能を利用できます。設定はここでいつでも変更できます。広告は無効です。', '解析を許可', '解析を拒否', '閉じる', 'プライバシーポリシー', '現在：解析を許可', '現在：解析は未許可', '選択を保存できません。ブラウザーの保存設定をご確認ください。', '選択は180日間保存されます。下書き文書、非公開ワークスペース、URLのクエリ値、認証トークンは解析に送信しません。同意を撤回しても、Googleに送信済みの統計は削除されません。'],
  fr: ['Paramètres de mesure', 'Statistiques des pages publiques', 'Avec votre accord, Google Analytics utilise des cookies pour mesurer les visites et l’utilisation des pages publiques. Le refus ne limite aucune fonctionnalité. Vous pouvez modifier votre choix ici à tout moment. La publicité est désactivée.', 'Autoriser la mesure', 'Refuser la mesure', 'Fermer', 'Politique de confidentialité', 'Actuellement : mesure autorisée', 'Actuellement : mesure non autorisée', 'Votre choix n’a pas pu être enregistré. Vérifiez le stockage du navigateur.', 'Votre choix est conservé 180 jours. Les brouillons, espaces privés, paramètres de requête URL et jetons d’authentification ne sont pas transmis. Le retrait du consentement ne supprime pas les statistiques déjà envoyées à Google.'],
  it: ['Impostazioni analisi', 'Statistiche delle pagine pubbliche', 'Se acconsenti, Google Analytics usa cookie per raccogliere visite e statistiche di utilizzo delle pagine pubbliche. Il rifiuto non limita le funzioni. Puoi cambiare la scelta qui in qualsiasi momento. La pubblicità è disattivata.', 'Consenti analisi', 'Rifiuta analisi', 'Chiudi', 'Informativa sulla privacy', 'Attuale: analisi consentita', 'Attuale: analisi non consentita', 'Impossibile salvare la scelta. Controlla le impostazioni di archiviazione del browser.', 'La scelta viene conservata per 180 giorni. Bozze, spazi privati, valori delle query URL e token di autenticazione non vengono inviati. La revoca non elimina le statistiche già inviate a Google.'],
  es: ['Ajustes de análisis', 'Estadísticas de páginas públicas', 'Si lo permite, Google Analytics usa cookies para recopilar visitas y estadísticas de uso de páginas públicas. Rechazarlo no limita ninguna función. Puede cambiar su decisión aquí en cualquier momento. La publicidad está desactivada.', 'Permitir análisis', 'Rechazar análisis', 'Cerrar', 'Política de privacidad', 'Actual: análisis permitido', 'Actual: análisis no permitido', 'No se pudo guardar su decisión. Revise el almacenamiento del navegador.', 'Su decisión se guarda durante 180 días. No se envían borradores, espacios privados, valores de consulta URL ni tokens de autenticación. Retirar el consentimiento no elimina las estadísticas ya enviadas a Google.'],
  pt: ['Definições de análise', 'Estatísticas de páginas públicas', 'Se permitir, o Google Analytics utiliza cookies para recolher visitas e estatísticas de uso de páginas públicas. Recusar não limita nenhuma funcionalidade. Pode alterar a escolha aqui a qualquer momento. A publicidade está desativada.', 'Permitir análise', 'Recusar análise', 'Fechar', 'Política de privacidade', 'Atual: análise permitida', 'Atual: análise não permitida', 'Não foi possível guardar a escolha. Verifique o armazenamento do navegador.', 'A escolha é guardada por 180 dias. Rascunhos, espaços privados, valores de consulta URL e tokens de autenticação não são enviados. Retirar o consentimento não elimina estatísticas já enviadas ao Google.'],
  ru: ['Настройки аналитики', 'Статистика открытых страниц', 'С вашего разрешения Google Analytics использует файлы cookie для сбора статистики посещений открытых страниц. Отказ не ограничивает функции. Вы можете изменить выбор здесь в любое время. Реклама отключена.', 'Разрешить аналитику', 'Отклонить аналитику', 'Закрыть', 'Политика конфиденциальности', 'Сейчас: аналитика разрешена', 'Сейчас: аналитика не разрешена', 'Не удалось сохранить выбор. Проверьте настройки хранилища браузера.', 'Выбор хранится 180 дней. Черновики, закрытые рабочие области, параметры URL и токены авторизации не передаются. Отзыв согласия не удаляет статистику, уже отправленную Google.'],
  ar: ['إعدادات التحليلات', 'إحصاءات الصفحات العامة', 'إذا سمحت، يستخدم Google Analytics ملفات تعريف الارتباط لجمع إحصاءات الزيارات واستخدام الصفحات العامة. الرفض لا يقيّد أي ميزة. يمكنك تغيير اختيارك هنا في أي وقت. الإعلانات معطّلة.', 'السماح بالتحليلات', 'رفض التحليلات', 'إغلاق', 'سياسة الخصوصية', 'حالياً: التحليلات مسموحة', 'حالياً: التحليلات غير مسموحة', 'تعذّر حفظ اختيارك. تحقّق من إعدادات تخزين المتصفح.', 'يُحفظ اختيارك لمدة 180 يوماً. لا تُرسل المسودات أو مساحات العمل الخاصة أو قيم استعلام الرابط أو رموز المصادقة. سحب الموافقة لا يحذف الإحصاءات المرسلة سابقاً إلى Google.'],
};
export function getAnalyticsText(locale = 'en-US') {
  return Object.fromEntries(['settings', 'title', 'body', 'allow', 'deny', 'close', 'privacy', 'allowed', 'denied', 'error', 'detail'].map((key, index) => [key, (rows[locale.split('-')[0]] || rows.en)[index]]));
}
