const rows = {
 ko: ['공개 페이지 방문 분석', 'Google Analytics의 쿠키를 사용해 공개 페이지의 방문 통계를 자동으로 수집합니다. 광고는 꺼져 있습니다. 공개 페이지의 제목과 유입 사이트 도메인도 수집합니다.', '비공개 작업 공간·문서 내용·URL 검색값·인증 토큰은 전송하지 않습니다. 이 페이지에서 이 브라우저의 분석을 중지할 수 있습니다. 중지해도 이미 Google에 전송한 통계는 삭제되지 않습니다.', '방문 분석 사용', '이 브라우저의 방문 분석 중지', '현재: 방문 분석 사용 중', '현재: 방문 분석 중지됨', '설정을 저장하지 못했습니다. 브라우저 저장소 설정을 확인해 주세요.'],
 en: ['Public-page analytics', 'Google Analytics uses cookies to collect public-page visit statistics automatically. Advertising is disabled. Public page titles and referring site domains are also collected.', 'Private workspaces, document content, URL query values and authentication tokens are not sent. You can stop analytics for this browser on this page. Stopping does not delete statistics already sent to Google.', 'Enable analytics', 'Stop analytics in this browser', 'Current: analytics enabled', 'Current: analytics stopped', 'The setting could not be saved. Check your browser storage settings.'],
 de: ['Analyse öffentlicher Seiten', 'Google Analytics verwendet Cookies, um Besuche öffentlicher Seiten automatisch zu erfassen. Werbung ist deaktiviert. Auch die Titel öffentlicher Seiten und die Domains verweisender Websites werden erfasst.', 'Private Arbeitsbereiche, Dokumentinhalte, URL-Abfragewerte und Authentifizierungstoken werden nicht übermittelt. Sie können die Analyse für diesen Browser hier stoppen. Bereits an Google gesendete Statistiken werden dadurch nicht gelöscht.', 'Analyse aktivieren', 'Analyse in diesem Browser stoppen', 'Aktuell: Analyse aktiviert', 'Aktuell: Analyse gestoppt', 'Die Einstellung konnte nicht gespeichert werden. Prüfen Sie den Browserspeicher.'],
 ja: ['公開ページのアクセス解析', 'Google Analytics の Cookie を使用して公開ページの訪問統計を自動収集します。広告は無効です。 公開ページのタイトルと参照元サイトのドメインも収集します。', '非公開ワークスペース、文書内容、URLのクエリ値、認証トークンは送信しません。このページで、このブラウザーの解析を停止できます。停止してもGoogleに送信済みの統計は削除されません。', 'アクセス解析を有効化', 'このブラウザーの解析を停止', '現在：解析は有効', '現在：解析は停止中', '設定を保存できません。ブラウザーの保存設定をご確認ください。'],
 fr: ['Analyse des pages publiques', 'Google Analytics utilise des cookies pour collecter automatiquement les statistiques de visite des pages publiques. La publicité est désactivée. Les titres des pages publiques et les domaines des sites référents sont également collectés.', 'Les espaces privés, le contenu des documents, les paramètres de requête URL et les jetons d’authentification ne sont pas transmis. Vous pouvez arrêter l’analyse pour ce navigateur ici. Cela ne supprime pas les statistiques déjà envoyées à Google.', 'Activer l’analyse', 'Arrêter l’analyse dans ce navigateur', 'Actuellement : analyse activée', 'Actuellement : analyse arrêtée', 'Impossible d’enregistrer ce réglage. Vérifiez le stockage du navigateur.'],
 it: ['Analisi delle pagine pubbliche', 'Google Analytics usa cookie per raccogliere automaticamente le statistiche di visita delle pagine pubbliche. La pubblicità è disattivata. Vengono raccolti anche i titoli delle pagine pubbliche e i domini dei siti di provenienza.', 'Spazi privati, contenuto dei documenti, valori delle query URL e token di autenticazione non vengono inviati. Qui puoi interrompere l’analisi per questo browser. Le statistiche già inviate a Google non vengono eliminate.', 'Attiva analisi', 'Interrompi analisi in questo browser', 'Attuale: analisi attiva', 'Attuale: analisi interrotta', 'Impossibile salvare l’impostazione. Controlla l’archiviazione del browser.'],
 es: ['Análisis de páginas públicas', 'Google Analytics usa cookies para recopilar automáticamente estadísticas de visitas a páginas públicas. La publicidad está desactivada. También se recopilan los títulos de las páginas públicas y los dominios de los sitios de procedencia.', 'No se envían espacios privados, contenido de documentos, valores de consulta URL ni tokens de autenticación. Puede detener el análisis para este navegador aquí. Esto no elimina las estadísticas ya enviadas a Google.', 'Activar análisis', 'Detener análisis en este navegador', 'Actual: análisis activo', 'Actual: análisis detenido', 'No se pudo guardar el ajuste. Revise el almacenamiento del navegador.'],
 pt: ['Análise de páginas públicas', 'O Google Analytics utiliza cookies para recolher automaticamente estatísticas de visitas a páginas públicas. A publicidade está desativada. Também são recolhidos os títulos das páginas públicas e os domínios dos sites de origem.', 'Espaços privados, conteúdo de documentos, valores de consulta URL e tokens de autenticação não são enviados. Pode parar a análise para este navegador aqui. Isso não elimina estatísticas já enviadas ao Google.', 'Ativar análise', 'Parar análise neste navegador', 'Atual: análise ativa', 'Atual: análise parada', 'Não foi possível guardar a definição. Verifique o armazenamento do navegador.'],
 ru: ['Аналитика открытых страниц', 'Google Analytics использует файлы cookie для автоматического сбора статистики посещений открытых страниц. Реклама отключена. Также собираются заголовки открытых страниц и домены сайтов-источников переходов.', 'Закрытые рабочие области, содержимое документов, параметры URL и токены авторизации не передаются. Здесь можно остановить аналитику для этого браузера. Это не удаляет статистику, уже отправленную Google.', 'Включить аналитику', 'Остановить аналитику в этом браузере', 'Сейчас: аналитика включена', 'Сейчас: аналитика остановлена', 'Не удалось сохранить настройку. Проверьте хранилище браузера.'],
 ar: ['تحليلات الصفحات العامة', 'يستخدم Google Analytics ملفات تعريف الارتباط لجمع إحصاءات زيارات الصفحات العامة تلقائياً. الإعلانات معطّلة. تُجمع أيضاً عناوين الصفحات العامة ونطاقات المواقع المُحيلة.', 'لا تُرسل مساحات العمل الخاصة أو محتويات المستندات أو قيم استعلام الرابط أو رموز المصادقة. يمكنك إيقاف التحليلات لهذا المتصفح هنا. الإيقاف لا يحذف الإحصاءات المرسلة سابقاً إلى Google.', 'تشغيل التحليلات', 'إيقاف التحليلات لهذا المتصفح', 'حالياً: التحليلات مفعّلة', 'حالياً: التحليلات متوقفة', 'تعذّر حفظ الإعداد. تحقّق من تخزين المتصفح.'],
};
export function getAnalyticsText(locale = 'en-US') {
 return Object.fromEntries(['title','body','detail','allow','deny','allowed','denied','error'].map((key,index)=>[key,(rows[locale.split('-')[0]]||rows.en)[index]]));
}
