const keys=['download','busy','translated','original','showTranslation','unsupported','error','notice'];
const labels={
 ko:['무료 번역 준비','브라우저에서 번역 중','자동 번역','원문 보기','번역 보기','이 브라우저·언어 조합은 자동 번역을 지원하지 않아 원문을 표시합니다.','번역하지 못했습니다. 원문을 표시합니다.','기계 번역 참고본입니다. 작업 국가와 원문은 유지되며, 단계 재사용 시 원문을 가져옵니다.'],
 en:['Prepare free translation','Translating in your browser','Machine translation','Show original','Show translation','Automatic translation is unavailable for this browser or language pair. Showing the original.','Translation failed. Showing the original.','Machine-translated reference. The work country and source remain unchanged; reusing steps imports the original.'],
 ja:['無料翻訳を準備','ブラウザーで翻訳中','自動翻訳','原文を表示','翻訳を表示','このブラウザーまたは言語の組み合わせは翻訳に対応していません。原文を表示しています。','翻訳できませんでした。原文を表示しています。','機械翻訳の参考資料です。作業国と原文は変更されません。手順の再利用では原文を取り込みます。'],
 de:['Kostenlose Übersetzung vorbereiten','Übersetzung im Browser','Maschinelle Übersetzung','Original anzeigen','Übersetzung anzeigen','Diese Browser- oder Sprachkombination unterstützt keine automatische Übersetzung. Das Original wird angezeigt.','Übersetzung fehlgeschlagen. Das Original wird angezeigt.','Maschinell übersetzte Referenz. Arbeitsland und Original bleiben unverändert. Beim Wiederverwenden werden die Originalschritte übernommen.'],
 fr:['Préparer la traduction gratuite','Traduction dans votre navigateur','Traduction automatique','Voir l’original','Voir la traduction','Traduction indisponible pour ce navigateur ou cette paire de langues. Affichage de l’original.','Échec de la traduction. Affichage de l’original.','Traduction automatique de référence. Le pays de travail et la source restent inchangés ; la réutilisation importe les étapes originales.'],
 it:['Prepara la traduzione gratuita','Traduzione nel browser','Traduzione automatica','Mostra originale','Mostra traduzione','Traduzione non disponibile per questo browser o questa coppia di lingue. Viene mostrato l’originale.','Traduzione non riuscita. Viene mostrato l’originale.','Traduzione automatica di riferimento. Paese di lavoro e originale restano invariati; il riutilizzo importa le fasi originali.'],
 es:['Preparar traducción gratuita','Traduciendo en tu navegador','Traducción automática','Ver original','Ver traducción','Traducción no disponible para este navegador o par de idiomas. Se muestra el original.','No se pudo traducir. Se muestra el original.','Traducción automática de referencia. El país de trabajo y la fuente no cambian; al reutilizar etapas se importa el original.'],
 pt:['Preparar tradução gratuita','Traduzindo no navegador','Tradução automática','Ver original','Ver tradução','Tradução indisponível para este navegador ou par de idiomas. Exibindo o original.','Falha na tradução. Exibindo o original.','Tradução automática de referência. O país de trabalho e a fonte não mudam; a reutilização importa as etapas originais.'],
 ru:['Подготовить бесплатный перевод','Перевод в браузере','Машинный перевод','Показать оригинал','Показать перевод','Автоперевод недоступен для этого браузера или языковой пары. Показан оригинал.','Не удалось перевести. Показан оригинал.','Машинный перевод для справки. Страна работ и оригинал не изменяются; при повторном использовании импортируются исходные этапы.'],
 ar:['إعداد الترجمة المجانية','جارٍ الترجمة في المتصفح','ترجمة آلية','عرض الأصل','عرض الترجمة','الترجمة غير متاحة لهذا المتصفح أو زوج اللغات. يتم عرض الأصل.','تعذرت الترجمة. يتم عرض الأصل.','ترجمة آلية للمرجع. يبقى بلد العمل والمصدر دون تغيير؛ تستورد إعادة الاستخدام الخطوات الأصلية.'],
};
export const browserTranslationUi=locale=>Object.fromEntries(keys.map((key,i)=>[key,(labels[locale.split('-')[0]]||labels.en)[i]]));
