const en = {
 title:'Business workspace', beta:'Free beta', intro:'Try Pro and Business features for 30 days. No card, payment or automatic billing. Your saved documents remain readable after the trial.',
 free:'Free', freeDesc:'Create JSA documents, use the step library, export and explore public examples.', pro:'Pro beta', proDesc:'Keep personal document revisions, preview earlier versions and restore as a new revision.', business:'Business beta', businessDesc:'Company templates, roles, private team documents and version-specific approval.', start:'Start free Pro + Business trial', active:'Trial ends', expired:'Trial ended. Saved documents and history remain readable.', login:'Sign in to continue', library:'My library', home:'Home', loading:'Loading…', retry:'Retry', saved:'Saved.', error:'Unable to complete the request. Refresh and try again.', conflict:'This document changed. Refresh and check the latest version before retrying.', denied:'You do not have permission for this action.', expiredError:'The trial has ended. Existing data is still readable.', reviewerError:'Choose another reviewer who did not edit this version.', unavailable:'The invitation is expired, revoked or already used.',
 organizations:'Organizations', chooseOrg:'Choose an organization', name:'Organization name', create:'Create organization', limit:'Up to 3 organizations during the trial.', orgExpired:'This organization is read-only because its owner’s trial has ended.', documents:'Team documents', members:'Members & invitations', templates:'Company templates', history:'Personal revision history', historyHint:'Revisions are recorded when you save private documents during the trial. Restore creates another revision; history stays intact. Latest 100 entries are shown.',
 source:'My private document', chooseSource:'Choose a saved private document', import:'Share a copy with this organization', importHint:'Only the selected private document is copied, including its participants and photos. All organization members can read it. The original stays in your library.', importConfirm:'Share this document, including its private fields and photos, with every member of the selected organization?',
 empty:'No items yet.', open:'Open', revision:'Revision', draft:'Draft', submitted:'Awaiting approval', approved:'Approved', rejected:'Changes requested', reviewer:'Reviewer', owner:'Owner', editor:'Editor', viewer:'Viewer', chooseReviewer:'Choose a reviewer', submit:'Request approval', approve:'Approve this version', reject:'Request changes', comment:'Review comment (required when requesting changes)', reopen:'Create a new draft revision', withdraw:'Withdraw approval request', replace:'Replace draft from my selected document', restore:'Restore as a new revision', restoreConfirm:'Create a new revision using this snapshot? The previous history will be kept.', preview:'Preview', editCopy:'Edit a private copy', editHint:'To change a team document, edit and save a private copy, then select it above and replace this draft. Submitted and approved versions are locked.', audit:'Revision and approval history', actor:'By',
 invite:'Create one-use invitation', inviteHint:'The link expires in 7 days and can be used once by anyone who has it. Copy and send it yourself. No email is sent.', copy:'Copy link', copied:'Link copied.', revoke:'Revoke', remove:'Remove member', removeConfirm:'Remove this member’s access to the organization?', join:'Accept invitation', joinHint:'Accepting gives you access to the organization with the role chosen by its owner.', leave:'Leave organization', leaveConfirm:'Leave this organization and lose access to its private documents?',
 companyHint:'Use company templates from the Document Designer. Choose an organization there to apply or save a shared layout.', chooseTemplate:'Choose a company template', templateName:'Template name', saveTemplate:'Save a new company template', updateTemplate:'Update selected company template', deleteTemplate:'Delete selected company template', templateConfirm:'Update or delete this shared template for all members?', apply:'Apply template', noOrg:'Create or join an organization in the Business workspace.',
 interest:'Future paid plan preference (no purchase)', interestedPro:'Interested in Pro', interestedBusiness:'Interested in Business', current:'Current version', close:'Close preview', refresh:'Refresh', trialIncludes:'The trial includes both Pro and Business features. Paid plans are not available yet.',
};
const ko = {
 title:'회사 작업공간', beta:'무료 베타', intro:'Pro와 Business 기능을 30일간 무료로 체험합니다. 카드 등록·결제·자동 과금은 없습니다. 체험이 끝나도 저장된 문서는 열람할 수 있습니다.',
 free:'Free', freeDesc:'JSA 작성, 작업단계 라이브러리, 내보내기, 공개 자료 재사용을 이용합니다.', pro:'Pro 베타', proDesc:'개인 문서의 개정 이력을 보관하고 이전 버전을 확인·복원합니다.', business:'Business 베타', businessDesc:'회사 양식, 역할별 권한, 비공개 팀 문서와 버전별 결재를 이용합니다.', start:'Pro + Business 무료 체험 시작', active:'체험 종료일', expired:'체험이 종료되었습니다. 저장된 문서와 이력은 계속 열람할 수 있습니다.', login:'로그인하고 계속하기', library:'내 보관함', home:'홈', loading:'불러오는 중…', retry:'다시 시도', saved:'저장했습니다.', error:'요청을 완료하지 못했습니다. 새로고침 후 다시 시도해 주세요.', conflict:'다른 곳에서 문서가 변경되었습니다. 새로고침 후 최신 버전을 확인해 주세요.', denied:'이 작업을 수행할 권한이 없습니다.', expiredError:'체험이 종료되어 변경할 수 없습니다. 기존 자료는 열람할 수 있습니다.', reviewerError:'이 버전을 작성하지 않은 다른 검토자를 선택해 주세요.', unavailable:'초대가 만료·취소되었거나 이미 사용되었습니다.',
 organizations:'회사 선택', chooseOrg:'회사를 선택하세요', name:'회사·조직 이름', create:'회사 작업공간 만들기', limit:'체험 중 최대 3개의 회사를 만들 수 있습니다.', orgExpired:'회사 소유자의 체험이 종료되어 열람만 가능합니다.', documents:'팀 문서', members:'구성원·초대', templates:'회사 양식', history:'개인 문서 개정 이력', historyHint:'체험 중 비공개 문서를 저장할 때 개정 이력이 기록됩니다. 복원은 새 개정으로 저장되며 기존 이력은 유지됩니다. 최근 100건을 표시합니다.',
 source:'내 비공개 작업물', chooseSource:'저장한 비공개 작업물을 선택하세요', import:'이 회사에 사본 공유', importHint:'선택한 작업물의 참여자·사진을 포함한 사본을 모든 회사 구성원에게 공유합니다. 개인 원본은 내 보관함에 유지됩니다.', importConfirm:'선택한 작업물의 개인정보·사진을 포함한 사본을 이 회사의 모든 구성원에게 공유할까요?',
 empty:'아직 항목이 없습니다.', open:'열기', revision:'개정', draft:'작성 중', submitted:'결재 대기', approved:'승인됨', rejected:'보완 요청', reviewer:'검토자', owner:'소유자', editor:'작성자', viewer:'열람자', chooseReviewer:'검토자를 선택하세요', submit:'결재 요청', approve:'이 버전 승인', reject:'보완 요청', comment:'검토 의견 (보완 요청 시 필수)', reopen:'새 개정 작성', withdraw:'결재 요청 취소', replace:'선택한 작업물로 초안 교체', restore:'새 개정으로 복원', restoreConfirm:'이 내용으로 새 개정을 만들까요? 기존 이력은 유지됩니다.', preview:'미리보기', editCopy:'개인 사본으로 편집', editHint:'팀 문서를 수정하려면 개인 사본으로 편집·저장한 뒤, 위에서 해당 작업물을 선택하여 초안을 교체하세요. 결재 대기·승인 버전은 수정할 수 없습니다.', audit:'개정·결재 이력', actor:'처리자',
 invite:'일회용 초대 링크 만들기', inviteHint:'링크는 7일간 유효하며 가진 사람이 한 번 사용할 수 있습니다. 복사하여 직접 전달하세요. 이메일은 자동 발송되지 않습니다.', copy:'링크 복사', copied:'링크를 복사했습니다.', revoke:'초대 취소', remove:'구성원 제외', removeConfirm:'이 구성원의 회사 자료 접근 권한을 해제할까요?', join:'초대 수락', joinHint:'수락하면 소유자가 지정한 역할로 회사 작업공간에 참여합니다.', leave:'회사 나가기', leaveConfirm:'회사에서 나가고 비공개 자료 접근 권한을 해제할까요?',
 companyHint:'문서 디자이너에서 회사를 선택하면 회사 양식을 적용하거나 현재 양식을 공유할 수 있습니다.', chooseTemplate:'회사 양식을 선택하세요', templateName:'양식 이름', saveTemplate:'새 회사 양식으로 저장', updateTemplate:'선택한 회사 양식 갱신', deleteTemplate:'선택한 회사 양식 삭제', templateConfirm:'모든 구성원이 사용하는 회사 양식을 변경하거나 삭제할까요?', apply:'양식 적용', noOrg:'회사 작업공간에서 회사를 만들거나 초대에 참여하세요.',
 interest:'향후 유료 요금제 관심 등록 (구매 아님)', interestedPro:'Pro에 관심 있음', interestedBusiness:'Business에 관심 있음', current:'현재 버전', close:'미리보기 닫기', refresh:'새로고침', trialIncludes:'체험에는 Pro와 Business 기능이 모두 포함됩니다. 유료 요금제는 아직 판매하지 않습니다.',
};
export const getBusinessUi = (locale = 'en-US') => locale.startsWith('ko') ? ko : en;
export function businessError(error, ui) {
 const code = error?.message || '';
 if (code.includes('VERSION_CONFLICT')) return ui.conflict;
 if (/BETA_(EXPIRED|REQUIRED)/.test(code)) return ui.expiredError;
 if (/ACCESS_DENIED|OWNER_PROTECTED/.test(code)) return ui.denied;
 if (code.includes('REVIEWER_REQUIRED')) return ui.reviewerError;
 if (code.includes('INVITE_UNAVAILABLE')) return ui.unavailable;
 return ui.error;
}
