import { getAnalyticsText } from './analyticsText.js';
const rows={
 en:['General inquiry','Suggestion','Support & rights','Requests are private. The operator can review them; replies appear here. Do not include passwords, identity documents or confidential site details.','Community reuse v1: ownership stays with the author. Permission covers copying, adapting and republishing for work, with a link to the source and a note of changes. It does not grant rights to third-party material or certify safety. Removing a public page does not recall copies already obtained. Mandatory legal rights remain unaffected.','Shared material is a reference, not an approved work permit. A competent person must check site conditions, local rules and controls before work.','Advertising and external visitor analytics are currently disabled. Public views count signed-in visits; reuse counts recorded actions, not unique people or proof of use on site.','Operator identity and a non-member contact channel are awaiting verification. This beta request form currently requires sign-in.'],
 ko:['일반 문의','기능 건의','고객센터·권리 보호','문의는 비공개이며 운영자가 확인합니다. 답변은 이 화면에서 확인하세요. 비밀번호·신분증·현장 기밀은 입력하지 마세요.','커뮤니티 재사용 v1: 저작권은 작성자에게 남습니다. 원문 링크와 변경 내용을 표시하는 업무상 복사·수정·재공개를 허락합니다. 제3자 자료에 대한 권리나 안전 인증을 부여하지 않습니다. 공개 페이지를 내려도 이미 받은 사본이 회수되지는 않습니다. 법률상 강행규정에 따른 권리는 제한하지 않습니다.','공유 자료는 참고용이며 승인된 작업허가서가 아닙니다. 작업 전에 담당 전문가가 현장 조건·해당 지역 법령·안전대책을 확인해야 합니다.','광고와 외부 방문 분석은 현재 꺼져 있습니다. 공개 조회는 로그인 방문을, 활용은 기록된 동작을 집계하며 실제 현장 사용이나 고유 인원 수를 뜻하지 않습니다.','운영자 신원과 비회원 연락 경로는 확인 중입니다. 현재 베타 문의 접수는 로그인이 필요합니다.'],
 ja:['一般問い合わせ','機能提案','サポート・権利保護','申請は非公開で運営者が確認し、返信はここに表示されます。パスワード・身分証・現場の機密を含めないでください。','コミュニティ再利用v1：権利は作成者に残ります。出典リンクと変更点を明示した業務上の複製・改変・再公開を許可します。第三者の権利や安全認証は含みません。公開削除後も取得済みの複製は回収されません。強行法規上の権利を制限しません。','共有資料は参考用で、承認済み作業許可書ではありません。作業前に有資格者が現場・地域法令・安全対策を確認してください。','広告と外部アクセス解析は無効です。閲覧数はログインした訪問、利用数は操作の記録で、現場利用や実人数ではありません。','運営者の身元と非会員の連絡窓口は確認中です。ベータ版の申請にはログインが必要です。'],
 de:['Allgemeine Anfrage','Vorschlag','Hilfe & Rechte','Anfragen sind privat; der Betreiber prüft sie. Antworten erscheinen hier. Keine Passwörter, Ausweisdokumente oder Betriebsgeheimnisse eingeben.','Community-Nutzung v1: Rechte verbleiben beim Autor. Kopieren, Bearbeiten und erneutes Veröffentlichen für die Arbeit sind mit Quellenlink und Änderungshinweis erlaubt. Rechte Dritter und Sicherheitszertifizierungen sind nicht umfasst. Eine Löschung ruft erhaltene Kopien nicht zurück. Zwingende gesetzliche Rechte bleiben unberührt.','Geteilte Inhalte sind Referenzen, keine genehmigten Arbeitserlaubnisse. Fachkundige müssen Einsatzbedingungen, örtliches Recht und Maßnahmen vor Arbeitsbeginn prüfen.','Werbung und externe Besuchsanalyse sind deaktiviert. Aufrufe zählen angemeldete Besuche; Nutzung zählt Aktionen, nicht eindeutige Personen oder tatsächliche Einsätze.','Betreiberidentität und Kontakt für Nichtmitglieder werden noch geprüft. Beta-Anfragen erfordern eine Anmeldung.'],
 fr:['Question générale','Suggestion','Assistance et droits','Les demandes sont privées et examinées par l’opérateur. Les réponses apparaissent ici. Ne fournissez ni mot de passe, ni pièce d’identité, ni secret du site.','Réutilisation communautaire v1 : les droits restent à l’auteur. La copie, l’adaptation et la republication professionnelles sont autorisées avec un lien source et la mention des modifications. Aucun droit de tiers ni certification de sécurité n’est accordé. Le retrait ne rappelle pas les copies reçues. Les droits légaux impératifs restent inchangés.','Ces contenus sont des références, pas des permis de travail approuvés. Une personne compétente doit vérifier le site, les règles locales et les mesures avant le travail.','Publicités et analyses externes sont désactivées. Les vues comptent les visites connectées et les réutilisations des actions, pas des personnes uniques ni des utilisations sur site.','L’identité de l’opérateur et le contact hors compte restent à vérifier. Les demandes bêta exigent une connexion.'],
 es:['Consulta general','Sugerencia','Ayuda y derechos','Las solicitudes son privadas y las revisa el operador. Las respuestas aparecen aquí. No incluya contraseñas, documentos de identidad ni secretos del lugar.','Reutilización comunitaria v1: el autor conserva los derechos. Se permite copiar, adaptar y republicar para el trabajo con enlace a la fuente y aviso de cambios. No concede derechos de terceros ni certificación de seguridad. Retirar una página no recupera las copias obtenidas. Los derechos legales imperativos no se limitan.','El material es una referencia, no un permiso de trabajo aprobado. Una persona competente debe comprobar el lugar, las normas locales y las medidas antes del trabajo.','La publicidad y el análisis externo están desactivados. Las vistas cuentan visitas con sesión y los usos cuentan acciones, no personas únicas ni uso real en obra.','La identidad del operador y el contacto sin cuenta están pendientes de verificación. Las solicitudes beta requieren iniciar sesión.'],
 it:['Domanda generale','Suggerimento','Assistenza e diritti','Le richieste sono private e valutate dal gestore. Le risposte compaiono qui. Non inserire password, documenti d’identità o segreti del sito.','Riutilizzo comunitario v1: i diritti restano all’autore. Sono consentite copia, modifica e ripubblicazione per lavoro con link alla fonte e nota delle modifiche. Non concede diritti di terzi o certificazioni di sicurezza. La rimozione non richiama copie già ricevute. Restano salvi i diritti inderogabili.','I contenuti sono riferimenti, non permessi di lavoro approvati. Una persona competente deve verificare sito, norme locali e misure prima del lavoro.','Pubblicità e analisi esterne sono disattivate. Le visualizzazioni contano visite con accesso; i riutilizzi contano azioni, non persone uniche o uso sul campo.','Identità del gestore e contatto senza account sono in verifica. Le richieste beta richiedono l’accesso.'],
 pt:['Consulta geral','Sugestão','Suporte e direitos','Os pedidos são privados e revistos pelo operador. As respostas aparecem aqui. Não inclua senhas, documentos de identidade ou segredos do local.','Reutilização comunitária v1: os direitos permanecem com o autor. Cópia, adaptação e republicação para trabalho são permitidas com link da fonte e indicação das alterações. Não concede direitos de terceiros nem certificação de segurança. Remover uma página não recupera cópias recebidas. Direitos legais obrigatórios são preservados.','O material é referência, não permissão de trabalho aprovada. Uma pessoa competente deve verificar o local, as regras locais e as medidas antes do trabalho.','Publicidade e análise externa estão desativadas. Visualizações contam visitas autenticadas; reutilizações contam ações, não pessoas únicas nem uso em campo.','A identidade do operador e o contato sem conta aguardam verificação. Pedidos beta exigem login.'],
 ru:['Общий вопрос','Предложение','Поддержка и права','Запросы конфиденциальны и доступны оператору. Ответы появляются здесь. Не указывайте пароли, документы личности и секретные данные объекта.','Повторное использование v1: права остаются у автора. Разрешены рабочее копирование, изменение и повторная публикация со ссылкой на источник и описанием изменений. Права третьих лиц и сертификация безопасности не предоставляются. Удаление страницы не отзывает полученные копии. Обязательные законные права сохраняются.','Материал справочный, а не утверждённый наряд-допуск. Компетентный специалист должен проверить объект, местные нормы и меры до начала работ.','Реклама и внешняя аналитика отключены. Просмотры учитывают визиты с входом, использование — действия, а не уникальных людей или работу на объекте.','Личность оператора и связь без аккаунта ещё проверяются. Запросы бета-версии требуют входа.'],
 ar:['استفسار عام','اقتراح','الدعم والحقوق','الطلبات خاصة ويراجعها المشغّل. تظهر الردود هنا. لا تدخل كلمات مرور أو وثائق هوية أو أسرار الموقع.','إعادة الاستخدام v1: تبقى الحقوق للمؤلف. يسمح بالنسخ والتعديل وإعادة النشر للعمل مع رابط المصدر وبيان التغييرات. لا يمنح حقوق الغير أو شهادة سلامة. حذف الصفحة لا يسترجع النسخ السابقة. لا تتأثر الحقوق القانونية الإلزامية.','المحتوى مرجع وليس تصريح عمل معتمداً. يجب على مختص مراجعة ظروف الموقع والقواعد المحلية والتدابير قبل العمل.','الإعلانات والتحليلات الخارجية معطلة. المشاهدات تحصي الزيارات المسجلة والاستخدام يحصي الإجراءات، لا الأشخاص الفريدين أو العمل الفعلي بالموقع.','هوية المشغّل وقناة غير الأعضاء قيد التحقق. تتطلب طلبات النسخة التجريبية تسجيل الدخول.'],
};
export function getCommunityPolicy(locale='en-US') {
 const row=rows[locale.split('-')[0]]||rows.en;
 const policy=Object.fromEntries(['general','suggestion','support','privateHelp','reuseTerms','safetyHelp','measurement','pendingContact'].map((k,i)=>[k,row[i]]));
 // Replace the historical disabled-analytics sentence, retaining the explanation of public counters.
 policy.measurement=getAnalyticsText(locale).body+' '+row[6].replace(/^[^.。]*[.。]\s*/, '');
 return policy;
}
