// Shared editorial copy. Country-specific guidance is kept separately from language.
export const GUIDE_LANGUAGES = ['ko','en','de','ja','fr','it','es','ar','pt','ru'];
const rows = `
library|실무 가이드|Field guides|Praxisleitfäden|実務ガイド|Guides pratiques|Guide operative|Guías prácticas|أدلة العمل|Guias práticos|Практические руководства
common|작업 전 안전계획|Pre-work safety planning|Sicherheitsplanung vor Arbeitsbeginn|作業前の安全計画|Préparation de la sécurité au travail|Pianificazione della sicurezza|Planificación preventiva del trabajo|تخطيط السلامة قبل العمل|Planejamento de segurança antes do trabalho|Планирование безопасности перед работой
construction|건설 작업 가이드|Construction work guide|Leitfaden für Bauarbeiten|建設作業ガイド|Guide des travaux de construction|Guida ai lavori edili|Guía de trabajos de construcción|دليل أعمال البناء|Guia de trabalhos de construção|Руководство по строительным работам
manufacturing|제조·설비 정비 가이드|Manufacturing and maintenance guide|Leitfaden für Fertigung und Instandhaltung|製造・設備保全ガイド|Guide de fabrication et de maintenance|Guida alla produzione e manutenzione|Guía de fabricación y mantenimiento|دليل التصنيع والصيانة|Guia de fabricação e manutenção|Руководство по производству и обслуживанию
chemical|화학·가스 작업 가이드|Chemical and gas work guide|Leitfaden für Chemikalien und Gase|化学・ガス作業ガイド|Guide des travaux chimiques et gaziers|Guida ai lavori con sostanze chimiche e gas|Guía de trabajos con sustancias químicas y gases|دليل الأعمال الكيميائية والغاز|Guia de trabalhos com produtos químicos e gases|Руководство по работам с химикатами и газами
high-risk|고위험 작업 가이드|High-risk work guide|Leitfaden für besonders gefährliche Arbeiten|高リスク作業ガイド|Guide des travaux à risques élevés|Guida ai lavori ad alto rischio|Guía de trabajos de alto riesgo|دليل الأعمال عالية المخاطر|Guia de trabalhos de alto risco|Руководство по работам повышенной опасности
general|일상·서비스 작업 가이드|Everyday and service work guide|Leitfaden für Alltags- und Servicearbeiten|日常・サービス作業ガイド|Guide des activités courantes et de service|Guida alle attività quotidiane e di servizio|Guía de actividades cotidianas y de servicios|دليل الأعمال اليومية والخدمية|Guia de atividades diárias e de serviços|Руководство по повседневным и сервисным работам
intro|작업 예시에서 위험요인과 확인 항목을 살펴보고, 현장 조건에 맞는 위험성평가와 작업 서류로 연결하세요.|Review hazards and checks for each example, then prepare an assessment and work documents for your actual site.|Prüfen Sie Gefährdungen und Prüfpunkte der Beispiele und erstellen Sie anschließend die Beurteilung und Arbeitsunterlagen für Ihren Einsatzort.|作業例の危険要因と確認事項を確認し、実際の現場に合うリスクアセスメントと作業書類を作成します。|Examinez les dangers et les points à vérifier, puis préparez une analyse et des documents adaptés au lieu de travail.|Esaminate i pericoli e i controlli degli esempi, poi preparate la valutazione e i documenti per il luogo di lavoro reale.|Revise los peligros y las comprobaciones de los ejemplos y prepare la evaluación y los documentos para su lugar de trabajo.|راجع المخاطر ونقاط التحقق في الأمثلة، ثم أعد التقييم ومستندات العمل بما يلائم موقعك الفعلي.|Analise os perigos e as verificações dos exemplos e prepare a avaliação e os documentos para o local real.|Изучите опасности и проверочные пункты примеров, затем подготовьте оценку и документы для конкретного рабочего места.
region|국가·지역과 언어|Country, region and language|Land, Region und Sprache|国・地域と言語|Pays, région et langue|Paese, regione e lingua|País, región e idioma|الدولة والمنطقة واللغة|País, região e idioma|Страна, регион и язык
contents|이 가이드에서|In this guide|In diesem Leitfaden|目次|Dans ce guide|In questa guida|En esta guía|في هذا الدليل|Neste guia|В этом руководстве
local|현지 문서와 적용 범위|Local documents and scope|Örtliche Dokumente und Geltungsbereich|現地の文書と適用範囲|Documents locaux et champ d’application|Documenti locali e ambito|Documentos locales y ámbito|المستندات المحلية ونطاق التطبيق|Documentos locais e abrangência|Местные документы и область применения
workflow|현장에 적용하는 순서|From example to site use|Vom Beispiel zum Einsatzort|現場に適用する手順|De l’exemple au terrain|Dall’esempio al luogo di lavoro|Del ejemplo al lugar de trabajo|من المثال إلى التطبيق بالموقع|Do exemplo à aplicação no local|От примера к применению на месте
examples|작업별 위험요인과 확인 항목|Task hazards and checks|Gefährdungen und Prüfpunkte je Tätigkeit|作業別の危険要因と確認事項|Dangers et vérifications par tâche|Pericoli e verifiche per attività|Peligros y comprobaciones por tarea|المخاطر والتحقق حسب المهمة|Perigos e verificações por tarefa|Опасности и проверки по видам работ
hazard|예상 위험요인|Potential hazards|Mögliche Gefährdungen|想定される危険要因|Dangers potentiels|Pericoli potenziali|Peligros potenciales|المخاطر المحتملة|Perigos potenciais|Возможные опасности
checks|현장에서 확인하고 구체화할 사항|Checks to verify and specify on site|Vor Ort zu prüfende und zu konkretisierende Punkte|現場で確認・具体化する事項|Points à vérifier et préciser sur place|Verifiche da effettuare e precisare sul posto|Puntos que verificar y concretar en el lugar|نقاط يجب التحقق منها وتحديدها في الموقع|Pontos a verificar e detalhar no local|Что проверить и уточнить на месте
sources|공식 참고 자료|Official references|Offizielle Quellen|公的な参考資料|Références officielles|Riferimenti ufficiali|Referencias oficiales|المراجع الرسمية|Referências oficiais|Официальные источники
download|현지화 PDF 다운로드|Download localised PDF|Lokalisiertes PDF herunterladen|現地版PDFをダウンロード|Télécharger le PDF localisé|Scarica il PDF localizzato|Descargar PDF localizado|تنزيل ملف PDF المحلي|Baixar PDF localizado|Скачать локализованный PDF
preview|PDF 미리보기|Preview PDF|PDF-Vorschau|PDFプレビュー|Aperçu du PDF|Anteprima PDF|Vista previa del PDF|معاينة PDF|Visualizar PDF|Просмотр PDF
close|미리보기 닫기|Close preview|Vorschau schließen|プレビューを閉じる|Fermer l’aperçu|Chiudi anteprima|Cerrar vista previa|إغلاق المعاينة|Fechar visualização|Закрыть просмотр
pdfHelp|본문과 같은 국가·언어의 안내서를 제공합니다. 아래 본문에서도 전체 내용을 읽을 수 있습니다.|The PDF uses the same country and language as this page. All content is also readable below.|Das PDF entspricht Land und Sprache dieser Seite. Der gesamte Inhalt ist auch unten lesbar.|このページと同じ国・言語のPDFです。下の本文でも全文を読めます。|Le PDF correspond au pays et à la langue de cette page. Le texte complet est aussi disponible ci-dessous.|Il PDF corrisponde al paese e alla lingua della pagina. Il testo completo è leggibile anche qui sotto.|El PDF corresponde al país y al idioma de esta página. El contenido completo también está disponible debajo.|ملف PDF مطابق لدولة هذه الصفحة ولغتها. ويمكن قراءة المحتوى كاملاً أدناه.|O PDF corresponde ao país e ao idioma desta página. O conteúdo completo também pode ser lido abaixo.|PDF соответствует стране и языку страницы. Полный текст также доступен ниже.
create|위험성평가 작성|Create an assessment|Beurteilung erstellen|リスクアセスメントを作成|Créer une analyse|Crea una valutazione|Crear una evaluación|إنشاء تقييم|Criar uma avaliação|Создать оценку
package|작업별 서류 묶음|Work document packages|Arbeitsunterlagen-Pakete|作業別の書類セット|Dossiers de travail|Pacchetti di documenti|Paquetes de documentos de trabajo|حزم مستندات العمل|Pacotes de documentos de trabalho|Комплекты рабочих документов
explore|공개 JSA 찾아보기|Explore public JSA|Öffentliche JSA durchsuchen|公開JSAを探す|Explorer les JSA publiques|Esplora JSA pubbliche|Explorar JSA públicas|استكشاف JSA العامة|Explorar JSA públicas|Просмотреть открытые JSA
edition|콘텐츠 개정|Content revision|Inhaltsstand|コンテンツ改訂|Version du contenu|Revisione dei contenuti|Revisión del contenido|مراجعة المحتوى|Revisão do conteúdo|Редакция содержания
scope|작업계획을 위한 참고 가이드입니다. 수치 기준·허가·자격은 해당 국가, 업종과 설비에 맞춰 확인하고, 현장 측정값·작업자·서명은 작업할 때 새로 기록하세요.|This is a planning reference. Verify numerical limits, permits and qualifications for the jurisdiction, sector and equipment. Record fresh site measurements, people and signatures for each job.|Dies ist eine Planungshilfe. Grenzwerte, Erlaubnisse und Qualifikationen sind für Region, Branche und Anlage zu prüfen. Messwerte, Personen und Unterschriften sind je Einsatz neu zu erfassen.|作業計画の参考資料です。数値基準・許可・資格は国・業種・設備に合わせて確認し、測定値・作業者・署名は作業ごとに新しく記録してください。|Ce guide aide à préparer le travail. Vérifiez les seuils, permis et compétences selon le territoire, le secteur et l’équipement. Relevez de nouvelles mesures, personnes et signatures à chaque intervention.|Guida di supporto alla pianificazione. Verificate limiti, permessi e qualifiche per territorio, settore e attrezzatura. Registrate nuove misure, persone e firme per ogni intervento.|Guía de apoyo a la planificación. Verifique límites, permisos y cualificaciones según territorio, sector y equipo. Registre mediciones, personas y firmas nuevas para cada trabajo.|هذا مرجع للتخطيط. تحقق من الحدود والتصاريح والمؤهلات وفق المنطقة والقطاع والمعدات. سجل قياسات وأسماء وتوقيعات جديدة لكل عمل.|Referência para planejamento. Verifique limites, permissões e qualificações conforme a região, o setor e o equipamento. Registre novas medições, pessoas e assinaturas a cada trabalho.|Справочный материал для планирования. Проверьте пределы, разрешения и квалификацию для региона, отрасли и оборудования. Для каждой работы заново записывайте измерения, участников и подписи.
step1|작업 범위를 나누세요|Define the job|Arbeit abgrenzen|作業範囲を分ける|Définir le travail|Definire il lavoro|Definir el trabajo|تحديد العمل|Definir o trabalho|Определите работу
step1Body|설비·장소·작업 순서와 함께 작업자, 주변 작업, 접근 동선을 확인합니다. 준비·본작업·정리 단계를 나누고 실제로 관찰한 위험요인을 적습니다.|Identify equipment, location, sequence, people, nearby activities and access. Separate preparation, execution and close-out, and record hazards observed at the site.|Anlage, Ort, Ablauf, Personen, benachbarte Tätigkeiten und Zugang erfassen. Vorbereitung, Ausführung und Abschluss trennen und beobachtete Gefährdungen dokumentieren.|設備・場所・手順、作業者、周辺作業、動線を確認します。準備・実施・片付けに分け、現場で確認した危険要因を記録します。|Repérez les équipements, le lieu, les étapes, les personnes, les activités voisines et les accès. Distinguez préparation, exécution et clôture et notez les dangers observés.|Identificate attrezzature, luogo, sequenza, persone, attività vicine e accessi. Distinguete preparazione, esecuzione e chiusura e annotate i pericoli osservati.|Identifique equipos, lugar, secuencia, personas, actividades cercanas y accesos. Separe preparación, ejecución y cierre y registre los peligros observados.|حدد المعدات والمكان والتسلسل والأشخاص والأعمال المجاورة ومسارات الوصول. افصل التحضير والتنفيذ والإغلاق وسجل المخاطر المرصودة.|Identifique equipamentos, local, sequência, pessoas, atividades próximas e acessos. Separe preparação, execução e encerramento e registre os perigos observados.|Укажите оборудование, место, этапы, людей, соседние работы и доступ. Разделите подготовку, выполнение и завершение; запишите выявленные опасности.
step2|대책을 작업 순서에 연결하세요|Match controls to each step|Maßnahmen den Schritten zuordnen|手順ごとに対策をつなぐ|Associer les mesures aux étapes|Collegare le misure alle fasi|Asignar medidas a cada etapa|ربط الضوابط بكل خطوة|Associar medidas às etapas|Свяжите меры с этапами
step2Body|위험 제거·대체·공학적 방호를 먼저 검토하고 절차와 보호구를 보완합니다. 각 대책의 담당자, 확인 방법, 작업 중지 조건을 정합니다.|Consider elimination, substitution and engineering controls first, then procedures and PPE. Assign an owner, a verification method and stop-work conditions for each control.|Beseitigung, Ersatz und technische Maßnahmen zuerst prüfen, danach Verfahren und PSA. Verantwortliche, Prüfmethode und Abbruchbedingungen je Maßnahme festlegen.|除去・代替・工学的対策を先に検討し、手順と保護具を補います。対策ごとに担当者、確認方法、中止条件を決めます。|Privilégiez l’élimination, la substitution et les protections techniques, puis les procédures et EPI. Définissez responsables, vérifications et conditions d’arrêt.|Considerate prima eliminazione, sostituzione e misure tecniche, poi procedure e DPI. Definite responsabili, verifiche e condizioni di sospensione.|Priorice eliminación, sustitución y medidas técnicas, después procedimientos y EPI. Defina responsables, comprobaciones y condiciones de parada.|ابدأ بالإزالة والاستبدال والضوابط الهندسية، ثم الإجراءات ومعدات الوقاية. حدد المسؤول وطريقة التحقق وشروط إيقاف العمل.|Priorize eliminação, substituição e medidas de engenharia, depois procedimentos e EPI. Defina responsáveis, verificação e condições de parada.|Сначала рассмотрите устранение, замену и технические меры, затем процедуры и СИЗ. Назначьте ответственных, способ проверки и условия остановки.
step3|서류와 현장 확인을 연결하세요|Connect documents and site checks|Unterlagen und Vor-Ort-Prüfung verbinden|書類と現場確認をつなぐ|Relier documents et vérifications|Collegare documenti e verifiche|Conectar documentos y comprobaciones|ربط المستندات والتحقق الميداني|Conectar documentos e verificações|Свяжите документы с проверками
step3Body|현지 명칭의 평가서·절차서와 필요한 허가서를 선택하고, 작업 전 회의에서 내용을 확인합니다. 도면·점검표를 묶고 변경 시 재평가한 후 이번 작업의 출력본을 보관합니다.|Choose the local assessment, procedure and applicable permits, then brief the crew. Add drawings and checklists, reassess changes and retain the output for this job.|Örtliche Beurteilung, Arbeitsanweisung und erforderliche Erlaubnisse wählen und das Team unterweisen. Pläne und Checklisten ergänzen, Änderungen neu beurteilen und den Einsatzstand aufbewahren.|現地の評価書・手順書と必要な許可書を選び、作業前に共有します。図面・点検表をまとめ、変更時は再評価し、今回の出力版を保管します。|Choisissez l’analyse, la procédure et les permis adaptés et informez l’équipe. Ajoutez plans et listes de contrôle, réévaluez les changements et conservez le dossier de l’intervention.|Scegliete valutazione, procedura e permessi pertinenti e informate la squadra. Aggiungete disegni e liste, rivalutate le modifiche e conservate i documenti dell’intervento.|Seleccione evaluación, procedimiento y permisos pertinentes e informe al equipo. Añada planos y listas, reevalúe los cambios y conserve los documentos del trabajo.|اختر التقييم والإجراء والتصاريح المناسبة وناقشها مع الفريق. أضف الرسومات وقوائم الفحص وأعد تقييم التغييرات واحتفظ بمخرجات العمل.|Escolha a avaliação, o procedimento e as permissões aplicáveis e oriente a equipe. Inclua desenhos e listas, reavalie mudanças e guarde a versão usada no trabalho.|Выберите местные формы оценки, процедуры и нужные разрешения; обсудите их с бригадой. Добавьте чертежи и проверки, оцените изменения и сохраните документы этой работы.
equipment|제조사 절차, 방호장치, 에너지 차단과 잔류에너지 해소를 확인하고 재가동 전 인원·공구를 점검합니다.|Check manufacturer procedures, guards, energy isolation and release of stored energy; account for people and tools before restart.|Herstellerverfahren, Schutzeinrichtungen, Energietrennung und Restenergieabbau prüfen; vor Wiederanlauf Personen und Werkzeuge kontrollieren.|メーカー手順、ガード、エネルギー遮断と残留エネルギー除去を確認し、再起動前に人員・工具を確認します。|Vérifiez les procédures du fabricant, protecteurs, isolement et dissipation des énergies; contrôlez personnes et outils avant remise en marche.|Verificate procedure del fabbricante, ripari, isolamento e dissipazione delle energie; controllate persone e utensili prima del riavvio.|Verifique procedimientos del fabricante, resguardos, aislamiento y disipación de energías; compruebe personas y herramientas antes de reiniciar.|تحقق من إجراءات المصنع والحواجز وعزل الطاقة وتفريغ الطاقة المخزنة، ومن الأشخاص والأدوات قبل إعادة التشغيل.|Verifique procedimentos do fabricante, proteções, isolamento e dissipação de energias; confira pessoas e ferramentas antes de reiniciar.|Проверьте инструкции изготовителя, ограждения, отключение и снятие остаточной энергии; перед пуском учтите людей и инструменты.
chemicalCheck|SDS와 물질 적합성, 밀폐·국소배기, 누출 차단 및 비상조치를 확인합니다. 측정 대상·허용기준과 호흡보호구는 실제 물질·노출조건에 맞춰 선정합니다.|Check the SDS, compatibility, containment, extraction, leak isolation and emergency response. Select test targets, limits and respiratory protection for the actual substances and exposure.|Sicherheitsdatenblatt, Verträglichkeit, Einhausung, Absaugung, Leckageabsperrung und Notfallmaßnahmen prüfen. Messstoffe, Grenzwerte und Atemschutz nach Stoff und Exposition auswählen.|SDS、適合性、密閉・局所排気、漏えい遮断と緊急対応を確認します。測定対象・基準・呼吸用保護具は物質とばく露条件に合わせて選定します。|Vérifiez FDS, compatibilité, confinement, captage, isolement des fuites et urgence. Choisissez mesures, limites et protection respiratoire selon substances et exposition.|Verificate SDS, compatibilità, contenimento, aspirazione, isolamento delle perdite ed emergenze. Scegliete misure, limiti e protezione respiratoria in base a sostanze ed esposizione.|Revise FDS, compatibilidad, contención, extracción, aislamiento de fugas y emergencias. Seleccione mediciones, límites y protección respiratoria según sustancias y exposición.|راجع صحيفة بيانات السلامة والتوافق والاحتواء والشفط وعزل التسرب والطوارئ. اختر القياسات والحدود وحماية التنفس وفق المواد والتعرض الفعلي.|Verifique FDS, compatibilidade, contenção, exaustão, isolamento de vazamentos e emergência. Selecione medições, limites e proteção respiratória conforme substâncias e exposição.|Проверьте паспорт безопасности, совместимость, герметизацию, вытяжку, локализацию утечек и аварийные действия. Измерения, пределы и защиту дыхания выбирайте по веществам и воздействию.
lifting|중량·무게중심·인양점·장비 정격과 줄걸이 각도를 확인합니다. 지반·이동경로·통제구역과 신호 방법을 정하고 해당 인양계획에 따라 작업합니다.|Verify weight, centre of gravity, lifting points, rated capacity and sling angles. Define ground conditions, route, exclusion zone and signals; follow the lift plan.|Gewicht, Schwerpunkt, Anschlagpunkte, Tragfähigkeit und Anschlagwinkel prüfen. Boden, Weg, Sperrbereich und Signale festlegen und Hebeplan einhalten.|重量・重心・吊り点・定格荷重・玉掛け角度を確認します。地盤・経路・立入禁止区域・合図を定め、揚重計画に従います。|Vérifiez poids, centre de gravité, points de levage, capacité et angles d’élingage. Définissez sol, trajet, zone interdite et signaux selon le plan de levage.|Verificate peso, baricentro, punti di sollevamento, portata e angoli delle brache. Definite terreno, percorso, area esclusa e segnali secondo il piano di sollevamento.|Verifique peso, centro de gravedad, puntos de izado, capacidad y ángulos de eslingas. Defina terreno, ruta, zona excluida y señales según el plan de izado.|تحقق من الوزن ومركز الثقل ونقاط الرفع والحمولة المقننة وزوايا الحبال. حدد الأرض والمسار ومنطقة العزل والإشارات واتبع خطة الرفع.|Verifique peso, centro de gravidade, pontos de içamento, capacidade e ângulos das lingas. Defina terreno, rota, isolamento e sinais conforme o plano de içamento.|Проверьте массу, центр тяжести, точки подъема, грузоподъемность и углы стропов. Определите грунт, маршрут, зону ограждения и сигналы по плану подъема.
excavation|매설물·지반·인접 구조물을 조사하고 굴착 깊이와 토질에 맞는 지보·사면 계획을 정합니다. 접근·배수·장비 이격과 상태 변화 시 재점검을 확인합니다.|Survey utilities, soil and adjacent structures. Plan support or slopes for depth and ground conditions; check access, drainage, plant separation and inspections after changes.|Leitungen, Boden und Nachbarbauwerke erkunden. Verbau oder Böschung nach Tiefe und Boden planen; Zugang, Entwässerung, Geräteabstand und Kontrollen bei Änderungen prüfen.|埋設物・地盤・隣接構造物を調査し、深さと土質に合う土留め・法面計画を定めます。通路・排水・機械の離隔と変化時の再点検を確認します。|Repérez réseaux, terrain et structures voisines. Prévoyez soutènement ou talus selon profondeur et sol; vérifiez accès, drainage, distances des engins et inspections après changement.|Individuate sottoservizi, terreno e strutture vicine. Pianificate sostegno o pendenze secondo profondità e suolo; verificate accessi, drenaggio, distanze e ispezioni dopo cambiamenti.|Investigue servicios, suelo y estructuras cercanas. Planifique entibación o taludes según profundidad y terreno; compruebe acceso, drenaje, separación de maquinaria e inspecciones tras cambios.|افحص الخدمات المدفونة والتربة والمنشآت المجاورة. خطط للتدعيم أو الميول حسب العمق والتربة وتحقق من الوصول والصرف وفصل المعدات وإعادة الفحص عند التغيير.|Investigue redes, solo e estruturas vizinhas. Planeje escoramento ou taludes conforme profundidade e solo; confira acesso, drenagem, afastamento de máquinas e inspeções após mudanças.|Исследуйте коммуникации, грунт и соседние сооружения. Выберите крепление или откосы по глубине и грунту; проверьте доступ, водоотвод, расстояния до машин и осмотр после изменений.
pressure|시험·개방 전에 유체와 압력을 차단·해소하고 확인합니다. 시험압력·매체·승압 순서는 설계규격과 승인된 절차에 따르며, 접근통제와 이상 시 중지 조건을 정합니다.|Isolate, release and verify pressure and contents before opening. Use the design code and approved procedure for test pressure, medium and sequence; define exclusion and stop criteria.|Druck und Inhalt vor Öffnung absperren, abbauen und prüfen. Prüfdruck, Medium und Ablauf nach Auslegungsregel und freigegebenem Verfahren festlegen; Sperr- und Abbruchkriterien bestimmen.|開放前に流体と圧力を遮断・解放し確認します。試験圧力・媒体・昇圧手順は設計規格と承認手順に従い、立入制限と中止条件を定めます。|Isolez, dépressurisez et vérifiez le contenu avant ouverture. Définissez pression, fluide et séquence d’essai selon le code de conception et la procédure approuvée; fixez exclusion et arrêt.|Isolate, scaricate e verificate pressione e contenuto prima dell’apertura. Seguite norma di progetto e procedura approvata per pressione, fluido e sequenza di prova; definite esclusione e arresto.|Aísle, libere y verifique presión y contenido antes de abrir. Use el código de diseño y el procedimiento aprobado para presión, medio y secuencia de prueba; defina exclusión y parada.|اعزل الضغط والمحتويات وفرغها وتحقق منها قبل الفتح. اتبع معيار التصميم والإجراء المعتمد لضغط الاختبار ووسطه وتسلسله وحدد العزل وشروط الإيقاف.|Isole, alivie e verifique pressão e conteúdo antes de abrir. Siga o código de projeto e procedimento aprovado para pressão, fluido e sequência de teste; defina isolamento e parada.|Перед вскрытием изолируйте, сбросьте и проверьте давление и содержимое. Давление, среду и порядок испытания определяйте по проектной норме и утвержденной процедуре; задайте зону и условия остановки.
traffic|차량과 보행 동선을 분리하고 시야·후진·하역 장소를 확인합니다. 속도와 유도 방법은 현장 조건에 맞춰 정하며, 불안정한 적재·지반에서는 작업을 중지합니다.|Separate vehicles and pedestrians; check visibility, reversing and loading areas. Set speed and signalling for the site, and stop for unstable loads or ground.|Fahrzeuge und Fußgänger trennen; Sicht, Rückwärtsfahrt und Ladebereiche prüfen. Geschwindigkeit und Einweisung örtlich festlegen; bei instabiler Last oder Boden stoppen.|車両と歩行者の動線を分け、視界・後退・荷役場所を確認します。速度と誘導方法は現場に合わせ、荷や地盤が不安定なら中止します。|Séparez véhicules et piétons; vérifiez visibilité, marche arrière et chargement. Adaptez vitesse et guidage au site et arrêtez si charge ou sol instable.|Separate veicoli e pedoni; verificate visibilità, retromarcia e carico. Adeguate velocità e segnalazioni al sito e fermatevi con carichi o terreno instabili.|Separe vehículos y peatones; compruebe visibilidad, marcha atrás y carga. Adapte velocidad y señales al lugar y detenga el trabajo con cargas o terreno inestables.|افصل المركبات والمشاة وتحقق من الرؤية والرجوع والتحميل. حدد السرعة والإشارات حسب الموقع وتوقف عند عدم استقرار الحمولة أو الأرض.|Separe veículos e pedestres; confira visibilidade, marcha à ré e carga. Ajuste velocidade e sinalização ao local e pare com carga ou terreno instável.|Разделите движение машин и пешеходов; проверьте обзор, задний ход и погрузку. Задайте скорость и сигналы по условиям; остановитесь при неустойчивом грузе или грунте.
specialist|작업에 필요한 교육·자격과 전용 절차를 확인합니다. 공정·장비별 방호, 노출관리, 비상대응 및 현장 책임자의 확인을 작업계획에 구체적으로 기록합니다.|Verify task-specific training, qualifications and procedures. Record process and equipment protections, exposure controls, emergency arrangements and the responsible person's checks in the work plan.|Tätigkeitsbezogene Schulung, Qualifikation und Verfahren prüfen. Prozess- und Geräteschutz, Expositionskontrolle, Notfallorganisation und verantwortliche Prüfungen im Arbeitsplan festhalten.|作業別の教育・資格と専用手順を確認します。工程・機器の防護、ばく露管理、緊急対応と責任者の確認を作業計画に具体化します。|Vérifiez formation, qualifications et procédures propres à l’activité. Précisez protections, maîtrise des expositions, urgences et vérifications du responsable dans le plan de travail.|Verificate formazione, qualifiche e procedure specifiche. Documentate protezioni, controllo delle esposizioni, emergenze e verifiche del responsabile nel piano di lavoro.|Verifique formación, cualificaciones y procedimientos específicos. Detalle protecciones, control de exposición, emergencias y comprobaciones del responsable en el plan de trabajo.|تحقق من التدريب والمؤهلات والإجراءات الخاصة بالمهمة. سجل وسائل الحماية وضبط التعرض والطوارئ وفحوص المسؤول بالتفصيل في خطة العمل.|Verifique treinamento, qualificações e procedimentos específicos. Registre proteções, controle de exposição, emergência e verificações do responsável no plano de trabalho.|Проверьте обучение, квалификацию и специальные процедуры. Укажите в плане защиты процесса и оборудования, контроль воздействия, аварийные меры и проверки ответственного.
related|다른 실무 가이드|More field guides|Weitere Praxisleitfäden|その他の実務ガイド|Autres guides pratiques|Altre guide operative|Otras guías prácticas|أدلة عملية أخرى|Outros guias práticos|Другие практические руководства
editorial|Smart JSA Bridge 편집 가이드|Smart JSA Bridge editorial guide|Redaktioneller Leitfaden von Smart JSA Bridge|Smart JSA Bridge 編集ガイド|Guide éditorial Smart JSA Bridge|Guida redazionale Smart JSA Bridge|Guía editorial de Smart JSA Bridge|دليل تحريري من Smart JSA Bridge|Guia editorial Smart JSA Bridge|Редакционное руководство Smart JSA Bridge
referenceHelp|아래 출처는 현지 명칭과 적용 범위를 확인하기 위한 자료입니다. 작업 예시는 Smart JSA Bridge가 정리한 참고 항목이며 공식 발행 양식이 아닙니다.|These sources support local terminology and scope. The examples are editorial planning prompts from Smart JSA Bridge, not official forms.|Die Quellen erläutern örtliche Begriffe und Geltungsbereiche. Die Beispiele sind redaktionelle Planungshilfen von Smart JSA Bridge, keine amtlichen Formulare.|下記は現地の用語と適用範囲を確認する資料です。作業例はSmart JSA Bridgeが整理した参考項目で、公的な様式ではありません。|Ces sources éclairent les termes locaux et leur portée. Les exemples sont des aides éditoriales de Smart JSA Bridge, pas des formulaires officiels.|Le fonti chiariscono termini locali e ambito. Gli esempi sono spunti redazionali di Smart JSA Bridge, non moduli ufficiali.|Las fuentes aclaran términos locales y alcance. Los ejemplos son orientaciones editoriales de Smart JSA Bridge, no formularios oficiales.|توضح المصادر المصطلحات المحلية ونطاقها. الأمثلة نقاط تخطيط تحريرية من Smart JSA Bridge وليست نماذج رسمية.|As fontes esclarecem termos locais e abrangência. Os exemplos são orientações editoriais do Smart JSA Bridge, não formulários oficiais.|Источники поясняют местные термины и область применения. Примеры являются редакционными подсказками Smart JSA Bridge, а не официальными формами.
pdfUnavailable|PDF를 불러오지 못했습니다. 다운로드 링크를 이용하거나 아래 본문을 확인하세요.|The PDF could not be loaded. Use the download link or read the text below.|Das PDF konnte nicht geladen werden. Nutzen Sie den Download oder den Text unten.|PDFを読み込めません。ダウンロードリンクまたは下の本文をご利用ください。|Le PDF n’a pas pu être chargé. Utilisez le téléchargement ou le texte ci-dessous.|Impossibile caricare il PDF. Usate il download o il testo qui sotto.|No se pudo cargar el PDF. Use la descarga o el texto inferior.|تعذر تحميل PDF. استخدم رابط التنزيل أو النص أدناه.|Não foi possível carregar o PDF. Use o download ou o texto abaixo.|Не удалось загрузить PDF. Используйте ссылку скачивания или текст ниже.
loading|PDF 불러오는 중|Loading PDF|PDF wird geladen|PDFを読み込み中|Chargement du PDF|Caricamento PDF|Cargando PDF|جار تحميل PDF|Carregando PDF|Загрузка PDF
print|인쇄|Print|Drucken|印刷|Imprimer|Stampa|Imprimir|طباعة|Imprimir|Печать
read|본문 읽기|Read the guide|Leitfaden lesen|本文を読む|Lire le guide|Leggi la guida|Leer la guía|قراءة الدليل|Ler o guia|Читать руководство
records|새로 기록할 현장 정보|Fresh site records|Aktuelle Angaben vor Ort|今回記録する現場情報|Nouveaux relevés sur place|Nuovi dati del luogo di lavoro|Nuevos registros del lugar|سجلات ميدانية جديدة|Novos registros do local|Новые записи с места работ
recordsBody|작업일·장소·설비번호, 담당자·참여자, 허가번호, 측정값·측정시각·측정자, 점검 결과와 변경사항을 기록하세요. 이전 작업의 서명과 측정값은 재사용하지 않습니다.|Record date, location, equipment ID, responsible people, crew, permit references, measurements, times, testers, inspections and changes. Do not reuse previous signatures or readings.|Datum, Ort, Anlagenkennung, Verantwortliche, Team, Erlaubnisse, Messwerte, Zeiten, Prüfer, Kontrollen und Änderungen erfassen. Alte Unterschriften und Messwerte nicht übernehmen.|作業日・場所・設備番号、担当者・参加者、許可番号、測定値・時刻・測定者、点検結果と変更を記録します。以前の署名や測定値は流用しません。|Notez date, lieu, équipement, responsables, équipe, permis, mesures, heures, opérateurs, inspections et changements. Ne réutilisez pas les signatures ou mesures antérieures.|Registrate data, luogo, attrezzatura, responsabili, squadra, permessi, misure, orari, addetti, verifiche e modifiche. Non riutilizzate firme o valori precedenti.|Registre fecha, lugar, equipo, responsables, personal, permisos, mediciones, horas, medidores, inspecciones y cambios. No reutilice firmas ni lecturas anteriores.|سجل التاريخ والمكان والمعدات والمسؤولين والفريق والتصاريح والقياسات وأوقاتها والقائمين بها والفحوص والتغييرات. لا تعِد استخدام التوقيعات أو القراءات السابقة.|Registre data, local, equipamento, responsáveis, equipe, permissões, medições, horários, medidores, inspeções e mudanças. Não reutilize assinaturas ou leituras anteriores.|Запишите дату, место, оборудование, ответственных, бригаду, разрешения, измерения, время, исполнителей, проверки и изменения. Не переносите прежние подписи и показания.
page|페이지|Page|Seite|ページ|Page|Pagina|Página|صفحة|Página|Страница
of|/|/|/|/|/|/|/|/|/|/
back|목록으로|Back to contents|Zur Übersicht|目次へ|Retour au sommaire|Torna all’indice|Volver al índice|العودة للفهرس|Voltar ao índice|К содержанию
pdfLabel|본문과 동일한 현지화 PDF|Localised PDF matching this guide|Lokalisiertes PDF zu diesem Leitfaden|本文と同じ現地版PDF|PDF localisé identique au guide|PDF localizzato uguale alla guida|PDF localizado igual a la guía|PDF محلي مطابق للدليل|PDF localizado igual ao guia|Локализованный PDF этого руководства
`;
export const GUIDE_TEXT = Object.fromEntries(rows.trim().split('\n').map(line => {
  const [key,...values]=line.split('|');
  if(values.length!==10 || values.some(v=>!v)) throw new Error(`Incomplete guide translation: ${key}`);
  return [key,Object.fromEntries(GUIDE_LANGUAGES.map((lang,i)=>[lang,values[i]]))];
}));
export function guideText(locale,key) { return GUIDE_TEXT[key]?.[locale.split('-')[0]] || GUIDE_TEXT[key]?.en || key; }
