const keys = ['title','intro','detail','reuse','scrap','saved','share','copied','unavailable','error','retry','more','empty','community','notice','steps','search','latest','popular','back','login','quality','report','reason','submit','reported'];
const labels = {
  en: ['Public JSA library','Browse shared work steps and adapt them to your site.','View JSA','Reuse work steps','Save to my library','Saved','Copy link','Link copied','This JSA is unavailable or private.','Unable to load. Please retry.','Retry','Load more','No matching public JSA.','Community contribution','Reference only. Review hazards and controls for your actual site before use.','Work steps','Search titles','Latest','Most saved','Back to library','Sign in','Shared reference — not a safety certification','Report','Reason for reporting','Submit','Report received'],
  ko: ['공개 JSA 라이브러리','공유된 작업단계를 살펴보고 현장에 맞게 재사용하세요.','JSA 상세 보기','작업단계 재사용','내 보관함에 스크랩','스크랩됨','링크 복사','링크를 복사했습니다','비공개이거나 사용할 수 없는 JSA입니다.','불러오지 못했습니다. 다시 시도해주세요.','다시 시도','더 보기','검색 조건에 맞는 공개 JSA가 없습니다.','사용자 공유 자료','참고용 자료입니다. 실제 현장의 위험요인과 대책을 검토한 뒤 사용하세요.','작업단계','제목 검색','최신순','스크랩순','목록으로','로그인','공유된 참고 자료이며 안전성 인증을 의미하지 않습니다.','신고','신고 사유','제출','신고를 접수했습니다'],
  de: ['Öffentliche JSA-Bibliothek','Geteilte Arbeitsschritte ansehen und an Ihren Standort anpassen.','JSA ansehen','Arbeitsschritte verwenden','In Bibliothek speichern','Gespeichert','Link kopieren','Link kopiert','Diese JSA ist privat oder nicht verfügbar.','Laden fehlgeschlagen. Bitte erneut versuchen.','Erneut versuchen','Mehr laden','Keine passende öffentliche JSA.','Community-Beitrag','Nur als Referenz. Gefahren und Maßnahmen vor Ort vor der Nutzung prüfen.','Arbeitsschritte','Titel suchen','Neueste','Meistgespeichert','Zur Übersicht','Anmelden','Referenzmaterial, keine Sicherheitszertifizierung','Melden','Grund der Meldung','Senden','Meldung erhalten'],
  fr: ['Bibliothèque JSA publique','Consultez les étapes partagées et adaptez-les à votre chantier.','Voir la JSA','Réutiliser les étapes','Enregistrer','Enregistré','Copier le lien','Lien copié','Cette JSA est privée ou indisponible.','Échec du chargement. Réessayez.','Réessayer','Afficher plus','Aucune JSA publique correspondante.','Contribution communautaire','Référence uniquement. Vérifiez les risques et mesures sur votre site avant utilisation.','Étapes','Rechercher un titre','Récentes','Les plus enregistrées','Retour à la liste','Se connecter','Document de référence, sans certification de sécurité','Signaler','Motif du signalement','Envoyer','Signalement reçu'],
  ja: ['公開JSAライブラリ','共有された作業手順を確認し、現場に合わせて再利用できます。','JSAの詳細','作業手順を再利用','ライブラリに保存','保存済み','リンクをコピー','コピーしました','非公開または利用できないJSAです。','読み込めませんでした。再試行してください。','再試行','もっと見る','該当する公開JSAはありません。','ユーザー共有資料','参考資料です。使用前に実際の現場の危険要因と対策を確認してください。','作業手順','タイトルを検索','新着順','保存数順','一覧へ','ログイン','参考資料であり、安全性の認証ではありません。','報告','報告理由','送信','報告を受け付けました'],
  es: ['Biblioteca pública de JSA','Consulta las etapas compartidas y adáptalas a tu lugar de trabajo.','Ver JSA','Reutilizar etapas','Guardar en mi biblioteca','Guardado','Copiar enlace','Enlace copiado','Esta JSA es privada o no está disponible.','Error al cargar. Inténtalo de nuevo.','Reintentar','Ver más','No hay JSA públicas coincidentes.','Aporte de la comunidad','Solo referencia. Revisa los peligros y las medidas en tu lugar de trabajo antes de usarlo.','Etapas','Buscar títulos','Recientes','Más guardados','Volver a la lista','Iniciar sesión','Referencia, sin certificación de seguridad','Denunciar','Motivo','Enviar','Denuncia recibida'],
  it: ['Biblioteca JSA pubblica','Consulta le fasi condivise e adattale al tuo sito.','Visualizza JSA','Riutilizza le fasi','Salva nella biblioteca','Salvato','Copia link','Link copiato','Questa JSA è privata o non disponibile.','Caricamento non riuscito. Riprova.','Riprova','Mostra altro','Nessuna JSA pubblica corrispondente.','Contributo della comunità','Solo riferimento. Verifica rischi e misure sul tuo sito prima dell’uso.','Fasi di lavoro','Cerca titoli','Recenti','Più salvati','Torna alla lista','Accedi','Riferimento, non una certificazione di sicurezza','Segnala','Motivo','Invia','Segnalazione ricevuta'],
  pt: ['Biblioteca pública de JSA','Consulte as etapas partilhadas e adapte-as ao seu local.','Ver JSA','Reutilizar etapas','Guardar na biblioteca','Guardado','Copiar ligação','Ligação copiada','Esta JSA é privada ou indisponível.','Falha ao carregar. Tente novamente.','Tentar novamente','Ver mais','Nenhuma JSA pública correspondente.','Contribuição da comunidade','Apenas referência. Reveja os riscos e medidas no seu local antes de usar.','Etapas','Pesquisar títulos','Recentes','Mais guardados','Voltar à lista','Entrar','Material de referência, sem certificação de segurança','Denunciar','Motivo','Enviar','Denúncia recebida'],
  ru: ['Публичная библиотека JSA','Просматривайте общие этапы и адаптируйте их к своему объекту.','Открыть JSA','Использовать этапы','Сохранить в библиотеку','Сохранено','Копировать ссылку','Ссылка скопирована','Эта JSA недоступна или закрыта.','Не удалось загрузить. Повторите попытку.','Повторить','Показать ещё','Подходящих публичных JSA нет.','Материал сообщества','Только для справки. Перед использованием проверьте риски и меры на своём объекте.','Этапы работы','Поиск по названию','Новые','Популярные','К списку','Войти','Справочный материал, не сертификат безопасности','Пожаловаться','Причина','Отправить','Жалоба получена'],
  ar: ['مكتبة JSA العامة','استعرض خطوات العمل المشتركة وعدّلها لتناسب موقعك.','عرض JSA','إعادة استخدام الخطوات','حفظ في مكتبتي','تم الحفظ','نسخ الرابط','تم نسخ الرابط','هذا المستند خاص أو غير متاح.','تعذر التحميل. حاول مجدداً.','إعادة المحاولة','عرض المزيد','لا توجد مستندات عامة مطابقة.','مساهمة مجتمعية','مرجع فقط. راجع المخاطر والتدابير في موقعك الفعلي قبل الاستخدام.','خطوات العمل','البحث بالعناوين','الأحدث','الأكثر حفظاً','العودة للقائمة','تسجيل الدخول','مادة مرجعية وليست شهادة سلامة','إبلاغ','سبب الإبلاغ','إرسال','تم استلام البلاغ'],
};
export function getPublicUi(locale = 'en-US') {
  const values = labels[locale.split('-')[0]] || labels.en;
  return Object.fromEntries(keys.map((key, i) => [key, values[i]]));
}
