const keys = ['intro', 'startTitle', 'startHelp', 'start', 'examples', 'blankPdf', 'paper', 'creating', 'error', 'attachments', 'attachmentHelp', 'download', 'linkedHelp'];
const rows = {
  ko: ['작업별 예시를 살펴보고, 현장에 맞게 작성해 PDF로 출력하세요.', '이번 작업 문서 시작하기', '작업 국가와 출력 언어를 확인하세요. 새 문서에는 작업명만 넣으며, 예시의 위험요인·대책은 자동 복사하지 않습니다.', '새 문서 작성', '현장 사례 연구 보기', '수기 작성용 빈 PDF', '출력 용지', 'PDF 생성 중…', 'PDF를 만들지 못했습니다. 다시 시도해주세요.', '이 사례의 첨부 PDF', '작성자가 첨부한 원본입니다. 아래 국가·언어 선택은 원본 PDF를 변경하지 않습니다.', '다운로드', '연결된 공개 JSA를 열면 작업단계를 확인하고 재사용할 수 있습니다.'],
  en: ['Explore task examples, adapt them to your site and export a PDF.', 'Start documents for your next job', 'Check the work country and document language. A new document includes only the task name; hazards and controls from the example are not copied automatically.', 'Create a new document', 'Explore case studies', 'Blank PDF for handwriting', 'Paper size', 'Creating PDF…', 'Could not create the PDF. Please try again.', 'PDF attachments for this case', 'Original files supplied by the author. The country and language selections below do not change these PDFs.', 'Download', 'Open a linked public JSA to review and reuse its work steps.'],
  de: ['Arbeitsbeispiele ansehen, an den Einsatzort anpassen und als PDF ausgeben.', 'Unterlagen für den nächsten Auftrag beginnen', 'Prüfen Sie Arbeitsland und Dokumentensprache. Nur die Tätigkeitsbezeichnung wird übernommen; Gefährdungen und Maßnahmen des Beispiels werden nicht automatisch kopiert.', 'Neues Dokument erstellen', 'Fallstudien ansehen', 'Leeres PDF zum handschriftlichen Ausfüllen', 'Papierformat', 'PDF wird erstellt…', 'Das PDF konnte nicht erstellt werden. Bitte erneut versuchen.', 'PDF-Anhänge zu diesem Beispiel', 'Originaldateien des Autors. Die folgende Länder- und Sprachauswahl ändert diese PDFs nicht.', 'Herunterladen', 'Öffnen Sie eine verknüpfte öffentliche JSA, um Arbeitsschritte zu prüfen und wiederzuverwenden.'],
  ja: ['作業例を確認し、現場に合わせて作成してPDFで出力できます。', '次の作業の書類を作成', '作業国と文書の言語を確認してください。新規文書には作業名のみを入力し、例の危険要因や対策は自動コピーしません。', '新規文書を作成', '現場の事例研究を見る', '手書き用の空欄PDF', '用紙サイズ', 'PDFを作成中…', 'PDFを作成できませんでした。もう一度お試しください。', 'この事例の添付PDF', '作成者が添付した原本です。以下の国・言語の選択では、これらのPDFは変更されません。', 'ダウンロード', '関連する公開JSAを開いて、作業手順を確認・再利用できます。'],
  fr: ['Consultez les exemples, adaptez-les à votre chantier et exportez un PDF.', 'Préparer les documents du prochain travail', 'Vérifiez le pays du travail et la langue du document. Seul le nom de la tâche est repris ; les dangers et les mesures de l’exemple ne sont pas copiés automatiquement.', 'Créer un document', 'Consulter les études de cas', 'PDF vierge à remplir à la main', 'Format du papier', 'Création du PDF…', 'Impossible de créer le PDF. Veuillez réessayer.', 'PDF joints à cette étude de cas', 'Fichiers originaux fournis par l’auteur. Le choix du pays et de la langue ci-dessous ne modifie pas ces PDF.', 'Télécharger', 'Ouvrez une analyse publique associée pour consulter et réutiliser ses étapes de travail.'],
  it: ['Consulta gli esempi, adattali al luogo di lavoro ed esporta un PDF.', 'Prepara i documenti del prossimo lavoro', 'Verifica il paese di lavoro e la lingua del documento. Viene inserito solo il nome dell’attività; pericoli e misure dell’esempio non vengono copiati automaticamente.', 'Crea un nuovo documento', 'Consulta i casi studio', 'PDF vuoto da compilare a mano', 'Formato carta', 'Creazione del PDF…', 'Impossibile creare il PDF. Riprova.', 'PDF allegati a questo caso', 'File originali forniti dall’autore. La selezione di paese e lingua qui sotto non modifica questi PDF.', 'Scarica', 'Apri una JSA pubblica collegata per esaminare e riutilizzare le fasi di lavoro.'],
  es: ['Consulta ejemplos de tareas, adáptalos al lugar de trabajo y exporta un PDF.', 'Prepara los documentos del próximo trabajo', 'Comprueba el país de trabajo y el idioma del documento. Solo se incluye el nombre de la tarea; los peligros y las medidas del ejemplo no se copian automáticamente.', 'Crear un documento', 'Ver estudios de caso', 'PDF en blanco para rellenar a mano', 'Tamaño del papel', 'Creando PDF…', 'No se pudo crear el PDF. Inténtalo de nuevo.', 'PDF adjuntos a este caso', 'Archivos originales aportados por el autor. La selección de país e idioma de abajo no modifica estos PDF.', 'Descargar', 'Abre un JSA público relacionado para revisar y reutilizar sus pasos de trabajo.'],
  ar: ['اطّلع على أمثلة المهام وعدّلها وفق موقع العمل ثم صدّرها بصيغة PDF.', 'ابدأ مستندات المهمة التالية', 'تحقق من بلد العمل ولغة المستند. يُدرج اسم المهمة فقط؛ ولا تُنسخ أخطار المثال وإجراءات التحكم تلقائياً.', 'إنشاء مستند جديد', 'استعراض دراسات الحالة', 'PDF فارغ للتعبئة بخط اليد', 'حجم الورق', 'جارٍ إنشاء PDF…', 'تعذّر إنشاء PDF. يرجى المحاولة مجدداً.', 'ملفات PDF المرفقة بهذه الحالة', 'ملفات أصلية أرفقها المؤلف. اختيار البلد واللغة أدناه لا يغيّر ملفات PDF هذه.', 'تنزيل', 'افتح تحليل سلامة عمل عاماً مرتبطاً لمراجعة خطوات العمل وإعادة استخدامها.'],
  pt: ['Consulte exemplos de tarefas, adapte-os ao local de trabalho e exporte um PDF.', 'Prepare os documentos do próximo trabalho', 'Confira o país de trabalho e o idioma do documento. Apenas o nome da tarefa é incluído; os perigos e as medidas do exemplo não são copiados automaticamente.', 'Criar um documento', 'Ver estudos de caso', 'PDF em branco para preencher à mão', 'Tamanho do papel', 'Criando PDF…', 'Não foi possível criar o PDF. Tente novamente.', 'PDFs anexos a este caso', 'Arquivos originais fornecidos pelo autor. A seleção de país e idioma abaixo não altera esses PDFs.', 'Baixar', 'Abra uma análise pública relacionada para revisar e reutilizar suas etapas de trabalho.'],
  ru: ['Изучите примеры работ, адаптируйте их к своему объекту и сохраните в PDF.', 'Подготовьте документы для следующей работы', 'Проверьте страну проведения работ и язык документа. Переносится только название задачи; опасности и меры из примера автоматически не копируются.', 'Создать документ', 'Посмотреть разборы практических случаев', 'Пустой PDF для заполнения от руки', 'Формат бумаги', 'Создание PDF…', 'Не удалось создать PDF. Попробуйте ещё раз.', 'PDF-приложения к этому примеру', 'Исходные файлы автора. Выбор страны и языка ниже не изменяет эти PDF.', 'Скачать', 'Откройте связанную общедоступную JSA, чтобы изучить и повторно использовать этапы работ.'],
};
export const regionalJourneyUi = locale => Object.fromEntries(keys.map((key, index) => [key, (rows[locale?.split('-')[0]] || rows.en)[index]]));
