// Columns: key | German | Japanese | French | Italian | Spanish | Arabic | Portuguese | Russian.
const languages = ['de', 'ja', 'fr', 'it', 'es', 'ar', 'pt', 'ru'];
function dictionaries(rows) {
  const result = Object.fromEntries(languages.map(l => [l, {}]));
  for (const line of rows.trim().split('\n')) {
    const [key, ...values] = line.split('|');
    if (values.length !== languages.length || values.some(v => !v.trim())) throw Error(`Incomplete regional translation: ${key}`);
    languages.forEach((l, i) => { result[l][key] = values[i]; });
  }
  return result;
}
export const regionalUiTranslations = dictionaries(`
title|Arbeitsland und Dokumentensprache|作業国と文書の言語|Pays de travail et langue des documents|Paese di lavoro e lingua dei documenti|País de trabajo e idioma del documento|بلد العمل ولغة المستند|País do trabalho e idioma do documento|Страна работ и язык документов
country|Arbeitsland / Zuständigkeit|作業国・管轄地域|Pays / territoire de travail|Paese / territorio di lavoro|País / jurisdicción del trabajo|بلد العمل / الاختصاص|País / jurisdição do trabalho|Страна / юрисдикция работ
region|Bundesland / Region|州・地域|État / région|Stato / regione|Estado / región|الولاية / المنطقة|Estado / região|Штат / регион
language|Dokumentensprache|出力文書の言語|Langue du document|Lingua del documento|Idioma del documento|لغة المستند|Idioma do documento|Язык документа
unspecified|Nicht festgelegt · allgemeine Vorlagen|未選択・汎用様式|Non précisé · modèles génériques|Non specificato · modelli generici|Sin especificar · modelos generales|غير محدد · نماذج عامة|Não especificado · modelos gerais|Не указано · общие формы
chooseLanguage|Dokumentensprache wählen|文書の言語を選択|Choisir la langue du document|Scegliere la lingua del documento|Elegir idioma del documento|اختر لغة المستند|Escolher idioma do documento|Выберите язык документа
industry|Branche|業種|Secteur d’activité|Settore|Sector|القطاع|Setor|Отрасль
activity|Arbeitstätigkeit|作業の種類|Activité|Attività lavorativa|Actividad de trabajo|نشاط العمل|Atividade de trabalho|Вид работ
help|Unabhängig von der Oberflächensprache gespeichert. Vorhandene Dokumente werden nicht umgeschrieben.|画面の言語とは別に保存します。追加済みの文書は変更されません。|Enregistré indépendamment de la langue de l’écran. Les documents existants ne sont pas réécrits.|Salvato separatamente dalla lingua dell’interfaccia. I documenti esistenti non vengono riscritti.|Se guarda por separado del idioma de la pantalla. No se reescriben los documentos existentes.|يُحفظ مستقلاً عن لغة الواجهة. لا تُعاد كتابة المستندات المضافة.|Salvo separadamente do idioma da tela. Os documentos existentes não são reescritos.|Сохраняется независимо от языка интерфейса. Добавленные документы не переписываются.
highRisk|Australien: Bauarbeiten mit hohem Risiko|豪州の高リスク建設作業への該当|Australie : travaux de construction à haut risque|Australia: lavori edili ad alto rischio|Australia: construcción de alto riesgo|أستراليا: أعمال إنشاء عالية الخطورة|Austrália: construção de alto risco|Австралия: строительные работы повышенного риска
yes|Ja|該当|Oui|Sì|Sí|نعم|Sim|Да
no|Nein|非該当|Non|No|No|لا|Não|Нет
unknown|Zu prüfen|要確認|À vérifier|Da verificare|Por confirmar|يلزم التحقق|A confirmar|Требует проверки
catalog|Regionale Grundvorlagen|国・地域別の基本様式|Modèles de base régionaux|Modelli di base regionali|Modelos básicos por región|النماذج الأساسية حسب المنطقة|Modelos básicos regionais|Региональные базовые формы
source|Zu übernehmende JSA|内容を取り込むJSA|JSA à réutiliser|JSA da riutilizzare|JSA que se reutilizará|تحليل سلامة العمل المراد استخدامه|JSA a reutilizar|Исходный JSA
blank|Mit leeren Vorlagen beginnen|空の様式から作成|Commencer avec des modèles vides|Iniziare con modelli vuoti|Empezar con modelos vacíos|البدء بنماذج فارغة|Começar com modelos em branco|Начать с пустых форм
addPack|Grundpaket hinzufügen|基本書類セットを追加|Ajouter le dossier de base|Aggiungere il pacchetto di base|Añadir paquete básico|إضافة الحزمة الأساسية|Adicionar pacote básico|Добавить базовый комплект
draft|Entwürfe zur Prüfung vor Ort. Regionale Regeln und Betriebsabläufe prüfen. Aus der JSA werden nur Tätigkeiten, Gefährdungen und Maßnahmen übernommen.|現場確認用の下書きです。地域の規則と現場手順を確認してください。JSAからは作業内容・危険要因・対策のみ取り込みます。|Brouillons à vérifier sur site. Vérifiez les règles locales et les procédures. Seules les activités, les dangers et les mesures sont repris de la JSA.|Bozze da verificare in cantiere. Controllare regole locali e procedure. Dalla JSA si copiano solo attività, pericoli e misure.|Borradores para revisión en el lugar de trabajo. Compruebe normas locales y procedimientos. Solo se copian actividades, peligros y medidas de la JSA.|مسودات للمراجعة في الموقع. تحقق من القواعد المحلية والإجراءات. يُنقل من تحليل العمل وصف الأنشطة والمخاطر وإجراءات التحكم فقط.|Rascunhos para revisão no local. Verifique regras locais e procedimentos. Da JSA, são copiados apenas atividades, perigos e medidas.|Черновики для проверки на месте. Уточните местные правила и процедуры. Из JSA переносятся только работы, опасности и меры защиты.
swms|SWMS ist für Bauarbeiten mit hohem Risiko bestimmt. Anwendbarkeit vor dem Hinzufügen bestätigen.|SWMSは高リスク建設作業用です。該当することを確認してから追加してください。|Le SWMS concerne les travaux de construction à haut risque. Confirmez son applicabilité avant de l’ajouter.|Il SWMS riguarda lavori edili ad alto rischio. Confermarne l’applicabilità prima di aggiungerlo.|El SWMS corresponde a construcción de alto riesgo. Confirme su aplicación antes de añadirlo.|وثيقة SWMS لأعمال الإنشاء عالية الخطورة. أكد انطباقها قبل الإضافة.|O SWMS destina-se à construção de alto risco. Confirme a aplicabilidade antes de adicionar.|SWMS предназначен для строительных работ повышенного риска. Подтвердите применимость перед добавлением.
sources|Referenzquellen|参考資料|Sources de référence|Fonti di riferimento|Fuentes de referencia|المراجع|Fontes de referência|Справочные источники
review|Übernommene Inhalte für diesen Einsatz geprüft|取り込んだ内容を今回の現場に合わせて確認しました|J’ai vérifié le contenu repris pour ce chantier|Ho verificato i contenuti per questo lavoro|He revisado el contenido para este trabajo|راجعت المحتوى المنقول لهذا الموقع|Revisei o conteúdo para este trabalho|Перенесённые сведения проверены для этих работ
reviewNeeded|Regionale Dokumente vor der Ausgabe prüfen.|出力前に国・地域別文書の内容を確認してください。|Vérifiez les documents régionaux avant la sortie.|Verificare i documenti regionali prima dell’uscita.|Revise los documentos regionales antes de generar la salida.|راجع المستندات الإقليمية قبل الإخراج.|Revise os documentos regionais antes da saída.|Проверьте региональные документы перед выводом.
mismatch|Einige Dokumente verwenden andere Länder-, Sprach- oder Arbeitseinstellungen. Passende Vorlagen hinzufügen und alte ausschließen oder entfernen.|国・言語・作業条件が異なる文書があります。適切な様式を追加し、古い文書を除外または削除してください。|Certains documents utilisent d’autres paramètres de pays, langue ou travail. Ajoutez les modèles adaptés et excluez ou retirez les anciens.|Alcuni documenti usano impostazioni diverse. Aggiungere i modelli corretti ed escludere o rimuovere i precedenti.|Hay documentos con otro país, idioma o condiciones. Añada los modelos adecuados y excluya o quite los anteriores.|بعض المستندات لها بلد أو لغة أو ظروف مختلفة. أضف النماذج المناسبة واستبعد القديمة أو أزلها.|Há documentos com outro país, idioma ou condições. Adicione os modelos adequados e exclua ou remova os anteriores.|У части документов другие страна, язык или условия. Добавьте подходящие формы, а прежние исключите или удалите.
retained|Dieses Dokument behält seine ursprüngliche Region, Sprache und Vorlagenversion.|この文書は作成時の国・言語・様式版を維持します。|Ce document conserve sa région, sa langue et sa version d’origine.|Questo documento conserva regione, lingua e versione originali.|Este documento conserva su región, idioma y versión originales.|يحتفظ هذا المستند بالمنطقة واللغة وإصدار النموذج الأصلي.|Este documento mantém a região, o idioma e a versão originais.|Документ сохраняет исходные регион, язык и версию формы.
version|Vorlagenversion|様式バージョン|Version du modèle|Versione del modello|Versión del modelo|إصدار النموذج|Versão do modelo|Версия формы
empty|Arbeitsland und Dokumentensprache wählen, um Vorlagen anzuzeigen.|作業国と文書の言語を選択すると基本様式が表示されます。|Choisissez le pays et la langue pour afficher les modèles.|Scegliere paese e lingua per visualizzare i modelli.|Elija el país y el idioma para ver los modelos.|اختر بلد العمل ولغة المستند لعرض النماذج.|Escolha país e idioma para ver os modelos.|Выберите страну и язык для просмотра форм.
`);
export const regionalFieldTranslations = dictionaries(`
Work scope|Arbeitsumfang|作業範囲・内容|Périmètre des travaux|Ambito dei lavori|Alcance del trabajo|نطاق العمل|Escopo do trabalho|Объём работ
Plant, equipment and tools|Anlagen, Geräte und Werkzeuge|設備・機器・工具|Installations, équipements et outils|Impianti, attrezzature e utensili|Instalaciones, equipos y herramientas|المنشآت والمعدات والأدوات|Instalações, equipamentos e ferramentas|Установки, оборудование и инструмент
Personal protective equipment|Persönliche Schutzausrüstung|個人用保護具|Équipements de protection individuelle|Dispositivi di protezione individuale|Equipos de protección individual|معدات الوقاية الشخصية|Equipamentos de proteção individual|Средства индивидуальной защиты
Site emergency contacts, evacuation and rescue arrangements|Notfallkontakte, Evakuierung und Rettung vor Ort|現場の緊急連絡先・避難・救助計画|Contacts d’urgence, évacuation et secours sur site|Contatti di emergenza, evacuazione e soccorso|Contactos de emergencia, evacuación y rescate|اتصالات الطوارئ والإخلاء والإنقاذ بالموقع|Contatos de emergência, evacuação e resgate|Контакты экстренных служб, эвакуация и спасение
Site checks and changes|Prüfungen und Änderungen vor Ort|現場確認・変更事項|Vérifications et changements sur site|Verifiche e modifiche sul posto|Comprobaciones y cambios en el lugar|التحققات والتغييرات بالموقع|Verificações e alterações no local|Проверки и изменения на месте
Work sequence and control measures|Arbeitsablauf und Schutzmaßnahmen|作業順序・安全対策|Séquence des travaux et mesures de prévention|Sequenza di lavoro e misure di prevenzione|Secuencia de trabajo y medidas preventivas|تسلسل العمل وإجراءات التحكم|Sequência de trabalho e medidas de controle|Последовательность работ и меры защиты
Work step|Arbeitsschritt|作業工程|Étape de travail|Fase di lavoro|Etapa de trabajo|خطوة العمل|Etapa do trabalho|Этап работ
Procedure|Vorgehensweise|作業手順|Mode opératoire|Procedura|Procedimiento|الإجراء|Procedimento|Порядок выполнения
Hazards|Gefährdungen|危険・有害要因|Dangers|Pericoli|Peligros|المخاطر|Perigos|Опасности
Existing controls|Bestehende Schutzmaßnahmen|既存の対策|Mesures existantes|Misure esistenti|Medidas existentes|إجراءات التحكم الحالية|Medidas existentes|Действующие меры защиты
Additional controls|Zusätzliche Schutzmaßnahmen|追加対策|Mesures supplémentaires|Misure aggiuntive|Medidas adicionales|إجراءات إضافية|Medidas adicionais|Дополнительные меры
Person responsible|Verantwortliche Person|今回の作業責任者|Personne responsable|Responsabile|Persona responsable|الشخص المسؤول|Responsável|Ответственное лицо
Hazards and controls — source scores retained without reassessment|Gefährdungen und Maßnahmen – Ausgangswerte ohne Neubewertung|危険要因と対策：元の評価値を再評価せず保持|Dangers et mesures – valeurs sources sans réévaluation|Pericoli e misure – valori originali senza rivalutazione|Peligros y medidas: valores originales sin reevaluar|المخاطر والإجراءات — القيم الأصلية دون إعادة تقييم|Perigos e medidas — valores originais sem reavaliação|Опасности и меры — исходные оценки без переоценки
Activity|Tätigkeit|作業|Activité|Attività|Actividad|النشاط|Atividade|Работа
Hazard|Gefährdung|危険要因|Danger|Pericolo|Peligro|الخطر|Perigo|Опасность
People at risk|Gefährdete Personen|影響を受ける人|Personnes exposées|Persone esposte|Personas expuestas|الأشخاص المعرضون للخطر|Pessoas expostas|Лица, подвергающиеся риску
Further controls|Weitere Maßnahmen|追加の安全対策|Mesures complémentaires|Ulteriori misure|Medidas complementarias|إجراءات تحكم إضافية|Medidas complementares|Дальнейшие меры защиты
Source likelihood / severity / risk|Ursprüngliche Wahrscheinlichkeit / Schwere / Risiko|元の頻度・重篤度・リスク|Probabilité / gravité / risque d’origine|Probabilità / gravità / rischio originali|Probabilidad / gravedad / riesgo originales|الاحتمال / الشدة / الخطر الأصلي|Probabilidade / gravidade / risco originais|Исходные вероятность / тяжесть / риск
Reassessed risk under site criteria|Neubewertung nach örtlichen Kriterien|現場基準による再評価リスク|Risque réévalué selon les critères du site|Rischio rivalutato con criteri del sito|Riesgo reevaluado según criterios del lugar|الخطر المعاد تقييمه وفق معايير الموقع|Risco reavaliado conforme critérios locais|Повторная оценка по критериям объекта
Action owner and due date|Verantwortliche und Frist|対策担当者・期限|Responsable et échéance|Responsabile e scadenza|Responsable y plazo|المسؤول والموعد النهائي|Responsável e prazo|Ответственный и срок
Assessment criteria, matrix and reassessment notes|Bewertungskriterien, Matrix und Neubewertung|評価基準・マトリクス・再評価の説明|Critères, matrice et notes de réévaluation|Criteri, matrice e note di rivalutazione|Criterios, matriz y notas de reevaluación|معايير التقييم والمصفوفة وملاحظات إعادة التقييم|Critérios, matriz e notas de reavaliação|Критерии, матрица и примечания к переоценке
Assessment team / reviewer signatures|Unterschriften: Bewertungsteam / Prüfer|評価参加者・確認者の署名|Signatures de l’équipe d’évaluation / du vérificateur|Firme del gruppo di valutazione / revisore|Firmas del equipo evaluador / revisor|توقيعات فريق التقييم / المراجع|Assinaturas da equipe avaliadora / revisor|Подписи оценщиков / проверяющего
Applicable high risk construction work and site conditions|Zutreffende Hochrisiko-Bauarbeiten und örtliche Bedingungen|該当する高リスク建設作業・現場条件|Travaux de construction à haut risque concernés et conditions du site|Lavori edili ad alto rischio applicabili e condizioni del sito|Obras de alto riesgo aplicables y condiciones del lugar|أعمال الإنشاء عالية الخطورة المنطبقة وظروف الموقع|Obras de alto risco aplicáveis e condições locais|Применимые строительные работы повышенного риска и условия
Roles, training and competency checks|Aufgaben, Unterweisung und Befähigungsprüfung|役割・教育・資格の確認|Rôles, formation et vérification des compétences|Ruoli, formazione e verifica delle competenze|Funciones, formación y comprobación de competencias|الأدوار والتدريب والتحقق من الكفاءة|Funções, treinamento e verificação de competências|Роли, обучение и проверка квалификации
Implementation, monitoring, review and stop-work arrangements|Umsetzung, Überwachung, Prüfung und Arbeitsunterbrechung|対策実施・監視・見直し・作業中止基準|Mise en œuvre, suivi, révision et arrêt des travaux|Attuazione, monitoraggio, revisione e arresto lavori|Aplicación, seguimiento, revisión y parada del trabajo|التنفيذ والمراقبة والمراجعة وإيقاف العمل|Implementação, monitoramento, revisão e interrupção|Выполнение, контроль, пересмотр и остановка работ
Preparations, stop-work and change review arrangements|Vorbereitung, Arbeitsunterbrechung und Änderungsprüfung|事前準備・作業中止・変更時の見直し|Préparatifs, arrêt des travaux et examen des changements|Preparativi, arresto lavori e verifica modifiche|Preparación, parada y revisión de cambios|التحضير وإيقاف العمل ومراجعة التغييرات|Preparação, interrupção e revisão de alterações|Подготовка, остановка и проверка изменений
Worker consultation, briefing and acknowledgement signatures|Beschäftigtenbeteiligung, Unterweisung und Bestätigung|作業者との協議・説明・確認署名|Consultation, briefing et signatures des travailleurs|Consultazione, informazione e firme dei lavoratori|Consulta, charla y firmas de trabajadores|تشاور العاملين والإحاطة وتوقيعات الإقرار|Consulta, orientação e assinaturas dos trabalhadores|Консультации с работниками, обсуждение и подтверждающие подписи
Prepared / reviewed / authorised signatures|Unterschriften: erstellt / geprüft / freigegeben|作成・確認・承認の署名|Signatures : rédaction / vérification / autorisation|Firme: redazione / verifica / autorizzazione|Firmas: elaboración / revisión / autorización|توقيعات الإعداد / المراجعة / الاعتماد|Assinaturas: elaboração / revisão / autorização|Подписи: составил / проверил / разрешил
Permit type, number and work area|Freigabeart, Nummer und Arbeitsbereich|許可の種類・番号・作業区域|Type de permis, numéro et zone de travail|Tipo di permesso, numero e area di lavoro|Tipo de permiso, número y zona|نوع التصريح ورقمه ومنطقة العمل|Tipo de permissão, número e área|Вид допуска, номер и зона работ
Permit valid from / until|Freigabe gültig von / bis|許可有効期間：開始・終了|Permis valable du / au|Permesso valido da / a|Permiso válido desde / hasta|صلاحية التصريح من / إلى|Permissão válida de / até|Допуск действителен с / до
Hazards and precautions|Gefährdungen und Vorsichtsmaßnahmen|危険要因・事前対策|Dangers et précautions|Pericoli e precauzioni|Peligros y precauciones|المخاطر والاحتياطات|Perigos e precauções|Опасности и меры предосторожности
Isolation, lockout / tagout and linked permit checks|Freischaltung, Verriegelung / Kennzeichnung und verknüpfte Freigaben|隔離・施錠・表示・関連許可の確認|Consignation, verrouillage / étiquetage et permis associés|Isolamento, blocco / segnalazione e permessi collegati|Aislamiento, bloqueo / etiquetado y permisos vinculados|العزل والقفل / وضع البطاقات والتحقق من التصاريح المرتبطة|Isolamento, bloqueio / etiquetagem e permissões vinculadas|Изоляция, блокировка / маркировка и связанные допуски
Site measurements where applicable|Messungen vor Ort, soweit erforderlich|必要に応じた現場測定記録|Mesures sur site si applicables|Misurazioni sul posto, se applicabili|Mediciones en el lugar, si procede|قياسات الموقع عند انطباقها|Medições no local, quando aplicáveis|Измерения на месте при необходимости
Test / location|Prüfung / Ort|測定項目・位置|Essai / emplacement|Prova / posizione|Ensayo / ubicación|الاختبار / الموقع|Teste / local|Проверка / место
Reading / unit|Messwert / Einheit|実測値・単位|Valeur / unité|Valore / unità|Valor / unidad|القراءة / الوحدة|Leitura / unidade|Показание / единица
Test time|Messzeitpunkt|測定時刻|Heure de mesure|Ora della misura|Hora de medición|وقت القياس|Horário da medição|Время измерения
Tester|Messende Person|測定者|Personne chargée de la mesure|Addetto alla misura|Persona que mide|القائم بالقياس|Responsável pela medição|Проводивший измерение
Applicant / site check / permit authority signatures|Unterschriften: Antrag / Ortsprüfung / Freigabe|申請・現場確認・許可者の署名|Signatures : demande / contrôle du site / autorité du permis|Firme: richiesta / verifica sito / autorità del permesso|Firmas: solicitante / verificación / autorizante|توقيعات مقدم الطلب / فاحص الموقع / جهة التصريح|Assinaturas: solicitante / verificação / autorizador|Подписи заявителя / проверяющего / выдающего допуск
Completion, handback and permit closure|Abschluss, Rückgabe und Schließung der Freigabe|作業終了・引継ぎ・許可終了の確認|Achèvement, restitution et clôture du permis|Completamento, riconsegna e chiusura del permesso|Finalización, devolución y cierre del permiso|الإنجاز والتسليم وإغلاق التصريح|Conclusão, devolução e encerramento da permissão|Завершение, передача и закрытие допуска
Hazards and controls to discuss|Zu besprechende Gefährdungen und Maßnahmen|共有する危険要因と対策|Dangers et mesures à discuter|Pericoli e misure da discutere|Peligros y medidas que se tratarán|المخاطر وإجراءات التحكم للمناقشة|Perigos e medidas a discutir|Опасности и меры для обсуждения
Changes, recent incidents and worker feedback|Änderungen, jüngste Vorfälle und Rückmeldungen|当日の変更・最近の事例・作業者の意見|Changements, incidents récents et retours des travailleurs|Modifiche, incidenti recenti e osservazioni dei lavoratori|Cambios, incidentes recientes y comentarios|التغييرات والحوادث الأخيرة وملاحظات العاملين|Mudanças, incidentes recentes e comentários|Изменения, недавние происшествия и мнения работников
Agreed actions and persons responsible|Vereinbarte Maßnahmen und Verantwortliche|協議結果・追加措置・担当者|Actions convenues et responsables|Azioni concordate e responsabili|Acciones acordadas y responsables|الإجراءات المتفق عليها والمسؤولون|Ações acordadas e responsáveis|Согласованные действия и ответственные
Attendance and acknowledgement|Teilnahme und Bestätigung|参加者の確認|Présence et confirmation|Presenze e conferma|Asistencia y confirmación|الحضور والإقرار|Presença e confirmação|Присутствие и подтверждение
Name|Name|氏名|Nom|Nome|Nombre|الاسم|Nome|ФИО
Signature|Unterschrift|署名|Signature|Firma|Firma|التوقيع|Assinatura|Подпись
Briefing leader and time|Besprechungsleitung und Zeitpunkt|進行者・実施時刻|Animateur et heure du briefing|Responsabile e ora della riunione|Responsable y hora de la charla|قائد الإحاطة ووقتها|Responsável e horário da reunião|Ведущий обсуждения и время
Inspection items and findings|Prüfpunkte und Ergebnisse|点検項目・結果|Points de contrôle et constats|Punti di controllo ed esiti|Puntos de inspección y resultados|بنود الفحص ونتائجه|Itens de inspeção e resultados|Пункты проверки и результаты
Control / item to check|Zu prüfende Maßnahme / Punkt|確認する対策・項目|Mesure / point à vérifier|Misura / elemento da verificare|Medida / punto a comprobar|الإجراء / البند المطلوب فحصه|Medida / item a verificar|Мера / проверяемый пункт
Finding / measurement|Ergebnis / Messwert|結果・実測値|Constat / mesure|Esito / misura|Resultado / medición|النتيجة / القياس|Resultado / medição|Результат / измерение
Defect / corrective action|Mangel / Korrekturmaßnahme|不備・改善措置|Défaut / action corrective|Difetto / azione correttiva|Defecto / acción correctiva|الخلل / الإجراء التصحيحي|Falha / ação corretiva|Недостаток / корректирующая мера
Owner / due date|Verantwortliche / Frist|担当者・完了期限|Responsable / échéance|Responsabile / scadenza|Responsable / plazo|المسؤول / الموعد|Responsável / prazo|Ответственный / срок
Inspector, time and follow-up verification|Prüfperson, Zeitpunkt und Nachkontrolle|点検者・点検時刻・事後確認|Inspecteur, heure et vérification de suivi|Ispettore, ora e verifica successiva|Inspector, hora y verificación posterior|الفاحص والوقت والتحقق اللاحق|Inspetor, horário e verificação posterior|Проверяющий, время и последующий контроль
Risk Assessment|Gefährdungsbeurteilung|リスクアセスメント|Évaluation des risques|Valutazione dei rischi|Evaluación de riesgos|تقييم المخاطر|Avaliação de riscos|Оценка рисков
Safe Work Procedure|Sichere Arbeitsanweisung|安全作業手順書|Procédure de travail sécuritaire|Procedura di lavoro sicuro|Procedimiento de trabajo seguro|إجراء العمل الآمن|Procedimento de trabalho seguro|Инструкция по безопасному выполнению работ
Permit to Work|Arbeitserlaubnis|作業許可書|Permis de travail|Permesso di lavoro|Permiso de trabajo|تصريح العمل الآمن|Permissão de trabalho|Разрешение на работы
Toolbox Talk|Sicherheitskurzbesprechung|作業前安全ミーティング|Causerie sécurité|Riunione di sicurezza|Charla de seguridad|اجتماع السلامة قبل العمل|Diálogo de segurança|Обсуждение безопасности перед работой
Inspection Checklist|Sicherheitscheckliste|安全点検表|Liste de contrôle de sécurité|Lista di controllo della sicurezza|Lista de comprobación de seguridad|قائمة فحص السلامة|Lista de verificação de segurança|Контрольный лист безопасности
Draft for site review|Entwurf zur Prüfung vor Ort|現場確認用の下書き|Brouillon à vérifier sur site|Bozza da verificare sul posto|Borrador para revisión en el lugar|مسودة للمراجعة بالموقع|Rascunho para revisão no local|Черновик для проверки на месте
Template version|Vorlagenversion|様式バージョン|Version du modèle|Versione del modello|Versión del modelo|إصدار النموذج|Versão do modelo|Версия формы
Source JSA|Quell-JSA|参照JSA|JSA source|JSA di origine|JSA de origen|تحليل العمل المصدر|JSA de origem|Исходный JSA
Work unit and related prevention documents|Arbeitseinheit und zugehörige Präventionsdokumente|作業単位・関連する予防管理文書|Unité de travail et documents de prévention associés|Unità di lavoro e documenti di prevenzione collegati|Unidad de trabajo y documentos preventivos relacionados|وحدة العمل ووثائق الوقاية المرتبطة|Unidade de trabalho e documentos de prevenção relacionados|Рабочая единица и связанные документы профилактики
Worker consultation and reassessment triggers|Beschäftigtenbeteiligung und Anlässe zur Neubewertung|作業者との協議・再評価の条件|Consultation des travailleurs et critères de réévaluation|Consultazione dei lavoratori e condizioni di rivalutazione|Consulta a trabajadores y criterios de reevaluación|تشاور العاملين وموجبات إعادة التقييم|Consulta aos trabalhadores e critérios de reavaliação|Консультации работников и основания переоценки
Local procedures, interfaces and responsible roles|Örtliche Verfahren, Schnittstellen und Verantwortlichkeiten|現場手順・他作業との調整・責任分担|Procédures locales, interfaces et responsabilités|Procedure locali, interferenze e responsabilità|Procedimientos locales, interferencias y responsabilidades|الإجراءات المحلية والتداخلات والأدوار المسؤولة|Procedimentos locais, interferências e responsabilidades|Местные процедуры, взаимодействия и ответственные роли
Prevention plan reference and follow-up|Präventionsplan-Verweis und Nachverfolgung|予防計画の参照・フォローアップ|Référence au plan de prévention et suivi|Riferimento al piano di prevenzione e monitoraggio|Referencia al plan preventivo y seguimiento|مرجع خطة الوقاية والمتابعة|Referência ao plano de prevenção e acompanhamento|Ссылка на план профилактики и последующий контроль
Worksite conditions and lone work arrangements|Örtliche Bedingungen und Alleinarbeit|現場条件・単独作業への対応|Conditions du site et travail isolé|Condizioni del sito e lavoro isolato|Condiciones del lugar y trabajo en solitario|ظروف الموقع وترتيبات العمل المنفرد|Condições locais e trabalho isolado|Условия объекта и работа в одиночку
Effectiveness checks and review date|Wirksamkeitskontrolle und Prüftermin|対策の有効性確認・見直し日|Vérification de l’efficacité et date de révision|Verifica dell’efficacia e data di revisione|Comprobación de eficacia y fecha de revisión|التحقق من الفعالية وتاريخ المراجعة|Verificação da eficácia e data de revisão|Проверка эффективности и дата пересмотра
Priority hazards and team action commitments|Vorrangige Gefährdungen und Teamvereinbarungen|重点危険要因・チームの行動目標|Dangers prioritaires et engagements de l’équipe|Pericoli prioritari e impegni della squadra|Peligros prioritarios y compromisos del equipo|المخاطر ذات الأولوية والتزامات الفريق|Perigos prioritários e compromissos da equipe|Приоритетные опасности и действия бригады
Related organisation-wide record (not replaced by this task form)|Zugehöriger betrieblicher Nachweis (nicht durch dieses Aufgabenblatt ersetzt)|関連する事業場全体の管理文書（本作業票は代替しません）|Document global de l’établissement associé (non remplacé par cette fiche)|Documento aziendale collegato (non sostituito da questa scheda)|Documento general de la empresa (esta ficha no lo sustituye)|سجل المنشأة العام المرتبط (لا يستبدله نموذج المهمة)|Registro geral da organização (esta ficha não o substitui)|Связанный документ организации (эта форма его не заменяет)
`);
const reviewFieldTranslations = dictionaries(`
Assessment / revision date|Datum der Beurteilung / Überarbeitung|評価・改訂日|Date d’évaluation / de révision|Data di valutazione / revisione|Fecha de evaluación / revisión|تاريخ التقييم / التعديل|Data da avaliação / revisão|Дата оценки / пересмотра
Next review date and early review triggers|Nächster Prüftermin und Anlässe zur vorzeitigen Überprüfung|次回見直し日・臨時見直しの条件|Prochaine révision et motifs de révision anticipée|Prossima revisione e condizioni per una revisione anticipata|Próxima revisión y motivos de revisión anticipada|تاريخ المراجعة التالية وأسباب المراجعة المبكرة|Próxima revisão e motivos para revisão antecipada|Следующая дата пересмотра и основания досрочного пересмотра
Worker consultation and communication of remaining risks|Beschäftigtenbeteiligung und Information über verbleibende Risiken|労働者の参加・残留リスクの周知記録|Consultation des travailleurs et communication des risques résiduels|Consultazione dei lavoratori e comunicazione dei rischi residui|Consulta a trabajadores y comunicación de riesgos residuales|التشاور مع العاملين وإبلاغهم بالمخاطر المتبقية|Consulta aos trabalhadores e comunicação dos riscos residuais|Участие работников и информирование об остаточных рисках
Control hierarchy, implementation and effectiveness|Maßnahmenhierarchie, Umsetzung und Wirksamkeitsprüfung|対策の優先順位・実施状況・有効性確認|Hiérarchie des mesures, mise en œuvre et efficacité|Gerarchia delle misure, attuazione ed efficacia|Jerarquía de medidas, aplicación y eficacia|تسلسل تدابير التحكم وتنفيذها والتحقق من فعاليتها|Hierarquia das medidas, implementação e eficácia|Приоритет мер, выполнение и проверка эффективности
People at risk and possible harm|Gefährdete Personen und mögliche Gesundheitsschäden|影響を受ける人・想定される負傷や健康障害|Personnes exposées et dommages possibles|Persone esposte e possibili danni|Personas expuestas y posibles daños|الأشخاص المعرضون للخطر والأضرار المحتملة|Pessoas expostas e possíveis danos|Лица, подверженные риску, и возможный вред
Assessment type and risk acceptance criteria|Art der Beurteilung und Kriterien der Risikoakzeptanz|評価の種類・リスクの許容基準|Type d’évaluation et critères d’acceptabilité du risque|Tipo di valutazione e criteri di accettabilità del rischio|Tipo de evaluación y criterios de aceptabilidad del riesgo|نوع التقييم ومعايير قبول المخاطر|Tipo de avaliação e critérios de aceitabilidade do risco|Вид оценки и критерии допустимости риска
Assessment team leader and approving manager|Leitung des Beurteilungsteams und freigebende Führungskraft|評価チーム責任者・承認管理者|Responsable de l’équipe d’évaluation et responsable approbateur|Responsabile del gruppo di valutazione e dirigente approvatore|Responsable del equipo de evaluación y responsable que aprueba|قائد فريق التقييم والمدير المعتمد|Líder da equipe de avaliação e gestor responsável pela aprovação|Руководитель группы оценки и утверждающий руководитель
Contracting parties and coordination record|Beteiligte Auftraggeber / Auftragnehmer und Koordinationsnachweis|発注者・請負業者・作業間の調整記録|Entreprises intervenantes et compte rendu de coordination|Imprese coinvolte e verbale di coordinamento|Empresas participantes y registro de coordinación|الجهات المتعاقدة وسجل التنسيق|Empresas envolvidas e registro de coordenação|Участвующие организации и запись о координации
Related prevention programme or action plan|Zugehöriges Präventionsprogramm oder Maßnahmenplan|関連する予防プログラム・行動計画|Programme de prévention ou plan d’action associé|Programma di prevenzione o piano d’azione collegato|Programa de prevención o plan de acción relacionado|برنامج الوقاية أو خطة العمل ذات الصلة|Programa de prevenção ou plano de ação relacionado|Связанная программа профилактики или план мероприятий
Reference to the applicable permit form and procedure|Verweis auf das geltende Erlaubnisformular und Verfahren|適用する許可書様式・許可手順の参照|Référence du formulaire et de la procédure d’autorisation applicables|Riferimento al modulo e alla procedura di autorizzazione applicabili|Referencia al formulario y procedimiento de autorización aplicables|مرجع نموذج التصريح وإجراءاته المعمول بها|Referência ao formulário e procedimento de permissão aplicáveis|Ссылка на применимую форму допуска и порядок оформления
Permit applicant / work supervisor|Antragsteller / Arbeitsverantwortlicher|許可申請者・作業責任者|Demandeur / responsable des travaux|Richiedente / responsabile dei lavori|Solicitante / responsable de los trabajos|مقدم طلب التصريح / مشرف العمل|Solicitante / responsável pelo trabalho|Заявитель / руководитель работ
Site precautions verified by|Prüfer der Schutzmaßnahmen vor Ort|現場の安全措置確認者|Vérificateur des mesures de sécurité sur site|Verificatore delle misure di sicurezza sul posto|Responsable de verificar las precauciones en el lugar|المسؤول عن التحقق من احتياطات الموقع|Responsável pela verificação das medidas no local|Проверивший меры безопасности на месте
Permit issuer|Erlaubniserteiler|許可発行者|Responsable de la délivrance de l’autorisation|Responsabile del rilascio del permesso|Responsable de emitir la autorización|مصدر التصريح|Responsável pela emissão da permissão|Выдающий разрешение
Work team acceptance|Bestätigung durch die ausführende Arbeitsgruppe|作業班の受領・確認|Acceptation par l’équipe exécutante|Accettazione da parte della squadra esecutrice|Aceptación por el equipo ejecutante|استلام فريق العمل وإقراره|Aceite da equipe executante|Принятие условий исполнителями
Suspension, revalidation and shift handover|Unterbrechung, erneute Freigabe und Schichtübergabe|中断・再許可・交替時の引継ぎ|Suspension, revalidation et relève d’équipe|Sospensione, riconvalida e passaggio di turno|Suspensión, revalidación y relevo de turno|التعليق وإعادة الاعتماد وتسليم الوردية|Suspensão, revalidação e passagem de turno|Приостановка, повторное разрешение и передача смены
Safe completion and return to service|Sicherer Abschluss und Wiederinbetriebnahme|安全な作業終了・設備の復旧|Fin des travaux en sécurité et remise en service|Conclusione in sicurezza e rimessa in servizio|Finalización segura y puesta en servicio|إنهاء العمل بأمان وإعادة التشغيل|Conclusão segura e retorno à operação|Безопасное завершение и ввод в работу
SG review: within 3 years, or earlier after changes or incidents|SG: Überprüfung innerhalb von 3 Jahren, früher bei Änderungen oder Vorfällen|SG：3年以内に見直し。変更・事故時は前倒し|SG : révision sous 3 ans, plus tôt après changement ou incident|SG: revisione entro 3 anni, prima in caso di modifiche o incidenti|SG: revisión dentro de 3 años, antes si hay cambios o incidentes|سنغافورة: المراجعة خلال 3 سنوات أو قبل ذلك عند التغييرات أو الحوادث|SG: revisão em até 3 anos, antes se houver mudanças ou incidentes|Сингапур: пересмотр в течение 3 лет, раньше при изменениях или происшествиях
Applicable procedures, training and work authorisations|Anwendbare Verfahren, Schulungen und Arbeitsberechtigungen|適用手順・教育・作業資格の確認|Procédures, formations et habilitations applicables|Procedure, formazione e autorizzazioni applicabili|Procedimientos, formación y autorizaciones aplicables|الإجراءات والتدريب وتصاريح العمل المعمول بها|Procedimentos, capacitação e autorizações aplicáveis|Применимые процедуры, обучение и допуски к работам
Records custodian and retention arrangements|Verantwortlicher für Nachweise und Aufbewahrung|記録管理者・保存方法|Responsable des archives et modalités de conservation|Responsabile degli archivi e modalità di conservazione|Responsable de registros y condiciones de conservación|مسؤول السجلات وترتيبات الاحتفاظ بها|Responsável pelos registros e condições de guarda|Ответственный за записи и порядок хранения
Action priority and remaining risks to communicate|Maßnahmenpriorität und mitzuteilende Restrisiken|対策の優先度・周知すべき残留リスク|Priorité des actions et risques résiduels à communiquer|Priorità degli interventi e rischi residui da comunicare|Prioridad de actuaciones y riesgos residuales que comunicar|أولوية الإجراءات والمخاطر المتبقية الواجب إبلاغها|Prioridade das ações e riscos residuais a comunicar|Приоритет действий и остаточные риски для информирования
Work unit, exposure and affected groups|Arbeitsbereich, Exposition und betroffene Gruppen|作業単位・ばく露・影響を受ける集団|Unité de travail, exposition et groupes concernés|Unità di lavoro, esposizione e gruppi interessati|Unidad de trabajo, exposición y grupos afectados|وحدة العمل والتعرض والمجموعات المتأثرة|Unidade de trabalho, exposição e grupos afetados|Рабочая единица, воздействие и затронутые группы
`);
for (const language of languages) Object.assign(regionalFieldTranslations[language], reviewFieldTranslations[language]);
export function regionalText(locale, english, korean = english) {
  if (locale?.startsWith('ko')) return korean;
  return regionalFieldTranslations[locale?.split('-')[0]]?.[english] || english;
}
