import { phase6Language } from './phase6Ui.js';
const keys = 'title|provider|scope|site|discovery|impressions|range|success|error|unconfigured|lastSuccess|attempt|manual|source|legacy|empty|help|naverHelp'.split('|');
const rows = {
 ko: '검색 서비스 연동|검색 서비스|집계 범위|사이트 전체|Explore·공개 JSA|노출 수|데이터 기간|수집 성공|연결·수집 오류|수집 기록 없음 · 연결 설정 확인|마지막 성공|마지막 시도|네이버 월별 입력|보고서 출처·집계 조건|기존 수동 입력 기록|아직 수집된 통계가 없습니다.|Google은 웹 검색·태평양 시간 기준, Bing은 여러 검색 영역의 사이트 전체 통계입니다. 라이브러리와 사이트 전체를 합산하지 않습니다. 표시 수치는 API가 반환한 날짜의 합계이며 이번 달·일부 기간은 월 전체 합계가 아닙니다. 누락은 0을 뜻하지 않습니다. 매일 수집하되 최신 며칠은 지연될 수 있습니다.|네이버 검색 성과의 일반 공개 API는 확인되지 않았습니다. 서치어드바이저에서 지난달 사이트 전체 클릭·노출을 확인해 입력하세요. 노출 수는 모르면 비워두세요.',
 en: 'Search integrations|Search service|Scope|Whole site|Explore · Public JSA|Impressions|Data period|Sync succeeded|Connection or sync error|No sync record · Check setup|Last success|Last attempt|Naver monthly entry|Report source and filters|Previous manual records|No collected metrics yet.|Google uses web search and Pacific dates; Bing includes multiple search verticals site-wide. Do not add library and site totals. Figures sum dates returned by the API; current or partial months are not full-month totals. Missing is not zero. Daily sync; recent days may be delayed.|No general public API for Naver search performance was confirmed. Enter a completed month’s site-wide clicks and impressions from Search Advisor. Leave unknown impressions blank.',
 ja: '検索サービス連携|検索サービス|集計範囲|サイト全体|Explore・公開JSA|表示回数|データ期間|取得成功|接続・取得エラー|取得履歴なし・設定を確認|最終成功|最終試行|Naver月次入力|レポートの出典・条件|以前の手動入力|取得データはまだありません。|Googleはウェブ検索・太平洋時間、Bingは複数検索領域のサイト全体です。ライブラリと全体を合算しないでください。APIが返した日付の合計で、当月や一部期間は月全体ではありません。欠落はゼロではありません。毎日取得し、直近は遅延する場合があります。|Naver検索実績の一般公開APIは確認できません。完了月のサイト全体のクリック・表示回数をSearch Advisorから入力してください。不明の表示回数は空欄にします。',
 de: 'Suchdienst-Verbindungen|Suchdienst|Umfang|Gesamte Website|Explore · Öffentliche JSA|Impressionen|Datenzeitraum|Abruf erfolgreich|Verbindungs- oder Abruffehler|Kein Abruf · Einrichtung prüfen|Letzter Erfolg|Letzter Versuch|Naver-Monatswerte|Berichtsquelle und Filter|Frühere manuelle Werte|Noch keine abgerufenen Daten.|Google: Websuche und pazifische Zeit. Bing: mehrere Suchbereiche der gesamten Website. Bibliothek und Website nicht addieren. Summiert werden nur gelieferte Tage; laufende oder teilweise Monate sind keine vollständigen Monatswerte. Fehlend bedeutet nicht null. Täglicher Abruf mit möglicher Verzögerung.|Keine allgemeine öffentliche API für Naver-Suchleistung bestätigt. Klicks und Impressionen eines abgeschlossenen Monats aus Search Advisor eingeben. Unbekannte Impressionen leer lassen.',
 fr: 'Connexions aux moteurs|Moteur|Périmètre|Site entier|Explore · JSA publiques|Impressions|Période des données|Collecte réussie|Erreur de connexion ou de collecte|Aucune collecte · Vérifier la configuration|Dernier succès|Dernière tentative|Saisie mensuelle Naver|Source et filtres du rapport|Anciennes saisies manuelles|Aucune donnée collectée.|Google : recherche Web et dates du Pacifique. Bing : plusieurs catégories sur tout le site. Ne pas additionner bibliothèque et site. Somme des jours renvoyés ; mois courant ou partiel différent du mois complet. Absence ne signifie pas zéro. Collecte quotidienne avec délai possible.|Aucune API publique générale de performance Naver confirmée. Saisir les clics et impressions du site pour un mois terminé depuis Search Advisor. Laisser les impressions inconnues vides.',
 es: 'Conexiones de búsqueda|Buscador|Ámbito|Todo el sitio|Explore · JSA públicas|Impresiones|Periodo de datos|Recopilación correcta|Error de conexión o recopilación|Sin registros · Revisar configuración|Último éxito|Último intento|Entrada mensual de Naver|Fuente y filtros del informe|Registros manuales anteriores|Aún no hay métricas recopiladas.|Google: búsqueda web y fechas del Pacífico. Bing: varias categorías de todo el sitio. No sumar biblioteca y sitio. Son sumas de días devueltos; meses actuales o parciales no representan el mes completo. Ausencia no es cero. Recopilación diaria con posible retraso.|No se confirmó una API pública general de rendimiento de Naver. Introduzca clics e impresiones de todo el sitio de un mes finalizado desde Search Advisor. Deje vacías las impresiones desconocidas.',
 it: 'Collegamenti ai motori|Motore|Ambito|Intero sito|Explore · JSA pubbliche|Impressioni|Periodo dei dati|Raccolta riuscita|Errore di connessione o raccolta|Nessuna raccolta · Controlla configurazione|Ultimo successo|Ultimo tentativo|Inserimento mensile Naver|Fonte e filtri del rapporto|Precedenti dati manuali|Nessuna metrica raccolta.|Google: ricerca web e date del Pacifico. Bing: più categorie sull’intero sito. Non sommare biblioteca e sito. Somme dei giorni restituiti; mesi correnti o parziali non sono mesi completi. Assenza non è zero. Raccolta giornaliera con possibili ritardi.|Non è stata confermata un’API pubblica generale per le prestazioni Naver. Inserisci clic e impressioni del sito per un mese concluso da Search Advisor. Lascia vuote le impressioni sconosciute.',
 pt: 'Integrações de pesquisa|Mecanismo|Escopo|Site inteiro|Explore · JSA públicas|Impressões|Período dos dados|Coleta concluída|Erro de conexão ou coleta|Sem registros · Verifique a configuração|Último sucesso|Última tentativa|Entrada mensal Naver|Fonte e filtros do relatório|Registros manuais anteriores|Ainda não há métricas coletadas.|Google: pesquisa web e datas do Pacífico. Bing: várias categorias do site inteiro. Não some biblioteca e site. Somam-se os dias retornados; meses atuais ou parciais não são meses completos. Ausência não é zero. Coleta diária com possível atraso.|Não foi confirmada API pública geral de desempenho Naver. Insira cliques e impressões do site de um mês concluído do Search Advisor. Deixe impressões desconhecidas em branco.',
 ru: 'Подключение поисковых систем|Поисковая система|Охват|Весь сайт|Explore · Публичные JSA|Показы|Период данных|Сбор выполнен|Ошибка подключения или сбора|Нет записей · Проверьте настройки|Последний успех|Последняя попытка|Месячные данные Naver|Источник и фильтры отчёта|Прежние ручные записи|Собранных данных пока нет.|Google: веб-поиск и тихоокеанское время. Bing: несколько категорий всего сайта. Не складывайте библиотеку и сайт. Суммируются полученные дни; текущий или неполный месяц не равен полному. Отсутствие не означает ноль. Ежедневный сбор с возможной задержкой.|Общедоступный API статистики Naver не подтверждён. Введите клики и показы сайта за завершённый месяц из Search Advisor. Неизвестные показы оставьте пустыми.',
 ar: 'ربط خدمات البحث|خدمة البحث|النطاق|الموقع بالكامل|Explore · تحليلات JSA العامة|مرات الظهور|فترة البيانات|نجح الجمع|خطأ في الاتصال أو الجمع|لا توجد سجلات · تحقق من الإعداد|آخر نجاح|آخر محاولة|إدخال Naver الشهري|مصدر التقرير والفلاتر|السجلات اليدوية السابقة|لا توجد إحصاءات مجمعة بعد.|Google: بحث الويب وتوقيت المحيط الهادئ. Bing: عدة مجالات بحث للموقع بالكامل. لا تجمع المكتبة مع الموقع. الأرقام مجموع الأيام التي أعادتها الواجهة؛ الشهر الحالي أو الجزئي ليس شهراً كاملاً. الغياب ليس صفراً. جمع يومي مع تأخير محتمل.|لم يتم تأكيد واجهة عامة لإحصاءات بحث Naver. أدخل نقرات وظهور الموقع لشهر مكتمل من Search Advisor. اترك مرات الظهور المجهولة فارغة.'
};
export function getSearchConsoleUi(locale) {
 const values = (rows[phase6Language(locale)] || rows.en).split('|');
 return Object.fromEntries(keys.map((key, index) => [key, values[index]]));
}
