// ko | en | de | ja | fr | it | es | ar | pt | ru
export const SINGAPORE_FORM_ROWS = `
sgAssessmentRegister|평가 참조번호·최초 평가일·이번 검토일·다음 검토일|RA reference, original assessment date, current and next review dates|RA-Referenz, Erstbewertung, aktuelles und nächstes Prüfdatum|RA参照番号・初回評価日・今回と次回の見直し日|Référence RA, date initiale et dates de révision actuelle et suivante|Riferimento RA, data iniziale e date della revisione attuale e successiva|Referencia RA, fecha inicial y fechas de revisión actual y próxima|مرجع RA وتاريخ التقييم الأول وتاريخا المراجعة الحالية والتالية|Referência RA, data inicial e datas da revisão atual e seguinte|Номер RA, дата первоначальной оценки, текущего и следующего пересмотра
sgRiskEvaluation|이번 작업의 위험도 평가 — 적용 행렬에 따른 중대성·가능성·위험도 기록|Current-work risk evaluation — severity, likelihood and risk under the chosen matrix|Risikobewertung der aktuellen Arbeit — Schwere, Wahrscheinlichkeit und Risiko nach gewählter Matrix|今回の作業のリスク評価 — 選択した行列による重篤度・可能性・リスク|Évaluation du travail actuel — gravité, probabilité et risque selon la matrice choisie|Valutazione del lavoro attuale — gravità, probabilità e rischio secondo la matrice scelta|Evaluación del trabajo actual — gravedad, probabilidad y riesgo según la matriz elegida|تقييم مخاطر العمل الحالي — الشدة والاحتمال والمخاطر وفق المصفوفة المختارة|Avaliação do trabalho atual — gravidade, probabilidade e risco segundo a matriz escolhida|Оценка текущей работы — тяжесть, вероятность и риск по выбранной матрице
sgInitialRisk|추가 대책 전: 이번 현장의 중대성 / 가능성 / 위험도|Before further controls: current-site severity / likelihood / risk|Vor weiteren Maßnahmen: aktuelle Schwere / Wahrscheinlichkeit / Risiko|追加対策前：今回の現場の重篤度 / 可能性 / リスク|Avant mesures supplémentaires : gravité / probabilité / risque du site actuel|Prima di ulteriori misure: gravità / probabilità / rischio del sito attuale|Antes de medidas adicionales: gravedad / probabilidad / riesgo del lugar actual|قبل الضوابط الإضافية: شدة / احتمال / مخاطر الموقع الحالي|Antes de medidas adicionais: gravidade / probabilidade / risco do local atual|До дополнительных мер: текущая тяжесть / вероятность / риск на объекте
sgResidualRisk|추가 대책 반영 후: 중대성 / 가능성 / 잔여 위험도|After further controls: severity / likelihood / residual risk|Nach weiteren Maßnahmen: Schwere / Wahrscheinlichkeit / Restrisiko|追加対策反映後：重篤度 / 可能性 / 残留リスク|Après mesures supplémentaires : gravité / probabilité / risque résiduel|Dopo ulteriori misure: gravità / probabilità / rischio residuo|Tras medidas adicionales: gravedad / probabilidad / riesgo residual|بعد الضوابط الإضافية: الشدة / الاحتمال / المخاطر المتبقية|Após medidas adicionais: gravidade / probabilidade / risco residual|После дополнительных мер: тяжесть / вероятность / остаточный риск
sgApprovalRecord|해당 구역·업무 책임자의 승인: 성명·직책·승인일·서명|Area/function manager approval: name, designation, approval date and signature|Freigabe durch Bereichs-/Funktionsleitung: Name, Funktion, Datum und Unterschrift|区域・業務責任者の承認：氏名・役職・承認日・署名|Approbation du responsable de zone/fonction : nom, fonction, date et signature|Approvazione del responsabile di area/funzione: nome, ruolo, data e firma|Aprobación del responsable de área/función: nombre, cargo, fecha y firma|اعتماد مدير المنطقة أو الوظيفة: الاسم والمسمى الوظيفي وتاريخ الاعتماد والتوقيع|Aprovação do responsável pela área/função: nome, cargo, data e assinatura|Утверждение руководителем участка/функции: имя, должность, дата и подпись
sgProcedureReview|관련 RA 참조·SWP 개정, 실행 확인자·확인일·다음 검토일|Linked RA, SWP revision, implementation verifier, check date and next review|Zugehörige RA, SWP-Revision, Umsetzungsprüfer, Prüfdatum und nächste Überprüfung|関連RA・SWP改訂、実施確認者・確認日・次回見直し日|RA liée, révision SWP, personne vérifiant l’application, date du contrôle et prochaine révision|RA collegata, revisione SWP, verificatore dell’attuazione, data del controllo e prossima revisione|RA vinculada, revisión SWP, verificador de aplicación, fecha de control y próxima revisión|RA المرتبط ومراجعة SWP ومسؤول التحقق من التنفيذ وتاريخ الفحص والمراجعة التالية|RA vinculada, revisão SWP, responsável pela verificação da execução, data da verificação e próxima revisão|Связанная RA, редакция SWP, проверяющий выполнение, дата проверки и следующий пересмотр
sgBriefingReadiness|오늘 작업 준비·적합한 보호구·중지/보고 방법·정리정돈 확인|Today's work readiness, suitable PPE, stop/report arrangements and housekeeping|Heutige Arbeitsbereitschaft, geeignete PSA, Stopp-/Meldeverfahren und Ordnung|当日の作業準備・適切な保護具・中止/報告方法・整理整頓の確認|Préparation du travail du jour, EPI adaptés, arrêt/signalement et rangement|Preparazione al lavoro odierno, DPI adeguati, arresto/segnalazione e ordine|Preparación para el trabajo de hoy, EPI adecuados, parada/aviso y orden|جاهزية عمل اليوم ومعدات الوقاية المناسبة وإجراءات التوقف والإبلاغ والترتيب|Preparação para o trabalho de hoje, EPI adequados, parada/comunicação e organização|Готовность к сегодняшней работе, подходящие СИЗ, порядок остановки/сообщения и уборка
sgBriefingUnderstanding|사용 언어·통역, SWP 설명·시연, 작업자 질문·이해 확인|Languages and interpretation, SWP explanation/demonstration, worker questions and understanding|Sprachen und Dolmetschen, SWP-Erklärung/Vorführung, Fragen und Verständnis der Beschäftigten|使用言語・通訳、SWPの説明・実演、作業者の質問・理解確認|Langues et interprétation, explication/démonstration SWP, questions et compréhension des travailleurs|Lingue e interpretariato, spiegazione/dimostrazione SWP, domande e comprensione dei lavoratori|Idiomas e interpretación, explicación/demostración SWP, preguntas y comprensión de los trabajadores|اللغات والترجمة الشفوية وشرح SWP وعرضه وأسئلة العمال والتحقق من فهمهم|Idiomas e interpretação, explicação/demonstração SWP, perguntas e compreensão dos trabalhadores|Языки и устный перевод, объяснение/демонстрация SWP, вопросы работников и проверка понимания
`;
