const keys = ['author','publications','follow','unfollow','followers','following','nickname','bio','profileHelp','save','all','empty','login','previous','next','error','saved','evidence','receipt','duplicate','pending','awaiting_changes','request_changes','priority','overdue','snapshot','history','refresh','conflict','privacyHelp','feed','authors','reviewHelp'];
const rows = {
 ko: ['작성자','공개 자료','팔로우','팔로우 취소','팔로워','팔로잉','공개 닉네임','소개','닉네임과 소개는 누구나 볼 수 있습니다. 실명·이메일·회사 기밀을 입력하지 마세요.','저장','전체','표시할 자료가 없습니다.','로그인 후 이용해주세요.','이전','다음','처리하지 못했습니다. 다시 시도해주세요.','저장했습니다.','문제가 있는 단계·문구 (선택)','접수번호','이미 접수된 신고입니다. 기존 처리 상태를 확인해주세요.','미처리','작성자 수정 대기','수정 요청','우선 검토','3일 이상 경과','신고 당시 문서','처리 이력','새로고침','내용이나 처리 상태가 변경됐습니다. 새로고침 후 다시 확인해주세요.','신고 내용은 운영자만 검토합니다. 처리 사유는 관련 이용자에게 안내됩니다.','팔로잉 새 자료','팔로잉 작성자','우선순위는 검토 순서입니다. 신고만으로 자동 숨김 또는 안전 검증을 하지 않습니다.'],
 en: ['Author','Public documents','Follow','Unfollow','Followers','Following','Public nickname','About','Your nickname and bio are public. Do not include real names, email addresses or confidential information.','Save','All','No documents to show.','Please sign in to continue.','Previous','Next','Unable to complete. Please retry.','Saved.','Affected step or passage (optional)','Reference number','Already reported. Check your existing request.','Pending','Awaiting author changes','Request changes','Priority review','Over 3 days old','Document at submission','Decision history','Refresh','The document or request has changed. Refresh and review again.','Reports are reviewed privately by operators. Decision reasons are shared with affected users.','Following feed','Followed authors','Priority determines review order. Reports do not automatically hide or certify a document.'],
 ja: ['作成者','公開資料','フォロー','フォロー解除','フォロワー','フォロー中','公開ニックネーム','紹介','ニックネームと紹介は公開されます。実名・メール・機密情報を含めないでください。','保存','すべて','表示する資料がありません。','ログインしてください。','前へ','次へ','処理できませんでした。再試行してください。','保存しました。','問題のある手順・文章（任意）','受付番号','受付済みです。既存の申請をご確認ください。','未処理','作成者の修正待ち','修正を依頼','優先確認','3日以上経過','通報時の文書','対応履歴','更新','文書または状態が変更されました。更新して再確認してください。','通報は運営者のみが確認します。判断理由は関係者に通知されます。','フォロー中の新着','フォロー中の作成者','優先度は確認順です。通報だけで自動非公開や安全認証は行いません。'],
 de: ['Autor','Öffentliche Dokumente','Folgen','Nicht mehr folgen','Follower','Gefolgt','Öffentlicher Spitzname','Über mich','Name und Beschreibung sind öffentlich. Keine echten Namen, E-Mail-Adressen oder vertraulichen Angaben.','Speichern','Alle','Keine Dokumente vorhanden.','Bitte anmelden.','Zurück','Weiter','Fehlgeschlagen. Bitte erneut versuchen.','Gespeichert.','Betroffener Schritt oder Text (optional)','Vorgangsnummer','Bereits gemeldet. Prüfen Sie Ihre bestehende Anfrage.','Offen','Warten auf Änderungen','Änderungen anfordern','Priorisierte Prüfung','Über 3 Tage alt','Dokument bei Meldung','Entscheidungsverlauf','Aktualisieren','Dokument oder Anfrage wurde geändert. Aktualisieren und erneut prüfen.','Meldungen werden vertraulich geprüft. Entscheidungsgründe werden Betroffenen mitgeteilt.','Neuigkeiten abonnierter Autoren','Abonnierte Autoren','Priorität bestimmt die Prüfreihenfolge. Meldungen sperren oder zertifizieren Dokumente nicht automatisch.'],
 fr: ['Auteur','Documents publics','Suivre','Ne plus suivre','Abonnés','Abonnements','Pseudonyme public','Présentation','Le pseudonyme et la présentation sont publics. Aucun nom réel, e-mail ou renseignement confidentiel.','Enregistrer','Tous','Aucun document à afficher.','Veuillez vous connecter.','Précédent','Suivant','Échec. Veuillez réessayer.','Enregistré.','Étape ou passage concerné (facultatif)','Numéro de suivi','Déjà signalé. Consultez votre demande existante.','En attente','En attente de corrections','Demander des corrections','Examen prioritaire','Plus de 3 jours','Document au signalement','Historique des décisions','Actualiser','Le document ou la demande a changé. Actualisez et vérifiez à nouveau.','Les signalements sont examinés en privé. Les motifs sont communiqués aux personnes concernées.','Nouveautés des abonnements','Auteurs suivis','La priorité détermine l’ordre de traitement. Un signalement ne masque ni ne certifie automatiquement un document.'],
 es: ['Autor','Documentos públicos','Seguir','Dejar de seguir','Seguidores','Siguiendo','Alias público','Presentación','El alias y la presentación son públicos. No incluya nombres reales, correos ni información confidencial.','Guardar','Todos','No hay documentos.','Inicie sesión para continuar.','Anterior','Siguiente','No se pudo completar. Reintente.','Guardado.','Paso o fragmento afectado (opcional)','Número de referencia','Ya se ha denunciado. Revise su solicitud existente.','Pendiente','Esperando cambios del autor','Solicitar cambios','Revisión prioritaria','Más de 3 días','Documento al denunciar','Historial de decisiones','Actualizar','El documento o la solicitud ha cambiado. Actualice y revise de nuevo.','Los avisos se revisan de forma privada. Los motivos se comunican a los usuarios afectados.','Novedades de autores seguidos','Autores seguidos','La prioridad determina el orden de revisión. Las denuncias no ocultan ni certifican automáticamente documentos.'],
 it: ['Autore','Documenti pubblici','Segui','Non seguire più','Follower','Seguiti','Pseudonimo pubblico','Presentazione','Pseudonimo e presentazione sono pubblici. Non inserire nomi reali, email o informazioni riservate.','Salva','Tutti','Nessun documento disponibile.','Accedi per continuare.','Precedente','Successivo','Operazione non riuscita. Riprova.','Salvato.','Passaggio o testo interessato (facoltativo)','Numero pratica','Già segnalato. Controlla la richiesta esistente.','In attesa','In attesa delle modifiche','Richiedi modifiche','Revisione prioritaria','Oltre 3 giorni','Documento alla segnalazione','Cronologia decisioni','Aggiorna','Il documento o la richiesta è cambiato. Aggiorna e verifica nuovamente.','Le segnalazioni sono esaminate in privato. I motivi sono comunicati agli utenti interessati.','Novità degli autori seguiti','Autori seguiti','La priorità determina l’ordine di revisione. Le segnalazioni non nascondono né certificano automaticamente i documenti.'],
 pt: ['Autor','Documentos públicos','Seguir','Deixar de seguir','Seguidores','Seguindo','Apelido público','Apresentação','O apelido e a apresentação são públicos. Não inclua nomes reais, e-mails ou informações confidenciais.','Salvar','Todos','Nenhum documento disponível.','Entre para continuar.','Anterior','Próximo','Não foi possível concluir. Tente novamente.','Salvo.','Etapa ou trecho afetado (opcional)','Número de protocolo','Já foi denunciado. Consulte a solicitação existente.','Pendente','Aguardando alterações','Solicitar alterações','Revisão prioritária','Mais de 3 dias','Documento no momento da denúncia','Histórico de decisões','Atualizar','O documento ou a solicitação mudou. Atualize e revise novamente.','Denúncias são analisadas em privado. Os motivos são informados aos usuários afetados.','Novidades de autores seguidos','Autores seguidos','A prioridade define a ordem de revisão. Denúncias não ocultam nem certificam documentos automaticamente.'],
 ru: ['Автор','Открытые документы','Подписаться','Отписаться','Подписчики','Подписки','Публичный псевдоним','О себе','Псевдоним и описание видны всем. Не указывайте реальные имена, email и конфиденциальные сведения.','Сохранить','Все','Нет документов.','Войдите для продолжения.','Назад','Далее','Не удалось выполнить. Повторите.','Сохранено.','Проблемный этап или текст (необязательно)','Номер обращения','Уже подано. Проверьте существующее обращение.','Ожидает','Ожидаются исправления','Запросить исправления','Приоритетная проверка','Более 3 дней','Документ на момент жалобы','История решений','Обновить','Документ или обращение изменились. Обновите и проверьте снова.','Жалобы рассматриваются конфиденциально. Причины решений сообщаются заинтересованным пользователям.','Новое в подписках','Авторы в подписках','Приоритет определяет порядок проверки. Жалобы не скрывают и не сертифицируют документы автоматически.'],
 ar: ['المؤلف','المستندات العامة','متابعة','إلغاء المتابعة','المتابعون','المتابَعون','اسم مستعار عام','نبذة','الاسم والنبذة متاحان للجميع. لا تضع أسماء حقيقية أو بريداً إلكترونياً أو معلومات سرية.','حفظ','الكل','لا توجد مستندات.','يرجى تسجيل الدخول.','السابق','التالي','تعذّر الإكمال. حاول مجدداً.','تم الحفظ.','الخطوة أو المقطع المعني (اختياري)','رقم الطلب','تم الإبلاغ مسبقاً. راجع طلبك الحالي.','قيد الانتظار','بانتظار تعديلات المؤلف','طلب تعديلات','مراجعة ذات أولوية','أكثر من 3 أيام','المستند وقت الإبلاغ','سجل القرارات','تحديث','تغير المستند أو الطلب. حدّث الصفحة وراجع مجدداً.','يراجع المشغّلون البلاغات بشكل خاص. تُرسل أسباب القرار إلى المستخدمين المعنيين.','جديد المؤلفين المتابَعين','المؤلفون المتابَعون','تحدد الأولوية ترتيب المراجعة. لا تخفي البلاغات المستندات أو تعتمد سلامتها تلقائياً.'],
};
export function getSocialUi(locale='en-US') {
 const row=rows[locale.split('-')[0]]||rows.en;
 const revisions={
  ko:['수정본 재검토 요청','새로 공개 저장한 수정본을 선택해주세요. 이전 문서의 숨김 상태는 자동으로 해제되지 않습니다.','수정본','현재 검토할 문서'],
  en:['Submit revision for review','Select a newly published corrected copy. The previous document remains restricted until an operator restores it.','Revised document','Current document to review'],
  ja:['修正版の再確認を依頼','新しく公開保存した修正版を選択してください。元の文書の公開制限は自動解除されません。','修正版','現在の確認対象'],
  de:['Überarbeitung einreichen','Wählen Sie eine neu veröffentlichte Korrektur. Die Sperre des alten Dokuments wird nicht automatisch aufgehoben.','Überarbeitung','Aktuell zu prüfendes Dokument'],
  fr:['Soumettre une révision','Choisissez une nouvelle copie corrigée publiée. La restriction de l’ancien document reste en place.','Document révisé','Document actuel à examiner'],
  es:['Enviar revisión','Seleccione una nueva copia corregida y publicada. La restricción del documento anterior no se retira automáticamente.','Documento corregido','Documento actual para revisar'],
  it:['Invia revisione','Seleziona una nuova copia corretta e pubblicata. Il blocco del documento precedente non viene rimosso automaticamente.','Documento corretto','Documento attuale da esaminare'],
  pt:['Enviar revisão','Selecione uma nova cópia corrigida e publicada. A restrição do documento anterior não é removida automaticamente.','Documento revisado','Documento atual para revisão'],
  ru:['Отправить исправления','Выберите новую опубликованную исправленную копию. Ограничение исходного документа автоматически не снимается.','Исправленный документ','Текущий документ для проверки'],
  ar:['إرسال نسخة للمراجعة','اختر نسخة مصححة منشورة حديثاً. لا يُرفع تقييد المستند السابق تلقائياً.','المستند المصحح','المستند الحالي للمراجعة']
 }[locale.split('-')[0]]||['Submit revision for review','Select a newly published corrected copy. Restrictions remain until reviewed.','Revised document','Current document to review'];
 return {...Object.fromEntries(keys.map((key,index)=>[key,row[index]])),...Object.fromEntries(['resubmit','revisionHelp','revision','currentDocument'].map((key,index)=>[key,revisions[index]]))};
}
