import { KR_ON_FORM_ROWS } from './regionalKrOnFormText20261005.js';
import { REQUIREMENT_REVIEW_ROWS } from './requirementReviewText.js';
import { REQUIREMENT_REVIEW_ROWS_20261005 } from './requirementReviewText20261005.js';
import { REQUIREMENT_REVIEW_REMAINING_ROWS_20261005 } from './requirementReviewRemainingText20261005.js';
import { REVIEW_FOLLOWUP_ROWS_20261005 } from './regionalReviewFollowupText20261005.js';
import { SINGAPORE_REVIEW_ROWS } from './singaporeReviewText20261005.js';
import { REGIONAL_BATCH_ROWS } from './regionalBatchText20261005.js';
import { REGIONAL_ASSESSMENT_ROWS } from './regionalAssessmentText20261005.js';
import { REGIONAL_FORM_REVIEW_ROWS } from './regionalFormReviewText20261005.js';
import { SINGAPORE_FORM_ROWS } from './singaporeFormText20261005.js';
import { INSPECTION_FORM_ROWS } from './regionalInspectionText20261005.js';
import { AU_JP_FORM_ROWS } from './regionalAuJpFormText20261005.js';
import { PERMIT_FORM_ROWS } from './regionalPermitText20261005.js';
import { COUNTRY_FORM_ROWS } from './regionalCountryFormText20261005.js';
import { FR_ES_FORM_ROWS } from './regionalFrEsFormText20261005.js';
import { IT_BR_QC_FORM_ROWS } from './regionalItBrQcFormText20261005.js';
// Every column is a document language, independent of the work jurisdiction.
export const TASK_SAFETY_LANGUAGES = ['ko','en','de','ja','fr','it','es','ar','pt','ru'];
const rows = `
usScope|미국 1910 기준은 일반산업 대상입니다. 건설·조선 등은 별도 기준을 확인하세요.|US 1910 references cover general industry. Construction and shipyards require separate rules.|US-1910-Referenzen betreffen die allgemeine Industrie. Bau und Werften haben eigene Regeln.|米国1910は一般産業向けです。建設・造船等は別の基準を確認してください。|Les références US 1910 concernent l’industrie générale. Construction et chantiers navals ont des règles distinctes.|I riferimenti US 1910 riguardano l’industria generale. Edilizia e cantieri navali hanno regole distinte.|Las referencias US 1910 cubren la industria general. Construcción y astilleros tienen reglas distintas.|مراجع US 1910 تخص الصناعة العامة. للبناء وأحواض السفن قواعد منفصلة.|As referências US 1910 tratam da indústria geral. Construção e estaleiros têm regras próprias.|Ссылки US 1910 относятся к общей промышленности. Для строительства и верфей действуют отдельные правила.
auScope|호주의 모델 지침은 주·준주별 채택 여부를 확인해야 합니다. 고소작업 선택만으로 SWMS 적용을 확정하지 않습니다.|Check Australian state/territory adoption of model codes. Selecting height work does not establish SWMS applicability.|Übernahme der Modellregeln im Bundesstaat/Territorium prüfen. Höhenarbeit allein begründet keine SWMS-Pflicht.|豪州のモデル指針は州・準州での採用を確認してください。高所作業の選択だけでSWMS適用は決まりません。|Vérifiez l’adoption des codes modèles par l’État/territoire australien. Le travail en hauteur seul ne détermine pas l’application du SWMS.|Verificare l’adozione dei codici modello nello Stato/territorio australiano. Il lavoro in quota da solo non determina l’applicabilità dello SWMS.|Compruebe la adopción de los códigos modelo en el estado/territorio australiano. Trabajar en altura no determina por sí solo el SWMS.|تحقق من اعتماد القواعد النموذجية في الولاية أو الإقليم الأسترالي. اختيار العمل على ارتفاع لا يحدد وحده انطباق SWMS.|Verifique a adoção dos códigos modelo no estado/território australiano. Trabalho em altura não determina sozinho a aplicação do SWMS.|Проверьте принятие модельных норм штатом/территорией Австралии. Выбор высотных работ сам по себе не определяет необходимость SWMS.
gbScope|HSE 자료는 그레이트브리튼 기준입니다. 북아일랜드 적용은 별도로 확인해야 합니다.|HSE references cover Great Britain. Northern Ireland applicability needs separate review.|HSE-Referenzen gelten für Großbritannien. Nordirland ist gesondert zu prüfen.|HSE資料はグレートブリテン向けです。北アイルランドの適用は別途確認が必要です。|Les références HSE concernent la Grande-Bretagne. L’Irlande du Nord nécessite un examen distinct.|I riferimenti HSE riguardano la Gran Bretagna. L’Irlanda del Nord richiede verifica separata.|Las referencias HSE cubren Gran Bretaña. Irlanda del Norte requiere revisión separada.|مراجع HSE تخص بريطانيا العظمى. يلزم فحص منفصل لأيرلندا الشمالية.|As referências HSE abrangem a Grã-Bretanha. A Irlanda do Norte exige revisão separada.|Источники HSE относятся к Великобритании без Северной Ирландии. Для Северной Ирландии нужна отдельная проверка.
sgHeightScope|싱가포르: 공장의 위험 고소작업 PTW와 일반 추락방지 의무의 적용 범위를 구분하세요.|Singapore: distinguish factory hazardous-WAH PTW scope from general fall-protection duties.|Singapur: Anwendungsbereich der PTW für gefährliche Höhenarbeit in Fabriken von allgemeinen Absturzschutzpflichten unterscheiden.|シンガポール：工場の危険な高所作業PTWと一般墜落防止義務の適用範囲を区別してください。|Singapour : distinguer le PTW pour travail en hauteur dangereux en usine des obligations générales de prévention des chutes.|Singapore: distinguere il PTW per lavoro in quota pericoloso in fabbrica dagli obblighi generali anticaduta.|Singapur: distinguir el PTW para trabajo peligroso en altura en fábricas de las obligaciones generales de protección contra caídas.|سنغافورة: ميّز نطاق PTW للعمل الخطر على ارتفاع في المصانع عن واجبات منع السقوط العامة.|Singapura: distinguir o PTW para trabalho perigoso em altura em fábricas das obrigações gerais de proteção contra quedas.|Сингапур: отличайте область PTW для опасных высотных работ на фабриках от общих обязанностей защиты от падения.
marineScope|연결 자료는 해양·조선 분야 자료입니다. 다른 업종의 허가·자격 요건으로 그대로 적용하지 않습니다.|The reference is for marine/shipbuilding work. Do not transfer its permit or qualification rules to other sectors.|Die Quelle betrifft Schifffahrt/Schiffbau. Erlaubnis- und Qualifikationsregeln nicht auf andere Branchen übertragen.|参照資料は海事・造船向けです。許可・資格条件を他業種にそのまま適用しません。|La référence vise le secteur maritime/naval. Ses règles de permis et de qualification ne s’étendent pas aux autres secteurs.|Il riferimento riguarda il settore marittimo/navale. Non estendere permessi e qualifiche ad altri settori.|La referencia es marítima/naval. No extrapole permisos o cualificaciones a otros sectores.|المرجع للقطاع البحري وبناء السفن. لا تعمم قواعد التصاريح أو التأهيل على القطاعات الأخرى.|A referência é marítima/naval. Não estenda regras de permissão ou qualificação a outros setores.|Источник относится к морским работам/судостроению. Не переносите требования допуска и квалификации на другие отрасли.
caScope|캐나다는 연방·주별 관할과 적용 규정을 확인해야 합니다. 일반 지침을 전국 공통 의무로 보지 않습니다.|Confirm Canadian federal/provincial jurisdiction. General guidance is not a nationwide legal requirement.|Kanadische Bundes-/Provinzzuständigkeit prüfen. Allgemeine Hinweise sind keine landesweite Pflicht.|カナダは連邦・州の管轄を確認してください。一般指針は全国共通の義務ではありません。|Confirmez la compétence fédérale/provinciale au Canada. Un guide général n’est pas une obligation nationale.|Verificare la competenza federale/provinciale canadese. Una guida generale non è un obbligo nazionale.|Confirme la jurisdicción federal/provincial canadiense. Una guía general no es una obligación nacional.|تحقق من الاختصاص الفيدرالي أو الإقليمي في كندا. الإرشادات العامة ليست التزاماً قانونياً وطنياً.|Confirme a jurisdição federal/provincial canadense. Orientação geral não é obrigação nacional.|Уточните федеральную/провинциальную юрисдикцию Канады. Общие рекомендации не являются единой национальной обязанностью.
deadScope|이 항목은 정전·차단 확인용입니다. 활선작업의 필요성 판단이나 별도 작업 승인 절차를 대체하지 않습니다.|These checks address de-energisation and isolation. They do not replace live-work justification or separate authorisation.|Diese Punkte prüfen Freischaltung. Sie ersetzen weder die Begründung noch die gesonderte Freigabe für Arbeiten unter Spannung.|停電・遮断の確認項目です。活線作業の必要性判断や別途承認手続の代わりにはなりません。|Ces points concernent la mise hors tension. Ils ne remplacent pas la justification ni l’autorisation de travail sous tension.|Questi controlli riguardano la messa fuori tensione. Non sostituiscono motivazione e autorizzazione per lavori sotto tensione.|Estas comprobaciones son de desconexión y aislamiento. No sustituyen justificación ni autorización de trabajos en tensión.|تختص الفحوص بفصل الطاقة والعزل ولا تستبدل تبرير العمل تحت الجهد أو التصريح المنفصل.|Estas verificações tratam de desenergização. Não substituem justificativa nem autorização para trabalho energizado.|Проверки относятся к снятию напряжения. Они не заменяют обоснование и отдельный допуск к работам под напряжением.
select|작업허가서에 추가할 확인 항목|Checks to add to the work permit|Zusätzliche Prüfungen zur Arbeitserlaubnis|作業許可書に追加する確認項目|Vérifications à ajouter au permis de travail|Verifiche da aggiungere al permesso di lavoro|Comprobaciones para añadir a la autorización|فحوص تضاف إلى تصريح العمل|Verificações a incluir na permissão de trabalho|Проверки для добавления к разрешению на работы
help|해당 작업을 선택한 뒤 작업허가서를 추가하세요. 현장 측정·확인 결과는 작업할 때 새로 입력합니다.|Select the activities, then add the work permit. Enter fresh measurements and checks for each job.|Tätigkeiten auswählen, dann die Arbeitserlaubnis hinzufügen. Messungen und Prüfungen für jeden Einsatz neu erfassen.|作業を選び、作業許可書を追加してください。測定値と確認結果は作業ごとに入力します。|Sélectionnez les activités, puis ajoutez le permis. Saisissez les mesures et vérifications à chaque intervention.|Selezionare le attività, poi aggiungere il permesso. Inserire misure e verifiche per ogni intervento.|Seleccione las actividades y añada la autorización. Registre mediciones y comprobaciones para cada trabajo.|اختر الأنشطة ثم أضف تصريح العمل. أدخل قياسات ونتائج فحص جديدة لكل عمل.|Selecione as atividades e adicione a permissão. Registre medições e verificações novas a cada trabalho.|Выберите виды работ и добавьте разрешение. Замеры и результаты проверок вводятся заново для каждой работы.
height|고소·추락위험 작업|Work at height|Arbeiten mit Absturzgefahr|高所・墜落危険作業|Travail en hauteur|Lavori in quota|Trabajos en altura|العمل على ارتفاع|Trabalho em altura|Работы на высоте
confined|밀폐공간 작업|Confined space entry|Arbeiten in Behältern und engen Räumen|閉所作業|Travail en espace confiné|Ingresso in spazi confinati|Trabajos en espacios confinados|العمل في الأماكن المحصورة|Trabalho em espaços confinados|Работы в ограниченных и замкнутых пространствах
electrical|정전·전기 작업|Electrical isolation and work|Freischalten und elektrische Arbeiten|停電・電気作業|Consignation et travaux électriques|Messa in sicurezza e lavori elettrici|Consignación y trabajos eléctricos|العزل والأعمال الكهربائية|Desenergização e serviços em eletricidade|Отключение и работы в электроустановках
hot|화기 작업|Hot work|Feuergefährliche Arbeiten|火気使用作業|Travaux par points chauds|Lavori a caldo|Trabajos en caliente|الأعمال الساخنة|Trabalho a quente|Огневые работы
applicability|적용 규정·작업 분류·별도 허가서 참조|Applicable rules, task classification and separate permit reference|Anwendbare Regeln, Tätigkeitseinstufung und gesonderte Erlaubnis|適用規定・作業区分・別途許可書の参照|Règles applicables, classification et permis distinct|Regole applicabili, classificazione e permesso separato|Normativa aplicable, clasificación y autorización específica|القواعد المطبقة وتصنيف العمل ومرجع التصريح المنفصل|Regras aplicáveis, classificação e referência à permissão específica|Применимые правила, категория работ и ссылка на отдельное разрешение
competence|담당자·교육·역량·자격·작업 권한 확인|Responsible people, training, competence and work authorisation|Verantwortliche, Unterweisung, Qualifikation und Beauftragung|担当者・教育・力量・資格・作業権限の確認|Responsables, formation, compétences et autorisations|Responsabili, formazione, competenze e autorizzazioni|Responsables, formación, competencia y autorización|المسؤولون والتدريب والكفاءة والتفويض بالعمل|Responsáveis, capacitação, competência e autorização|Ответственные, обучение, квалификация и допуск к работе
avoidHeight|고소작업 회피·작업발판·난간 등 우선 조치|Avoiding height work; platforms and collective fall protection|Vermeidung von Höhenarbeit; Arbeitsbühnen und kollektiver Absturzschutz|高所作業の回避・作業床・手すり等の優先措置|Éviter le travail en hauteur ; plateformes et protections collectives|Evitare lavori in quota; piattaforme e protezioni collettive|Evitar trabajos en altura; plataformas y protección colectiva|تجنب العمل على ارتفاع والمنصات والحماية الجماعية من السقوط|Evitar trabalho em altura; plataformas e proteção coletiva|Исключение работ на высоте; настилы и коллективная защита
fallSystem|추락 방지·제동 장비, 부착점, 필요 여유거리 확인|Fall restraint/arrest equipment, anchors and required clearance|Rückhalte-/Auffangsysteme, Anschlagpunkte und Freiraum|墜落防止・制止用器具、取付設備、地面・障害物までの必要クリアランスの確認|Systèmes de retenue/arrêt, ancrages et tirant d’air|Sistemi di trattenuta/arresto, ancoraggi e tirante d’aria|Sistemas de retención/anticaídas, anclajes y distancia libre|معدات منع وإيقاف السقوط ونقاط التثبيت والخلوص المطلوب|Sistemas de restrição de movimentação/retenção de queda, ancoragens e zona livre|Удерживающие/страховочные системы, анкеры и запас высоты
access|출입·취약면·개구부·낙하물 통제|Access, fragile surfaces, openings and falling-object controls|Zugang, nicht tragfähige Flächen, Öffnungen und herabfallende Gegenstände|昇降・踏み抜き・開口部・落下物の対策|Accès, surfaces fragiles, ouvertures et chutes d’objets|Accessi, superfici fragili, aperture e caduta di oggetti|Accesos, superficies frágiles, huecos y caída de objetos|الوصول والأسطح الهشة والفتحات والأجسام الساقطة|Acesso, superfícies frágeis, aberturas e queda de objetos|Доступ, непрочные поверхности, проёмы и падающие предметы
weather|기상·작업 조건·장비 점검·중지 기준|Weather, work conditions, equipment inspection and stop criteria|Wetter, Arbeitsbedingungen, Ausrüstungsprüfung und Abbruchkriterien|気象・作業条件・器具点検・中止基準|Météo, conditions, inspection du matériel et critères d’arrêt|Meteo, condizioni, controllo attrezzature e criteri di sospensione|Meteorología, condiciones, revisión de equipos y criterios de parada|الطقس وظروف العمل وفحص المعدات ومعايير التوقف|Clima, condições, inspeção de equipamentos e critérios de parada|Погода, условия, осмотр оборудования и критерии остановки
rescue|현장 구조 방법·인력·장비·연락 및 구조 준비 확인|Site rescue method, people, equipment, communication and readiness|Rettungsverfahren, Personal, Ausrüstung, Kommunikation und Bereitschaft|現場の救出方法・人員・器具・連絡と準備確認|Méthode de secours, personnel, matériel, communication et disponibilité|Metodo di soccorso, personale, attrezzature, comunicazioni e disponibilità|Método de rescate, personal, equipos, comunicación y preparación|طريقة الإنقاذ والأفراد والمعدات والاتصال والجاهزية|Método de resgate, equipe, equipamentos, comunicação e prontidão|Способ спасения, персонал, оборудование, связь и готовность
space|공간 식별·출입 필요성·접근 및 탈출 경로|Space identification, need for entry, access and escape routes|Raumkennzeichnung, Notwendigkeit des Einstiegs, Zugang und Fluchtwege|場所の特定・立入りの必要性・出入口と退避経路|Identification, nécessité d’entrer, accès et voies d’évacuation|Identificazione, necessità di ingresso, accessi e vie di uscita|Identificación, necesidad de entrada, accesos y evacuación|تحديد المكان وضرورة الدخول ومسارات الوصول والخروج|Identificação, necessidade de entrada, acessos e rotas de saída|Идентификация пространства, необходимость входа, доступ и выход
entryRoles|출입자·외부 감시인·작업 책임자 및 연락 방법|Entrants, outside attendant, person in charge and communication|Einsteigende, Sicherungsposten, Aufsichtführende und Kommunikation|作業者・外部監視担当者・作業責任者と連絡方法|Intervenants, surveillant extérieur, responsable et communication|Entranti, sorvegliante esterno, responsabile e comunicazioni|Entrantes, vigilancia exterior, responsable y comunicación|الداخلون والمراقب الخارجي والمسؤول عن العمل ووسيلة الاتصال|Trabalhadores, vigilância externa, responsável e comunicação|Входящие, наружный наблюдающий, руководитель и связь
atmosphere|측정 대상·허용 기준·재측정 또는 연속 감시 계획|Atmospheric test targets, acceptance criteria and repeat/continuous monitoring|Messstoffe, zulässige Werte und Wiederholungs-/Dauermessung|測定対象・許容基準・再測定または連続監視計画|Paramètres, critères d’acceptation et contrôles répétés/continus|Parametri, criteri di accettabilità e monitoraggio ripetuto/continuo|Parámetros, criterios de aceptación y vigilancia repetida/continua|المواد المقاسة وحدود القبول وخطة القياس المتكرر أو المستمر|Parâmetros, limites de aceitação e monitoramento repetido/contínuo|Параметры атмосферы, допустимые значения и повторный/постоянный контроль
isolation|유입물·설비 에너지 차단·잠금·잔류 에너지 확인|Isolation of incoming substances and energy; locks and stored-energy checks|Trennung von Stoffzufuhr und Energie; Verriegelung und Restenergie|流入物・設備エネルギーの遮断・施錠・残留エネルギー確認|Isolation des arrivées et énergies, verrouillage et énergies résiduelles|Isolamento di sostanze ed energie, blocchi ed energie residue|Aislamiento de sustancias y energías, bloqueo y energía residual|عزل المواد والطاقة والأقفال والتحقق من الطاقة المخزنة|Isolamento de substâncias e energias, bloqueios e energia residual|Отключение подачи веществ и энергии, блокировка и остаточная энергия
ventilation|환기·호흡보호·오염원 통제 및 정지 시 조치|Ventilation, respiratory protection, contaminant controls and failure response|Lüftung, Atemschutz, Schadstoffkontrolle und Verhalten bei Ausfall|換気・呼吸用保護具・発生源対策と停止時措置|Ventilation, protection respiratoire, polluants et conduite en cas de panne|Ventilazione, protezione respiratoria, contaminanti e risposta ai guasti|Ventilación, protección respiratoria, contaminantes y actuación ante fallos|التهوية وحماية التنفس والتحكم بالملوثات والاستجابة للأعطال|Ventilação, proteção respiratória, contaminantes e resposta a falhas|Вентиляция, защита дыхания, загрязнения и действия при отказе
entryLog|출입 인원·입퇴장 시각·전원 퇴장 확인|Entrant count, entry/exit times and confirmation everyone has exited|Personenzahl, Ein-/Ausstiegszeiten und Abschlusskontrolle|入退場人数・時刻・全員退場の確認|Effectif, heures d’entrée/sortie et évacuation complète|Numero di entranti, orari di ingresso/uscita e conferma dell’uscita di tutti|Número de entrantes, horas de entrada/salida y confirmación de salida de todos|عدد الداخلين وأوقات الدخول والخروج والتأكد من الإخلاء|Número de entrantes, horários de entrada/saída e confirmação da saída de todos|Учёт людей, время входа/выхода и проверка выхода всех
circuit|설비·회로·전원 식별, 역송전·유도전압·저장 에너지|Equipment, circuits, supplies, backfeed, induced voltage and stored energy|Anlagen, Stromkreise, Einspeisungen, Rückspeisung, Induktion und Restenergie|設備・回路・電源の特定、逆送電・誘導電圧・蓄積エネルギー|Équipements, circuits, sources, retours, tensions induites et énergie stockée|Impianti, circuiti, fonti, ritorni, tensioni indotte ed energia accumulata|Equipos, circuitos, fuentes, retornos, tensión inducida y energía almacenada|المعدات والدوائر والمصادر والتغذية العكسية والجهد المستحث والطاقة المخزنة|Equipamentos, circuitos, fontes, retorno, tensão induzida e energia armazenada|Оборудование, цепи, источники, обратное питание, наводки и запасённая энергия
disconnect|전원 분리·재투입 방지·잠금 및 표지 확인|Disconnection, prevention of re-energisation, locks and tags|Freischalten, gegen Wiedereinschalten sichern, Verriegeln und Kennzeichnen|電源の切離し・再通電防止・施錠と表示|Séparation, prévention de réalimentation, condamnation et signalisation|Sezionamento, prevenzione rialimentazione, blocchi e segnaletica|Desconexión, prevención de realimentación, bloqueo y señalización|الفصل ومنع إعادة التوصيل والأقفال والبطاقات|Seccionamento, impedimento de reenergização, bloqueio e sinalização|Отключение, предотвращение включения, блокировки и плакаты
proveDead|검전기·기능 확인·무전압 검증 결과·확인자|Voltage detector, functional check, absence-of-voltage result and tester|Spannungsprüfer, Funktionsprüfung, Spannungsfreiheit und prüfende Person|検電器・機能確認・無電圧確認結果・確認者|Vérificateur d’absence de tension, contrôle de fonctionnement, résultat de vérification et intervenant|Rilevatore, prova funzionale, assenza di tensione e verificatore|Detector, prueba funcional, ausencia de tensión y verificador|كاشف الجهد وفحصه ونتيجة التحقق من غياب الجهد والفاحص|Detector, teste funcional, ausência de tensão e responsável|Указатель напряжения, проверка исправности, отсутствие напряжения и проверяющий
earthBarrier|해당 시 접지·단락, 인접 충전부 방호·작업구역 구분|Earthing/short-circuiting where required; adjacent live-part protection and boundaries|Erden/Kurzschließen soweit erforderlich; benachbarte aktive Teile abdecken und abgrenzen|必要な接地・短絡、近接充電部の防護と作業区域|Mise à la terre/court-circuit si requise ; protection des parties voisines sous tension et délimitation|Messa a terra/cortocircuito ove richiesto; protezione delle parti adiacenti in tensione e delimitazione|Puesta a tierra/cortocircuito cuando proceda; protección de partes próximas en tensión y delimitación|التأريض والقصر عند اللزوم وحماية الأجزاء المجاورة الحية وحدود العمل|Aterramento/curto-circuito quando exigido; proteção de partes próximas energizadas e delimitação|Заземление/закорачивание при необходимости; защита соседних токоведущих частей под напряжением и границы
restore|작업 완료·인원 철수·잠금 해제·복전 승인 기록|Completion, personnel clearance, lock removal and re-energisation authority|Arbeitsende, Personenfreigabe, Aufheben der Sicherung und Wiedereinschaltfreigabe|作業終了・退避・施錠解除・復電承認の記録|Fin des travaux, retrait du personnel, décondamnation et autorisation de remise sous tension|Fine lavori, sgombero, rimozione blocchi e autorizzazione alla rialimentazione|Fin del trabajo, retirada del personal, desbloqueo y autorización de reposición|إنهاء العمل وإخلاء الأفراد وإزالة الأقفال والإذن بإعادة التوصيل|Conclusão, retirada de pessoas, desbloqueio e autorização de reenergização|Завершение, вывод людей, снятие блокировок и разрешение на включение
combustibles|가연물 제거·차폐, 벽 반대편·하부·개구부 확인|Combustible removal/shielding; opposite faces, lower areas and openings|Brennbares entfernen/abdecken; Rückseiten, untere Bereiche und Öffnungen prüfen|可燃物除去・遮へい、反対側・下方・開口部の確認|Retrait/protection des combustibles ; faces opposées, niveaux inférieurs et ouvertures|Rimozione/protezione combustibili; lati opposti, aree sottostanti e aperture|Retirada/protección de combustibles; caras opuestas, zonas inferiores y huecos|إزالة أو حماية المواد القابلة للاحتراق وفحص الجوانب المقابلة والمناطق السفلية والفتحات|Remoção/proteção de combustíveis; faces opostas, áreas inferiores e aberturas|Удаление/защита горючих материалов; обратные стороны, нижние зоны и проёмы
fireWatch|화재감시자·소화설비·작업 후 감시 기간과 완료시각|Fire watch, extinguishing equipment, post-work watch duration and completion time|Brandwache, Löschmittel, Nachkontrolldauer und Abschlusszeit|火災監視員・消火設備・作業後監視時間と終了時刻|Surveillance incendie, extincteurs, durée après travaux et heure de fin|Sorveglianza antincendio, estintori, durata dopo i lavori e ora finale|Vigilancia de incendios, extintores, duración posterior y hora de cierre|مراقب الحريق ومعدات الإطفاء ومدة المراقبة بعد العمل ووقت انتهائها|Vigia de incêndio, extintores, duração após o trabalho e horário final|Пожарное наблюдение, средства тушения, длительность после работ и время окончания
gasFumes|가스·증기·흄·분진 평가, 측정 및 환기|Gas, vapour, fume and dust assessment, testing and ventilation|Gase, Dämpfe, Rauch und Staub bewerten, messen und belüften|ガス・蒸気・ヒューム・粉じんの評価、測定と換気|Évaluation des gaz, vapeurs, fumées et poussières, mesures et ventilation|Valutazione gas, vapori, fumi e polveri, misure e ventilazione|Evaluación de gases, vapores, humos y polvo, medición y ventilación|تقييم الغازات والأبخرة والأدخنة والغبار والقياس والتهوية|Avaliação de gases, vapores, fumos e poeiras, medição e ventilação|Оценка газов, паров, дыма и пыли, измерения и вентиляция
cylinders|용기·배관 잔류물, 가스통·호스·역화 방지 및 장비 점검|Vessel/pipe residues, cylinders, hoses, flashback protection and equipment checks|Behälter-/Rohrreste, Gasflaschen, Schläuche, Flammenrückschlagschutz und Geräteprüfung|容器・配管残留物、ガスボンベ・ホース・逆火防止と器具点検|Résidus, bouteilles, tuyaux, antiretours de flamme et contrôle du matériel|Residui in recipienti/tubazioni, bombole, tubi flessibili, dispositivi antiritorno di fiamma e controllo attrezzature|Residuos en recipientes/tuberías, botellas, mangueras, protección contra retroceso de llama y revisión de equipos|بقايا الأوعية والأنابيب والأسطوانات والخراطيم ومانعات رجوع اللهب وفحص المعدات|Resíduos em recipientes/tubulações, cilindros, mangueiras, proteção contra retrocesso de chama e inspeção|Остатки в ёмкостях/трубах, баллоны, шланги, защита от обратного удара и осмотр
stop|중지·퇴출·재확인·재허가 조건|Stop, evacuation, recheck and reauthorisation conditions|Abbruch-, Räumungs-, Nachprüfungs- und Neufreigabebedingungen|中止・退避・再確認・再許可の条件|Conditions d’arrêt, d’évacuation, de contrôle et de réautorisation|Condizioni di sospensione, evacuazione, verifica e nuova autorizzazione|Condiciones de parada, evacuación, revisión y nueva autorización|شروط التوقف والإخلاء وإعادة الفحص والتصريح|Condições de parada, abandono, verificação e nova autorização|Условия остановки, эвакуации, повторной проверки и допуска
record|이번 작업 측정·확인 기록|Measurements and checks for this job|Messungen und Prüfungen dieses Einsatzes|今回作業の測定・確認記録|Mesures et vérifications de cette intervention|Misure e verifiche di questo intervento|Mediciones y comprobaciones de este trabajo|قياسات وفحوص هذا العمل|Medições e verificações deste trabalho|Замеры и проверки для этой работы
instrument|측정기 식별·교정·기능 확인|Instrument ID, calibration and functional check|Messgerät, Kalibrierung und Funktionsprüfung|測定器番号・校正・機能確認|Identifiant de l’appareil, étalonnage et contrôle de fonctionnement|Identificativo dello strumento, taratura e prova funzionale|Identificación del instrumento, calibración y prueba funcional|معرّف الجهاز والمعايرة وفحص الوظيفة|Identificação do instrumento, calibração e teste funcional|Идентификатор прибора, калибровка и проверка исправности
criteria|적용 기준·판정 근거|Acceptance criteria and decision basis|Zulässige Werte und Bewertungsgrundlage|適用基準・判定根拠|Critères d’acceptation et base de décision|Criteri di accettabilità e base della decisione|Criterios de aceptación y fundamento|معايير القبول وأساس القرار|Critérios de aceitação e fundamento|Критерии допуска и основание решения
scopeNote|해당 업종·지역의 허가 절차와 함께 사용하는 확인 항목입니다. 이 서식만으로 작업을 승인하지 않습니다.|Use these checks with the applicable sector and local permit procedure. This form alone does not authorise work.|Diese Prüfungen ergänzen das örtliche und branchenspezifische Freigabeverfahren. Das Formular allein erlaubt keine Arbeit.|業種・地域の許可手続と併用する確認項目です。この様式だけで作業を許可するものではありません。|Ces vérifications complètent la procédure sectorielle et locale. Ce formulaire seul n’autorise pas les travaux.|Queste verifiche integrano la procedura locale e di settore. Il modulo da solo non autorizza i lavori.|Estas comprobaciones complementan el procedimiento local y sectorial. El formulario por sí solo no autoriza el trabajo.|تُستخدم الفحوص مع إجراءات التصريح المحلية والقطاعية. هذا النموذج وحده لا يجيز بدء العمل.|Estas verificações complementam o procedimento local e setorial. O formulário sozinho não autoriza o trabalho.|Проверки дополняют местный и отраслевой порядок допуска. Сам бланк не разрешает выполнение работ.
references|작업별 적용 기준 참조|Task-specific reference|Tätigkeitsspezifische Referenz|作業別の適用基準参照|Référence propre à l’activité|Riferimento specifico dell’attività|Referencia específica del trabajo|مرجع خاص بالعمل|Referência específica da atividade|Нормативная ссылка по виду работ
qcConfined|밀폐공간 작업 (퀘벡)|Confined space entry (Québec)|Enge Räume (Québec)|閉所作業（ケベック）|Travail en espace clos|Ambienti confinati (Québec)|Espacios confinados (Quebec)|الأماكن المحصورة في كيبيك|Espaços confinados (Quebec)|Замкнутые пространства (Квебек)
qcElectrical|잠금 차단·전기 작업 (퀘벡)|Lockout and electrical work (Québec)|Verriegelung und elektrische Arbeiten (Québec)|施錠・電気作業（ケベック）|Cadenassage et travaux électriques|Blocco e lavori elettrici (Québec)|Bloqueo y trabajos eléctricos (Quebec)|القفل والأعمال الكهربائية في كيبيك|Bloqueio e trabalhos elétricos (Quebec)|Блокировка и электрические работы (Квебек)
roles|현지 절차의 역할·담당자 확인|Roles and people under the local procedure|Rollen und Verantwortliche nach örtlichem Verfahren|現地手続の役割・担当者確認|Rôles et personnes selon la procédure locale|Ruoli e persone secondo la procedura locale|Funciones y personas según el procedimiento local|الأدوار والأشخاص وفق الإجراء المحلي|Funções e pessoas conforme o procedimento local|Роли и ответственные по местному порядку
pending|현행 세부 규정 대조 미완료 — 아래 항목은 현장 확인용 초안입니다.|Current detailed rules are not fully verified; the checks below are a site-review draft.|Aktuelle Detailregeln sind nicht vollständig geprüft; die folgenden Punkte sind ein Prüfentwurf.|現行の詳細規定は未確認の部分があります。以下は現場確認用の案です。|Les règles détaillées actuelles ne sont pas entièrement vérifiées ; les points ci-dessous sont un projet de contrôle.|Le regole attuali non sono interamente verificate; le verifiche seguenti sono una bozza.|Las reglas actuales no están totalmente verificadas; las comprobaciones siguientes son un borrador.|لم تُتحقق جميع القواعد التفصيلية الحالية؛ الفحوص أدناه مسودة للمراجعة الميدانية.|As regras atuais não foram totalmente verificadas; os itens abaixo são uma minuta.|Действующие подробные нормы проверены не полностью; ниже приведён проект проверок.
notice|작성 시 확인 사항|Completion guidance|Hinweise zum Ausfüllen|記入時の確認事項|Consignes de renseignement|Indicazioni per la compilazione|Indicaciones para cumplimentar|إرشادات التعبئة|Orientações de preenchimento|Указания по заполнению
copy|추가한 서류에만 적용됩니다. 기존 저장본은 변경하지 않습니다.|Applies only to newly added documents. Saved forms stay unchanged.|Gilt nur für neu hinzugefügte Dokumente. Gespeicherte Formulare bleiben unverändert.|追加する文書にのみ適用します。保存済みの様式は変更しません。|S’applique aux documents ajoutés. Les formulaires enregistrés restent inchangés.|Si applica ai nuovi documenti. I moduli salvati restano invariati.|Se aplica a documentos nuevos. Los guardados no cambian.|ينطبق على المستندات المضافة فقط. النماذج المحفوظة لا تتغير.|Aplica-se aos novos documentos. Os formulários salvos não mudam.|Применяется к новым документам. Сохранённые формы не изменяются.
`;
// Keep this dictionary limited to the actual specialist form/UI vocabulary.
export const TASK_SAFETY_TEXT = Object.fromEntries([rows, REQUIREMENT_REVIEW_ROWS, REQUIREMENT_REVIEW_ROWS_20261005, REQUIREMENT_REVIEW_REMAINING_ROWS_20261005, REVIEW_FOLLOWUP_ROWS_20261005, SINGAPORE_REVIEW_ROWS, REGIONAL_BATCH_ROWS, REGIONAL_ASSESSMENT_ROWS, REGIONAL_FORM_REVIEW_ROWS, SINGAPORE_FORM_ROWS, AU_JP_FORM_ROWS, INSPECTION_FORM_ROWS, PERMIT_FORM_ROWS, COUNTRY_FORM_ROWS, FR_ES_FORM_ROWS, IT_BR_QC_FORM_ROWS, KR_ON_FORM_ROWS].flatMap(text => text.trim().split('\n')).map(line => {
  const [key, ...values] = line.split('|');
  if (values.length !== TASK_SAFETY_LANGUAGES.length || values.some(v => !v)) throw Error(`Missing task safety translation: ${key}`);
  return [key, Object.fromEntries(TASK_SAFETY_LANGUAGES.map((l,i) => [l, values[i]]))];
}));
export function taskSafetyText(locale, key) {
  return TASK_SAFETY_TEXT[key]?.[String(locale || 'en').split('-')[0]] || TASK_SAFETY_TEXT[key]?.en || key;
}
