const languages = ['ko','en','de','ja','fr','it','es','ar','pt','ru'];
const rows = `
files|파일|Files|Dateien|ファイル|Fichiers|File|Archivos|الملفات|Arquivos|Файлы
notice|이 브라우저에 계정별로 7일간 임시 보관합니다. 공용 기기에서는 작업 후 초안을 지워주세요.|Drafts stay in this browser for 7 days, separately per account. Clear drafts after using a shared device.|Entwürfe bleiben je Konto 7 Tage in diesem Browser. Auf gemeinsam genutzten Geräten anschließend löschen.|下書きはアカウント別にこのブラウザーで7日間保存されます。共有端末では使用後に削除してください。|Brouillons conservés 7 jours dans ce navigateur, par compte. Effacez-les après utilisation d’un appareil partagé.|Bozze conservate per account in questo browser per 7 giorni. Eliminarle dopo l’uso di un dispositivo condiviso.|Borradores guardados por cuenta en este navegador durante 7 días. Bórrelos al terminar en equipos compartidos.|تُحفظ المسودات لكل حساب في هذا المتصفح لمدة 7 أيام. احذفها بعد استخدام جهاز مشترك.|Rascunhos por conta neste navegador por 7 dias. Apague-os após usar um dispositivo compartilhado.|Черновики хранятся в этом браузере отдельно для каждого аккаунта 7 дней. Удаляйте их после работы на общем устройстве.
choice|작성 중인 초안이 있습니다.|An unfinished draft is available.|Ein unfertiger Entwurf ist vorhanden.|作成途中の下書きがあります。|Un brouillon est disponible.|È disponibile una bozza.|Hay un borrador pendiente.|توجد مسودة غير مكتملة.|Há um rascunho disponível.|Есть незавершённый черновик.
resume|이 작업 이어쓰기|Continue this work|Diese Arbeit fortsetzen|この作業を再開|Reprendre ce travail|Riprendi questo lavoro|Continuar este trabajo|متابعة هذا العمل|Continuar este trabalho|Продолжить эту работу
discard|초안 지우고 새로 시작|Clear draft and start fresh|Entwurf löschen und neu beginnen|下書きを削除して新規開始|Effacer et recommencer|Elimina e ricomincia|Borrar y empezar de nuevo|حذف المسودة والبدء من جديد|Apagar e recomeçar|Удалить черновик и начать заново
changed|저장된 원본이 바뀌어 이 초안을 자동 복원할 수 없습니다.|The saved original changed; this draft cannot be restored automatically.|Das Original wurde geändert; der Entwurf kann nicht automatisch wiederhergestellt werden.|保存済みの原本が変更されたため、この下書きは自動復元できません。|L’original a changé ; restauration automatique impossible.|L’originale è cambiato; ripristino automatico non disponibile.|El original cambió; no se puede restaurar automáticamente.|تغيّر الأصل المحفوظ؛ لا يمكن استعادة المسودة تلقائياً.|O original mudou; a restauração automática não está disponível.|Оригинал изменён; автоматическое восстановление невозможно.
saved|이 브라우저에 임시 저장됨|Draft saved in this browser|Entwurf in diesem Browser gespeichert|このブラウザーに一時保存済み|Brouillon enregistré dans ce navigateur|Bozza salvata in questo browser|Borrador guardado en este navegador|حُفظت المسودة في هذا المتصفح|Rascunho salvo neste navegador|Черновик сохранён в этом браузере
saving|임시 저장 중…|Saving draft…|Entwurf wird gespeichert…|一時保存中…|Enregistrement…|Salvataggio…|Guardando borrador…|جارٍ حفظ المسودة…|Salvando rascunho…|Сохранение черновика…
error|임시 저장을 사용할 수 없습니다. 화면을 닫기 전에 작업을 저장해 주세요.|Draft recovery is unavailable. Save your work before closing.|Entwurfsspeicherung nicht verfügbar. Vor dem Schließen speichern.|一時保存を利用できません。閉じる前に保存してください。|Récupération indisponible. Enregistrez avant de fermer.|Recupero non disponibile. Salvare prima di chiudere.|Recuperación no disponible. Guarde antes de cerrar.|استعادة المسودة غير متاحة. احفظ العمل قبل الإغلاق.|Recuperação indisponível. Salve antes de fechar.|Восстановление недоступно. Сохраните работу перед закрытием.
conflict|다른 탭에서 초안을 변경했습니다. 덮어쓰기를 중지했습니다.|Another tab changed this draft. Overwriting has stopped.|Ein anderer Tab hat den Entwurf geändert. Überschreiben gestoppt.|別のタブで下書きが変更されました。上書きを停止しました。|Un autre onglet a modifié ce brouillon. Écrasement arrêté.|Un’altra scheda ha modificato la bozza. Sovrascrittura interrotta.|Otra pestaña modificó el borrador. Sobrescritura detenida.|عدّلت علامة تبويب أخرى المسودة. أُوقف الاستبدال.|Outra aba alterou o rascunho. A sobrescrita foi interrompida.|Черновик изменён в другой вкладке. Перезапись остановлена.
fresh|복원은 미완성 작업의 이어쓰기입니다. 새 날짜의 작업은 초안을 지우고 시작하세요. 측정값과 확인 사항을 다시 검토하세요.|Restore only to continue unfinished work. For a new day's work, clear the draft. Recheck measurements and confirmations.|Nur unfertige Arbeit fortsetzen. Für einen neuen Arbeitstag Entwurf löschen. Messwerte und Bestätigungen erneut prüfen.|復元は未完了の作業を続けるための機能です。別の日の作業では下書きを削除し、測定値と確認事項を再確認してください。|Restaurez seulement le travail inachevé. Pour un autre jour, effacez le brouillon. Revérifiez mesures et contrôles.|Ripristinare solo il lavoro incompleto. Per un nuovo giorno eliminare la bozza. Ricontrollare misure e verifiche.|Restaure solo trabajos pendientes. Para otro día, borre el borrador. Revise mediciones y comprobaciones.|استعد المسودة لمتابعة العمل غير المكتمل فقط. ليوم جديد احذفها وأعد مراجعة القياسات والتحقق.|Restaure apenas trabalho inacabado. Para outro dia, apague o rascunho. Confira medições e verificações.|Восстанавливайте только незавершённую работу. Для нового дня удалите черновик. Проверьте измерения и подтверждения.
usage|도면·출력본 저장 용량|Drawing and output storage|Speicher für Pläne und Ausgaben|図面・出力の保存容量|Stockage des plans et sorties|Spazio per disegni e documenti|Almacenamiento de planos y documentos|تخزين الرسومات والمخرجات|Armazenamento de desenhos e saídas|Хранилище чертежей и выпусков
unlinked|등록되지 않은 업로드|Unregistered uploads|Nicht registrierte Uploads|未登録のアップロード|Téléversements non enregistrés|Caricamenti non registrati|Archivos subidos sin registrar|ملفات مرفوعة غير مسجلة|Uploads não registrados|Незарегистрированные загрузки
usageHelp|비공개 JSA 3개 한도와 별개인 파일 사용량입니다. 등록되지 않은 파일은 정상 보관본을 확인한 뒤 운영자가 정리합니다.|File usage is separate from the three-private-JSA limit. Operators review unregistered uploads before cleanup.|Dateispeicher ist unabhängig vom Limit von drei privaten JSA. Nicht registrierte Uploads werden vor der Bereinigung geprüft.|ファイル容量は非公開JSAの3件制限とは別です。未登録ファイルは管理者が確認して整理します。|Stockage distinct de la limite de trois JSA privées. L’opérateur examine les fichiers non enregistrés avant nettoyage.|Lo spazio file è distinto dal limite di tre JSA private. I file non registrati vengono verificati prima della pulizia.|El espacio es independiente del límite de tres JSA privadas. Se revisan los archivos sin registrar antes de limpiarlos.|الاستخدام منفصل عن حد ثلاثة تقييمات خاصة. يراجع المشغّل الملفات غير المسجلة قبل تنظيفها.|O espaço é separado do limite de três JSA privadas. Arquivos não registrados são revisados antes da limpeza.|Объём файлов не связан с лимитом трёх частных JSA. Незарегистрированные файлы проверяются перед очисткой.
usageError|파일 사용량을 불러오지 못했습니다.|File usage could not be loaded.|Speichernutzung konnte nicht geladen werden.|使用量を取得できませんでした。|Impossible de charger l’utilisation.|Impossibile caricare l’utilizzo.|No se pudo cargar el uso.|تعذّر تحميل الاستخدام.|Não foi possível carregar o uso.|Не удалось загрузить объём использования.
openPdf|PDF 새 창으로 열기|Open PDF in a new tab|PDF in neuem Tab öffnen|PDFを新しいタブで開く|Ouvrir le PDF dans un nouvel onglet|Apri PDF in una nuova scheda|Abrir PDF en otra pestaña|فتح PDF في علامة تبويب جديدة|Abrir PDF em outra aba|Открыть PDF в новой вкладке
pdfHelp|미리보기가 비어 있으면 PDF를 새 창에서 열거나 다운로드하세요.|If the preview is blank, open the PDF in a new tab or download it.|Bei leerer Vorschau PDF in neuem Tab öffnen oder herunterladen.|プレビューが空の場合は新しいタブで開くかダウンロードしてください。|Si l’aperçu est vide, ouvrez le PDF dans un autre onglet ou téléchargez-le.|Se l’anteprima è vuota, apri in un’altra scheda o scarica il PDF.|Si no aparece la vista previa, abra el PDF en otra pestaña o descárguelo.|إذا كانت المعاينة فارغة، افتح PDF في علامة تبويب جديدة أو نزّله.|Se a prévia estiver vazia, abra em outra aba ou baixe o PDF.|Если предпросмотр пуст, откройте PDF в новой вкладке или скачайте его.
`;
export const WORK_RECOVERY_TEXT = Object.fromEntries(rows.trim().split('\n').map(row => {
  const [key, ...values] = row.split('|');
  if (values.length !== languages.length || values.some(v => !v)) throw Error(`Missing recovery translation: ${key}`);
  return [key, Object.fromEntries(languages.map((lang, i) => [lang, values[i]]))];
}));
export const recoveryUi = locale => Object.fromEntries(Object.entries(WORK_RECOVERY_TEXT).map(([key, values]) => [key, values[locale.split('-')[0]] || values.en]));
