// key | de | ja | fr | it | es | ar | pt | ru
const languages = ['de','ja','fr','it','es','ar','pt','ru'];
export const workPackageTranslations = Object.fromEntries(languages.map(l => [l, {}]));
const rows = `
intro|Unterlagen für wiederkehrende Arbeiten vorbereiten, aktuelle Angaben ergänzen und gemeinsam drucken.|繰り返す作業の書類を準備し、当日の情報を入力してまとめて印刷します。|Préparez les documents récurrents, renseignez les données du jour et imprimez l’ensemble.|Preparate i documenti ricorrenti, inserite i dati del giorno e stampate insieme.|Prepare documentos recurrentes, introduzca los datos del día e imprima el conjunto.|جهّز مستندات الأعمال المتكررة وأدخل بيانات اليوم ثم اطبعها معاً.|Prepare documentos recorrentes, informe os dados do dia e imprima o conjunto.|Подготовьте документы для повторных работ, внесите данные на сегодня и распечатайте комплект.
workflow|Ablauf der Dokumentenpakete|書類セットの使い方|Utilisation des dossiers|Uso dei pacchetti|Uso de los paquetes|طريقة استخدام الحزم|Como usar os pacotes|Порядок работы с комплектами
prepareTitle|Paket vorbereiten|書類セットを準備|Préparer un dossier|Preparare un pacchetto|Preparar paquete|إعداد الحزمة|Preparar pacote|Подготовить комплект
prepareHelp|Dokumente wählen, ordnen und wiederverwendbare Inhalte speichern.|書類を選び、順序と再利用する内容を保存します。|Choisissez et ordonnez les documents, puis enregistrez le contenu réutilisable.|Scegliete e ordinate i documenti, poi salvate i contenuti riutilizzabili.|Elija y ordene documentos y guarde el contenido reutilizable.|اختر المستندات ورتبها واحفظ المحتوى القابل لإعادة الاستخدام.|Escolha e ordene documentos e salve o conteúdo reutilizável.|Выберите и упорядочьте документы, сохраните повторно используемые сведения.
fillTitle|Aktuelle Arbeitsdaten eingeben|今回の作業情報を入力|Renseigner le travail du jour|Inserire i dati del lavoro|Introducir datos del trabajo|إدخال بيانات العمل الحالي|Informar dados do trabalho|Внести данные текущих работ
fillHelp|Gespeichertes Paket öffnen und Datum, Personal und Ergebnisse eintragen.|保存したセットを開き、日付・作業者・現場結果を入力します。|Ouvrez un dossier enregistré et renseignez date, travailleurs et résultats.|Aprite un pacchetto e indicate data, lavoratori e risultati.|Abra un paquete e indique fecha, trabajadores y resultados.|افتح حزمة محفوظة وأدخل التاريخ والعاملين والنتائج.|Abra um pacote e informe data, trabalhadores e resultados.|Откройте комплект, укажите дату, работников и результаты.
outputTitle|Prüfen und ausgeben|確認して出力|Vérifier et produire|Verificare e produrre|Revisar y generar|المراجعة والإخراج|Revisar e gerar|Проверить и вывести
outputHelp|Vorschau prüfen. PDF speichern oder drucken; eine Kopie wird archiviert.|プレビューを確認しPDF保存または印刷します。出力本も保管されます。|Vérifiez l’aperçu, puis enregistrez ou imprimez le PDF. Une copie est archivée.|Verificate l’anteprima e salvate o stampate il PDF. Una copia viene archiviata.|Revise la vista previa y guarde o imprima el PDF. Se archiva una copia.|راجع المعاينة ثم احفظ PDF أو اطبعه. تُؤرشف نسخة.|Revise a prévia e salve ou imprima o PDF. Uma cópia é arquivada.|Проверьте просмотр, сохраните PDF или распечатайте. Копия архивируется.
packagesHelp|Wiederverwendbare Dokumentensätze zum Bearbeiten oder für eine neue Ausgabe.|編集や新しい作業の出力に使う、再利用可能な書類セットです。|Dossiers réutilisables à modifier ou à utiliser pour une nouvelle sortie.|Pacchetti riutilizzabili da modificare o usare per una nuova uscita.|Conjuntos reutilizables para editar o generar una nueva salida.|مجموعات قابلة لإعادة الاستخدام للتحرير أو لإخراج جديد.|Conjuntos reutilizáveis para editar ou gerar nova saída.|Повторно используемые комплекты для редактирования и нового выпуска.
drawingsHelp|Originale hochladen und zu Paketen hinzufügen. Markierungen gehören zum jeweiligen Paket.|原図を登録してセットに追加します。書込みはセットごとに保存します。|Importez les originaux puis ajoutez-les aux dossiers. Les annotations appartiennent au dossier.|Caricate gli originali e aggiungeteli ai pacchetti. Le annotazioni appartengono al pacchetto.|Suba originales y añádalos a paquetes. Las anotaciones pertenecen a cada paquete.|ارفع الأصول وأضفها للحزم. ترتبط التعليقات بكل حزمة.|Envie originais e adicione aos pacotes. As anotações pertencem a cada pacote.|Загрузите оригиналы и добавьте в комплекты. Пометки принадлежат конкретному комплекту.
templatesHelp|Einzelformulare aus dem Editor speichern und in anderen Paketen nutzen.|編集画面で保存した個人様式を他のセットでも利用できます。|Formulaires personnels enregistrés dans l’éditeur et réutilisables dans d’autres dossiers.|Moduli personali salvati nell’editor e riutilizzabili in altri pacchetti.|Formularios personales guardados en el editor y reutilizables en otros paquetes.|نماذج شخصية محفوظة من المحرر وقابلة للاستخدام في حزم أخرى.|Formulários pessoais salvos no editor e reutilizáveis em outros pacotes.|Личные формы из редактора для повторного использования в других комплектах.
outputsHelp|Archivierte PDFs und Eingaben. Für neue Arbeiten das Paket erneut verwenden.|保管済みPDFと入力記録です。次の作業には書類セットを使用します。|PDF et données archivés. Réutilisez le dossier pour un nouveau travail.|PDF e dati archiviati. Usate il pacchetto per un nuovo lavoro.|PDF y datos archivados. Use el paquete para un nuevo trabajo.|ملفات PDF وبيانات مؤرشفة. استخدم الحزمة لعمل جديد.|PDFs e dados arquivados. Use o pacote para um novo trabalho.|Архивные PDF и введённые данные. Для новых работ используйте комплект.
packagesEmpty|Erstes Dokumentenpaket erstellen|最初の書類セットを作成|Créer votre premier dossier|Creare il primo pacchetto|Crear el primer paquete|إنشاء أول حزمة|Criar o primeiro pacote|Создайте первый комплект
packagesEmptyHelp|Land und Vorlagen wählen. JSA und Zeichnungen nach Bedarf ergänzen.|作業国と様式を選び、必要なJSAと図面を追加してください。|Choisissez le pays et les modèles, puis ajoutez JSA et plans si nécessaire.|Scegliete paese e modelli, poi aggiungete JSA e disegni secondo necessità.|Elija país y modelos y añada JSA y planos según necesite.|اختر البلد والنماذج وأضف تحليل العمل والمخططات حسب الحاجة.|Escolha país e modelos e adicione JSA e desenhos conforme necessário.|Выберите страну и формы, при необходимости добавьте JSA и чертежи.
drawingsEmpty|Noch keine Zeichnungen|図面は未登録です|Aucun plan importé|Nessun disegno caricato|No hay planos cargados|لا توجد مخططات مرفوعة|Nenhum desenho enviado|Чертежи не загружены
drawingsEmptyHelp|Original hochladen; es kann in mehreren Paketen verwendet werden.|原図を登録すると複数のセットで利用できます。|Importez un original pour le réutiliser dans plusieurs dossiers.|Caricate un originale da riutilizzare in più pacchetti.|Suba un original para usarlo en varios paquetes.|ارفع أصلاً لاستخدامه في عدة حزم.|Envie um original para usar em vários pacotes.|Загрузите оригинал для использования в нескольких комплектах.
templatesEmpty|Noch keine persönlichen Vorlagen|個人様式は未保存です|Aucun modèle personnel|Nessun modello personale|No hay modelos personales|لا توجد نماذج شخصية|Nenhum modelo pessoal|Личных форм пока нет
templatesEmptyHelp|Dokument im Paket auswählen und als persönliche Vorlage speichern.|セット内の文書を選び、個人様式として保存してください。|Sélectionnez un document du dossier et enregistrez-le comme modèle personnel.|Selezionate un documento e salvatelo come modello personale.|Seleccione un documento y guárdelo como modelo personal.|اختر مستنداً واحفظه كنموذج شخصي.|Selecione um documento e salve como modelo pessoal.|Выберите документ и сохраните как личную форму.
outputsEmpty|Noch keine Ausgaben gespeichert|出力本は未保存です|Aucune sortie enregistrée|Nessuna uscita salvata|No hay salidas guardadas|لا توجد مخرجات محفوظة|Nenhuma saída salva|Сохранённых выпусков нет
outputsEmptyHelp|Paket speichern, Arbeitsdaten eintragen und PDF speichern oder drucken.|セットを保存し作業情報を入力して、PDF保存または印刷してください。|Enregistrez le dossier, renseignez le travail puis générez ou imprimez le PDF.|Salvate il pacchetto, compilate i dati e generate o stampate il PDF.|Guarde el paquete, complete los datos y genere o imprima el PDF.|احفظ الحزمة وأكمل البيانات ثم أنشئ PDF أو اطبعه.|Salve o pacote, preencha os dados e gere ou imprima o PDF.|Сохраните комплект, заполните данные и сформируйте PDF или распечатайте.
packageName|Paketname|セット名|Nom du dossier|Nome del pacchetto|Nombre del paquete|اسم الحزمة|Nome do pacote|Название комплекта
packageNameHint|z. B. Pumpenwartung|例：ポンプ保守書類|Ex. entretien de pompe|Es. manutenzione pompa|Ej. mantenimiento de bomba|مثال: صيانة المضخة|Ex.: manutenção de bomba|Например: обслуживание насоса
versionHint|z. B. ver.1 oder Nachtschicht|例：ver.1、夜間作業用|Ex. ver.1 ou travail de nuit|Es. ver.1 o turno notturno|Ej. ver.1 o turno nocturno|مثال: ver.1 أو الوردية الليلية|Ex.: ver.1 ou turno noturno|Например: ver.1 или ночная смена
basicTitle|Paketangaben|セットの基本情報|Informations du dossier|Dati del pacchetto|Datos del paquete|بيانات الحزمة|Dados do pacote|Данные комплекта
basicHelp|Gemeinsame Vorgaben speichern. Datum, Personal und Messungen je Arbeit ergänzen.|共通の初期値を保存します。日付・作業者・測定値は作業ごとに入力します。|Enregistrez les valeurs communes. Date, travailleurs et mesures sont saisis pour chaque travail.|Salvate i valori comuni. Data, lavoratori e misure si compilano per ogni lavoro.|Guarde valores comunes. Fecha, trabajadores y mediciones se completan en cada trabajo.|احفظ القيم المشتركة. أدخل التاريخ والعاملين والقياسات لكل عمل.|Salve valores comuns. Data, trabalhadores e medições são preenchidos em cada trabalho.|Сохраните общие значения. Даты, работников и измерения вводите для каждых работ.
addTitle|Dokumente und Zeichnungen hinzufügen|書類と図面を追加|Ajouter documents et plans|Aggiungere documenti e disegni|Añadir documentos y planos|إضافة المستندات والمخططات|Adicionar documentos e desenhos|Добавить документы и чертежи
addHelp|Benötigte Unterlagen ergänzen und unten die Druckreihenfolge festlegen.|必要な様式と資料を追加し、下で出力順序を設定してください。|Ajoutez les documents nécessaires et définissez leur ordre ci-dessous.|Aggiungete i documenti necessari e ordinate l’uscita qui sotto.|Añada documentos y defina el orden de salida abajo.|أضف المستندات وحدد ترتيب الإخراج أدناه.|Adicione documentos e defina a ordem de saída abaixo.|Добавьте документы и задайте ниже порядок вывода.
blankForms|Leeres Formular hinzufügen|空の様式を追加|Ajouter un formulaire vide|Aggiungere un modulo vuoto|Añadir formulario vacío|إضافة نموذج فارغ|Adicionar formulário vazio|Добавить пустую форму
savedMaterials|Gespeicherte Unterlagen hinzufügen|保存済み資料を追加|Ajouter des éléments enregistrés|Aggiungere materiali salvati|Añadir materiales guardados|إضافة مواد محفوظة|Adicionar materiais salvos|Добавить сохранённые материалы
noJsa|Keine gespeicherte JSA verfügbar|保存済みJSAがありません|Aucune JSA enregistrée|Nessuna JSA salvata|No hay JSA guardada|لا يوجد تحليل عمل محفوظ|Nenhuma JSA salva|Нет сохранённых JSA
noTemplates|Keine persönlichen Vorlagen gespeichert|保存済み個人様式がありません|Aucun modèle personnel enregistré|Nessun modello personale salvato|No hay modelos personales guardados|لا توجد نماذج شخصية محفوظة|Nenhum modelo pessoal salvo|Нет сохранённых личных форм
noDrawings|Zuerst unten eine Zeichnung hochladen|先に下から図面を登録してください|Importez d’abord un plan ci-dessous|Caricare prima un disegno qui sotto|Suba primero un plano abajo|ارفع مخططاً أولاً أدناه|Envie primeiro um desenho abaixo|Сначала загрузите чертёж ниже
orderTitle|Dokumente und Ausgabereihenfolge|書類と出力順序|Documents et ordre de sortie|Documenti e ordine di uscita|Documentos y orden de salida|المستندات وترتيب الإخراج|Documentos e ordem de saída|Документы и порядок вывода
orderHelp|Dokument zum Bearbeiten wählen. Verschieben oder vom Druck ausschließen.|書類を選んで編集し、上下移動や出力対象の変更ができます。|Choisissez un document à modifier, déplacez-le ou excluez-le de l’impression.|Scegliete un documento, spostatelo o escludetelo dalla stampa.|Elija un documento, muévalo o exclúyalo de la impresión.|اختر مستنداً لتحريره أو نقله أو استبعاده من الطباعة.|Escolha um documento, mova-o ou exclua-o da impressão.|Выберите документ для правки, переместите или исключите из печати.
editTitle|Ausgewähltes Dokument bearbeiten|選択した書類を編集|Modifier le document sélectionné|Modificare il documento selezionato|Editar documento seleccionado|تحرير المستند المحدد|Editar documento selecionado|Редактировать выбранный документ
editHelp|Wiederverwendung, Eingabe je Arbeit oder handschriftliches Leerfeld wählen.|再利用・作業ごとの入力・手書き空欄を指定してください。|Choisissez contenu réutilisable, saisie par travail ou espace manuscrit.|Scegliete contenuti riutilizzabili, dati per lavoro o spazi manoscritti.|Elija contenido reutilizable, datos por trabajo o espacios manuscritos.|اختر محتوى قابلاً لإعادة الاستخدام أو إدخالاً لكل عمل أو فراغاً للكتابة.|Escolha conteúdo reutilizável, dados por trabalho ou espaços manuscritos.|Выберите повторные сведения, ввод для текущих работ или поле для записи от руки.
selectDocument|Dokument aus der Liste wählen oder oben hinzufügen.|一覧から書類を選ぶか、上で追加してください。|Choisissez un document dans la liste ou ajoutez-en un.|Scegliete un documento dall’elenco o aggiungetelo.|Elija un documento de la lista o añada uno.|اختر مستنداً من القائمة أو أضف واحداً.|Escolha um documento da lista ou adicione um.|Выберите документ из списка или добавьте новый.
orientation|Seitenausrichtung|用紙の向き|Orientation de la page|Orientamento pagina|Orientación de página|اتجاه الصفحة|Orientação da página|Ориентация страницы
fieldKind|Informationsart|情報の種類|Type d’information|Tipo di informazione|Tipo de información|نوع المعلومات|Tipo de informação|Тип сведений
fieldMode|Zeitpunkt der Eingabe|入力するタイミング|Moment de saisie|Quando compilare|Cuándo completar|وقت التعبئة|Quando preencher|Когда заполнять
fieldModeHelp|Standard: jetzt speichern. Je Arbeit: im nächsten Schritt ausfüllen. Leerfeld: auf Papier schreiben.|標準値はここで保存、当日値は次の画面で入力、手書き項目は空欄で印刷します。|Standard : enregistrer maintenant. Par travail : saisir à l’étape suivante. Vide : écrire sur papier.|Standard: salvare ora. Per lavoro: compilare dopo. Vuoto: scrivere su carta.|Estándar: guardar ahora. Por trabajo: completar después. Vacío: escribir en papel.|قياسي: احفظ الآن. لكل عمل: أدخل لاحقاً. فارغ: اكتب على الورق.|Padrão: salvar agora. Por trabalho: preencher depois. Vazio: escrever no papel.|Стандарт: сохранить сейчас. Для работ: заполнить далее. Пустое: записать на бумаге.
savePackage|Paket speichern|セットを保存|Enregistrer le dossier|Salvare pacchetto|Guardar paquete|حفظ الحزمة|Salvar pacote|Сохранить комплект
continueWork|Arbeitsdaten eingeben →|作業情報を入力 →|Renseigner le travail →|Inserire dati del lavoro →|Introducir datos →|إدخال بيانات العمل ←|Informar dados →|Внести данные работ →
backPackages|Zurück zu Paketen|セット一覧に戻る|Retour aux dossiers|Torna ai pacchetti|Volver a paquetes|العودة للحزم|Voltar aos pacotes|К списку комплектов
backEditor|Zurück zum Paketeditor|セット編集に戻る|Retour à l’édition du dossier|Torna all’editor|Volver al editor|العودة للمحرر|Voltar ao editor|К редактированию комплекта
readyHelp|Paket gespeichert. Neue Arbeitsdaten eingeben oder eine unabhängige Variante speichern.|セットを保存しました。作業情報の入力や独立した複製の保存ができます。|Dossier enregistré. Saisissez un nouveau travail ou enregistrez une variante indépendante.|Pacchetto salvato. Inserite un nuovo lavoro o salvate una variante indipendente.|Paquete guardado. Introduzca un nuevo trabajo o guarde una variante independiente.|تم حفظ الحزمة. أدخل بيانات عمل جديد أو احفظ نسخة مستقلة.|Pacote salvo. Informe novo trabalho ou salve uma variante independente.|Комплект сохранён. Внесите новые данные или сохраните независимый вариант.
inputsHelp|Gemeinsame Angaben gelten für alle gewählten Dokumente. Weitere Felder unten ausfüllen.|共通情報は選択した書類に反映されます。残りの項目を下で入力してください。|Les données communes s’appliquent aux documents sélectionnés. Complétez les autres champs ci-dessous.|I dati comuni si applicano ai documenti selezionati. Compilate gli altri campi sotto.|Los datos comunes se aplican a los documentos seleccionados. Complete los demás campos abajo.|تُطبق البيانات المشتركة على المستندات المحددة. أكمل الحقول الأخرى أدناه.|Os dados comuns se aplicam aos documentos selecionados. Complete os demais campos abaixo.|Общие данные используются во всех выбранных документах. Заполните остальные поля ниже.
previewHelp|Dokumente und Zeichnungsmarkierungen prüfen. Ausgabe wird beim Speichern oder Drucken archiviert.|書類と図面の書込みを確認してください。保存・印刷時に出力本を保管します。|Vérifiez documents et annotations. La sortie est archivée lors de l’enregistrement ou de l’impression.|Verificate documenti e annotazioni. L’uscita viene archiviata al salvataggio o alla stampa.|Revise documentos y anotaciones. La salida se archiva al guardar o imprimir.|راجع المستندات والتعليقات. يُؤرشف الإخراج عند الحفظ أو الطباعة.|Revise documentos e anotações. A saída é arquivada ao salvar ou imprimir.|Проверьте документы и пометки. При сохранении или печати выпуск архивируется.
noDocuments|Mindestens ein Dokument auswählen.|出力する書類を1つ以上選んでください。|Sélectionnez au moins un document.|Selezionare almeno un documento.|Seleccione al menos un documento.|اختر مستنداً واحداً على الأقل.|Selecione ao menos um documento.|Выберите хотя бы один документ.
textSize|Text- / Markierungsgröße|文字・マーカーサイズ|Taille du texte / repère|Dimensione testo / marcatore|Tamaño de texto / marcador|حجم النص / العلامة|Tamanho de texto / marcador|Размер текста / метки
title|Arbeitsdokumentenpakete|作業別書類セット|Dossiers de travail|Pacchetti di documenti di lavoro|Paquetes de documentos de trabajo|حزم مستندات العمل|Pacotes de documentos de trabalho|Комплекты рабочих документов
packages|Pakete|書類セット|Dossiers|Pacchetti|Paquetes|الحزم|Pacotes|Комплекты
drawings|Zeichnungsbibliothek|図面保管庫|Bibliothèque de plans|Archivio disegni|Biblioteca de planos|مكتبة المخططات|Biblioteca de desenhos|Библиотека чертежей
templates|Meine Formularvorlagen|個人様式|Mes modèles|I miei modelli|Mis modelos|نماذجي|Meus modelos|Мои формы
outputs|Gespeicherte Ausgaben|保管済み出力本|Sorties enregistrées|Uscite salvate|Salidas guardadas|المخرجات المحفوظة|Saídas salvas|Сохранённые выпуски
create|Neues Paket|新しいセット|Nouveau dossier|Nuovo pacchetto|Nuevo paquete|حزمة جديدة|Novo pacote|Новый комплект
name|Name|名称|Nom|Nome|Nombre|الاسم|Nome|Название
version|Versionsname|バージョン名|Nom de version|Nome versione|Nombre de versión|اسم الإصدار|Nome da versão|Название версии
save|Speichern|保存|Enregistrer|Salva|Guardar|حفظ|Salvar|Сохранить
copy|Unabhängige Kopie speichern|独立した複製を保存|Enregistrer une copie indépendante|Salvare copia indipendente|Guardar copia independiente|حفظ نسخة مستقلة|Salvar cópia independente|Сохранить независимую копию
open|Öffnen|開く|Ouvrir|Apri|Abrir|فتح|Abrir|Открыть
back|Zurück|戻る|Retour|Indietro|Volver|رجوع|Voltar|Назад
add|Hinzufügen|追加|Ajouter|Aggiungi|Añadir|إضافة|Adicionar|Добавить
remove|Entfernen|削除|Retirer|Rimuovi|Quitar|إزالة|Remover|Удалить
up|Nach oben|上へ|Monter|Sposta su|Subir|نقل لأعلى|Subir|Выше
down|Nach unten|下へ|Descendre|Sposta giù|Bajar|نقل لأسفل|Descer|Ниже
start|Neuen Arbeitsnachweis beginnen|新しい作業記録を開始|Commencer un nouveau travail|Iniziare nuovo lavoro|Iniciar nuevo trabajo|بدء سجل عمل جديد|Iniciar novo trabalho|Начать новую запись работ
common|Gemeinsame Angaben|共通情報|Informations communes|Informazioni comuni|Información común|المعلومات المشتركة|Informações comuns|Общие сведения
projectName|Arbeitsbezeichnung|作業名|Nom du travail|Nome del lavoro|Nombre del trabajo|اسم العمل|Nome do trabalho|Наименование работ
workLocation|Arbeitsort|作業場所|Lieu de travail|Luogo di lavoro|Lugar de trabajo|موقع العمل|Local de trabalho|Место работ
department|Abteilung|部署|Service|Reparto|Departamento|القسم|Departamento|Подразделение
workDate|Arbeitsdatum / Uhrzeit|作業日時|Date / heure du travail|Data / ora del lavoro|Fecha / hora del trabajo|تاريخ / وقت العمل|Data / hora do trabalho|Дата / время работ
manager|Verantwortliche Person|担当者|Responsable|Responsabile|Responsable|المسؤول|Responsável|Ответственный
workers|Beschäftigte (eine Person pro Zeile)|作業者（1行に1名）|Travailleurs (un par ligne)|Lavoratori (uno per riga)|Trabajadores (uno por línea)|العاملون (واحد في كل سطر)|Trabalhadores (um por linha)|Работники (по одному в строке)
defaults|Wiederverwendbare Vorgaben|再利用する初期値|Valeurs réutilisables|Valori riutilizzabili|Valores reutilizables|قيم قابلة لإعادة الاستخدام|Valores reutilizáveis|Повторно используемые значения
jsa|JSA / Gefährdungsbeurteilung|JSA・リスクアセスメント|JSA / évaluation des risques|JSA / valutazione dei rischi|JSA / evaluación de riesgos|تحليل سلامة العمل / تقييم المخاطر|JSA / avaliação de riscos|JSA / оценка рисков
ptw|Arbeitserlaubnis|作業許可書|Permis de travail|Permesso di lavoro|Permiso de trabajo|تصريح العمل الآمن|Permissão de trabalho|Наряд-допуск
tbm|Sicherheitsbesprechung|作業前安全ミーティング|Causerie sécurité|Riunione di sicurezza|Charla de seguridad|اجتماع السلامة|Diálogo de segurança|Предсменный инструктаж
checklist|Sicherheitscheckliste|安全点検表|Liste de contrôle de sécurité|Lista di controllo sicurezza|Lista de seguridad|قائمة فحص السلامة|Lista de segurança|Контрольный лист безопасности
custom|Eigenes Formular|独自様式|Formulaire personnalisé|Modulo personalizzato|Formulario personalizado|نموذج مخصص|Formulário personalizado|Своя форма
importJsa|Aus meiner JSA-Bibliothek übernehmen|自分のJSAから取り込む|Importer depuis mes JSA|Importare dalle mie JSA|Importar de mis JSA|استيراد من مكتبة تحليل العمل|Importar das minhas JSA|Импортировать из моих JSA
layout|Gespeichertes JSA-Layout|保存済みJSAレイアウト|Mise en page JSA enregistrée|Layout JSA salvato|Diseño JSA guardado|تخطيط تحليل العمل المحفوظ|Layout JSA salvo|Сохранённый макет JSA
field|Eingabefeld|入力欄|Champ de saisie|Campo di inserimento|Campo de entrada|حقل إدخال|Campo de entrada|Поле ввода
table|Tabelle|表|Tableau|Tabella|Tabla|جدول|Tabela|Таблица
row|Zeile|行|Ligne|Riga|Fila|صف|Linha|Строка
column|Spalte|列|Colonne|Colonna|Columna|عمود|Coluna|Столбец
label|Beschriftung|項目名|Libellé|Etichetta|Etiqueta|التسمية|Rótulo|Подпись поля
standard|Wiederverwendbarer Standard|再利用する標準値|Valeur standard réutilisable|Valore standard riutilizzabile|Valor estándar reutilizable|قيمة قياسية قابلة لإعادة الاستخدام|Valor padrão reutilizável|Повторно используемый стандарт
runtime|Für diese Arbeit eingeben|今回の作業で入力|Saisir pour ce travail|Compilare per questo lavoro|Completar para este trabajo|إدخال لهذا العمل|Preencher neste trabalho|Ввести для этих работ
blank|Handschriftliches Leerfeld|手書き用空欄|Espace manuscrit|Spazio manoscritto|Espacio manuscrito|فراغ للكتابة اليدوية|Espaço manuscrito|Поле для записи от руки
text|Text|文字|Texte|Testo|Texto|نص|Texto|Текст
date|Datum / Uhrzeit|日時|Date / heure|Data / ora|Fecha / hora|التاريخ / الوقت|Data / hora|Дата / время
worker|Beschäftigte Person|作業者|Travailleur|Lavoratore|Trabajador|العامل|Trabalhador|Работник
measurement|Messwert|実測値|Valeur mesurée|Valore misurato|Valor medido|القيمة المقاسة|Valor medido|Измеренное значение
measuredAt|Messzeitpunkt|測定時刻|Heure de mesure|Ora della misura|Hora de medición|وقت القياس|Horário da medição|Время измерения
measuredBy|Messende Person|測定者|Personne ayant mesuré|Addetto alla misura|Persona que mide|القائم بالقياس|Responsável pela medição|Проводивший измерение
verification|Prüfung vor Ort|現場確認|Vérification sur site|Verifica sul posto|Verificación en el lugar|التحقق بالموقع|Verificação no local|Проверка на месте
workScope|Arbeitsumfang|作業範囲|Périmètre des travaux|Ambito dei lavori|Alcance del trabajo|نطاق العمل|Escopo do trabalho|Объём работ
precautions|Gefährdungen und Maßnahmen|危険要因・安全対策|Dangers et précautions|Pericoli e precauzioni|Peligros y precauciones|المخاطر والاحتياطات|Perigos e precauções|Опасности и меры защиты
attendee|Teilnehmende Person|参加者|Participant|Partecipante|Participante|المشارك|Participante|Участник
signature|Unterschrift|署名|Signature|Firma|Firma|التوقيع|Assinatura|Подпись
checkItem|Prüfpunkt|点検項目|Point de contrôle|Punto di controllo|Punto de inspección|بند الفحص|Item de inspeção|Пункт проверки
result|Ergebnis|結果|Résultat|Risultato|Resultado|النتيجة|Resultado|Результат
remark|Bemerkungen|備考|Remarques|Note|Observaciones|ملاحظات|Observações|Примечания
fieldConfirmation|Bestätigung vor Ort|現場での確認|Confirmation sur site|Conferma sul posto|Confirmación en el lugar|تأكيد بالموقع|Confirmação no local|Подтверждение на месте
upload|Neues Original hochladen|新しい原図を登録|Importer un nouvel original|Caricare nuovo originale|Subir nuevo original|رفع أصل جديد|Enviar novo original|Загрузить новый оригинал
number|Zeichnungsnummer|図面番号|Numéro du plan|Numero disegno|Número de plano|رقم المخطط|Número do desenho|Номер чертежа
revision|Zeichnungsrevision|図面改訂番号|Révision du plan|Revisione disegno|Revisión del plano|مراجعة المخطط|Revisão do desenho|Редакция чертежа
fileHelp|PDF / PNG / JPG, bis 20 MB und 200 Seiten. Private Originale werden nicht überschrieben.|PDF・PNG・JPG、20MB・200ページまで。非公開の原図は上書きされません。|PDF / PNG / JPG, 20 Mo et 200 pages maximum. Les originaux privés ne sont pas écrasés.|PDF / PNG / JPG, massimo 20 MB e 200 pagine. Gli originali privati non vengono sovrascritti.|PDF / PNG / JPG, hasta 20 MB y 200 páginas. No se sobrescriben los originales privados.|PDF / PNG / JPG بحد 20 ميغابايت و200 صفحة. لا تُستبدل الأصول الخاصة.|PDF / PNG / JPG, até 20 MB e 200 páginas. Os originais privados não são sobrescritos.|PDF / PNG / JPG, до 20 МБ и 200 страниц. Личные оригиналы не перезаписываются.
pages|Einzubeziehende Seiten|含めるページ|Pages à inclure|Pagine da includere|Páginas a incluir|الصفحات المضمنة|Páginas a incluir|Включаемые страницы
replace|Durch anderes Original ersetzen|別の原図に差し替え|Remplacer par un autre original|Sostituire con altro originale|Sustituir por otro original|استبدال بأصل آخر|Substituir por outro original|Заменить другим оригиналом
review|Nach dem Austausch die Markierungen auf allen gewählten Seiten prüfen.|差し替え後、選択した全ページの書込み位置を確認してください。|Après remplacement, vérifiez les annotations de chaque page choisie.|Dopo la sostituzione, verificate le annotazioni su ogni pagina scelta.|Tras sustituir, revise las anotaciones de todas las páginas seleccionadas.|بعد الاستبدال تحقق من التعليقات في جميع الصفحات المحددة.|Após substituir, confira as anotações em todas as páginas selecionadas.|После замены проверьте пометки на всех выбранных страницах.
reviewed|Positionen der Markierungen geprüft|書込み位置を確認しました|J’ai vérifié les annotations|Ho verificato le annotazioni|He revisado las anotaciones|تحققت من مواضع التعليقات|Conferi as anotações|Положение пометок проверено
annotations|Zeichnungsmarkierungen|図面への書込み|Annotations du plan|Annotazioni del disegno|Anotaciones del plano|تعليقات المخطط|Anotações do desenho|Пометки на чертеже
select|Auswählen / verschieben|選択・移動|Sélectionner / déplacer|Seleziona / sposta|Seleccionar / mover|تحديد / نقل|Selecionar / mover|Выбрать / переместить
free|Freihand|自由線|Main levée|Mano libera|Trazo libre|رسم حر|Traço livre|Свободная линия
line|Linie|直線|Ligne|Linea|Línea|خط|Linha|Линия
arrow|Pfeil|矢印|Flèche|Freccia|Flecha|سهم|Seta|Стрелка
rect|Rechteck|長方形|Rectangle|Rettangolo|Rectángulo|مستطيل|Retângulo|Прямоугольник
circle|Ellipse|楕円|Ellipse|Ellisse|Elipse|شكل بيضاوي|Elipse|Эллипс
zone|Bereich|区域|Zone|Area|Zona|منطقة|Área|Область
marker|Nummernmarkierung|番号マーカー|Repère numéroté|Marcatore numerato|Marcador numerado|علامة مرقمة|Marcador numerado|Номерная метка
color|Farbe|色|Couleur|Colore|Color|اللون|Cor|Цвет
width|Linienstärke|線の太さ|Épaisseur du trait|Spessore linea|Grosor de línea|سمك الخط|Espessura da linha|Толщина линии
opacity|Deckkraft|不透明度|Opacité|Opacità|Opacidad|التعتيم|Opacidade|Непрозрачность
undo|Rückgängig|元に戻す|Annuler|Annulla|Deshacer|تراجع|Desfazer|Отменить
redo|Wiederholen|やり直し|Rétablir|Ripeti|Rehacer|إعادة|Refazer|Повторить
zoom|Zoom|拡大・縮小|Zoom|Zoom|Zoom|تكبير|Zoom|Масштаб
resize|Ausgewählte Form skalieren|選択した図形のサイズ変更|Redimensionner la forme|Ridimensionare la forma|Cambiar tamaño de forma|تغيير حجم الشكل|Redimensionar forma|Изменить размер фигуры
preview|Gesamtvorschau|まとめてプレビュー|Aperçu d’ensemble|Anteprima completa|Vista previa conjunta|المعاينة المجمعة|Prévia conjunta|Общий просмотр
pdf|PDF speichern und archivieren|PDF保存・保管|Enregistrer le PDF et archiver|Salvare PDF e archiviare|Guardar PDF y archivar|حفظ PDF وأرشفته|Salvar PDF e arquivar|Сохранить PDF и архивировать
print|Drucken und archivieren|印刷・保管|Imprimer et archiver|Stampare e archiviare|Imprimir y archivar|الطباعة والأرشفة|Imprimir e arquivar|Распечатать и архивировать
download|Herunterladen|ダウンロード|Télécharger|Scarica|Descargar|تنزيل|Baixar|Скачать
snapshot|Arbeitsnachweis|作業記録|Enregistrement du travail|Registro del lavoro|Registro del trabajo|سجل العمل|Registro do trabalho|Запись работ
privateHelp|Pakete, Zeichnungen und Ausgaben bleiben privat, auch wenn eine JSA veröffentlicht wird.|JSAを公開しても、書類セット・図面・出力本は非公開のままです。|Dossiers, plans et sorties restent privés, même si une JSA est publiée.|Pacchetti, disegni e uscite restano privati anche pubblicando una JSA.|Paquetes, planos y salidas siguen privados aunque se publique una JSA.|تبقى الحزم والمخططات والمخرجات خاصة حتى عند نشر تحليل العمل.|Pacotes, desenhos e saídas permanecem privados mesmo ao publicar uma JSA.|Комплекты, чертежи и выпуски остаются личными даже при публикации JSA.
runtimeHelp|Jede neue Arbeit beginnt ohne frühere Daten, Personen, Messwerte und Prüfergebnisse.|新しい作業では過去の日付・作業者・測定値・確認結果を引き継ぎません。|Chaque nouveau travail commence sans reprendre les dates, personnes, mesures et vérifications précédentes.|Ogni nuovo lavoro parte senza date, persone, misure e verifiche precedenti.|Cada trabajo nuevo empieza sin fechas, personas, mediciones ni verificaciones anteriores.|يبدأ كل عمل جديد دون تواريخ أو عاملين أو قياسات أو تحققات سابقة.|Cada novo trabalho começa sem datas, pessoas, medições ou verificações anteriores.|Новые работы начинаются без прежних дат, работников, измерений и результатов проверок.
empty|Noch nichts gespeichert.|まだ保存されていません。|Rien d’enregistré.|Nessun elemento salvato.|No hay elementos guardados.|لا يوجد شيء محفوظ.|Nada salvo.|Пока ничего не сохранено.
error|Vorgang fehlgeschlagen. Änderungen bleiben erhalten. Erneut versuchen.|完了できませんでした。編集内容は保持されています。再試行してください。|Échec. Vos modifications sont conservées. Réessayez.|Operazione non riuscita. Le modifiche sono conservate. Riprovare.|No se pudo completar. Se conservan los cambios. Reintente.|تعذر الإكمال. تبقى التعديلات محفوظة على الشاشة. أعد المحاولة.|Não foi possível concluir. As alterações permanecem. Tente novamente.|Не удалось завершить. Изменения сохранены на экране. Повторите попытку.
saved|Gespeichert.|保存しました。|Enregistré.|Salvato.|Guardado.|تم الحفظ.|Salvo.|Сохранено.
loading|Wird geladen…|読み込み中…|Chargement…|Caricamento…|Cargando…|جار التحميل…|Carregando…|Загрузка…
login|Für den privaten Arbeitsbereich anmelden|ログインして個人スペースを利用|Connectez-vous à votre espace privé|Accedere allo spazio privato|Inicie sesión en su espacio privado|سجّل الدخول لمساحتك الخاصة|Entre no espaço privado|Войдите в личное пространство
conflict|Paket wurde anderswo geändert. Vor weiterer Bearbeitung neu laden.|他の場所で変更されました。保存済みセットを再読み込みしてください。|Dossier modifié ailleurs. Rechargez-le avant de continuer.|Pacchetto modificato altrove. Ricaricarlo prima di continuare.|Paquete modificado en otro lugar. Recárguelo antes de continuar.|عُدلت الحزمة في مكان آخر. أعد تحميلها قبل المتابعة.|Pacote alterado em outro local. Recarregue antes de continuar.|Комплект изменён в другом месте. Перезагрузите его перед правкой.
saveFirst|Paket benennen und speichern. Danach die Arbeitsdaten eingeben.|セット名を入力して保存し、その後に作業情報を入力してください。|Nommez et enregistrez le dossier, puis renseignez le travail.|Denominate e salvate il pacchetto, poi compilate il lavoro.|Nombre y guarde el paquete y después complete el trabajo.|سمّ الحزمة واحفظها ثم أدخل بيانات العمل.|Nomeie e salve o pacote e depois informe o trabalho.|Назовите и сохраните комплект, затем внесите данные работ.
saveTemplate|Als persönliche Vorlage speichern|個人様式として保存|Enregistrer comme modèle personnel|Salvare come modello personale|Guardar como modelo personal|حفظ كنموذج شخصي|Salvar como modelo pessoal|Сохранить как личную форму
templateHelp|JSA-Inhalte im vorhandenen JSA-Editor bearbeiten. Aktualisierte JSA oder gespeichertes Layout übernehmen.|JSA本文は既存の編集画面で編集し、更新したJSAまたは保存済みレイアウトを取り込んでください。|Modifiez le contenu dans l’éditeur JSA existant, puis importez la JSA ou sa mise en page.|Modificate il contenuto nell’editor JSA, poi importate la JSA aggiornata o il layout.|Edite el contenido en el editor JSA e importe la JSA actualizada o su diseño.|حرر المحتوى في محرر تحليل العمل ثم استورد النسخة المحدثة أو التخطيط.|Edite no editor JSA e importe a versão atualizada ou o layout.|Правьте содержание в редакторе JSA, затем импортируйте обновлённый JSA или макет.
archiveHelp|Archivierte PDFs und Eingaben ändern sich nicht bei späteren Vorlagen- oder Zeichnungsänderungen.|後から様式や図面を変更しても、保管済みPDFと入力記録は変わりません。|Les PDF et données archivés restent inchangés si les modèles ou plans évoluent.|PDF e dati archiviati restano invariati se modelli o disegni cambiano.|Los PDF y datos archivados no cambian al modificar modelos o planos.|لا تتغير ملفات PDF والبيانات المؤرشفة عند تعديل النماذج أو المخططات.|PDFs e dados arquivados não mudam com alterações de modelos ou desenhos.|Архивные PDF и данные не меняются при изменении форм или чертежей.
unsaved|Nicht gespeicherte Änderungen. Seite verlassen?|未保存の変更があります。この画面を離れますか？|Modifications non enregistrées. Quitter ?|Modifiche non salvate. Uscire?|Hay cambios sin guardar. ¿Salir?|توجد تعديلات غير محفوظة. هل تريد المغادرة؟|Há alterações não salvas. Sair?|Есть несохранённые изменения. Выйти?
needReview|Zeichnungsseiten wählen und Positionen der Markierungen bestätigen.|出力前に図面ページと書込み位置を確認してください。|Sélectionnez les pages et confirmez les annotations.|Selezionare le pagine e confermare le annotazioni.|Seleccione páginas y confirme las anotaciones.|اختر الصفحات وأكد مواضع التعليقات.|Selecione páginas e confirme as anotações.|Выберите страницы и подтвердите положение пометок.
fileError|Datei nicht unterstützt, verschlüsselt, beschädigt oder zu groß. PDF, PNG oder JPG innerhalb der Grenzen verwenden.|非対応・暗号化・破損・容量超過のファイルです。制限内のPDF・PNG・JPGを使用してください。|Fichier non pris en charge, chiffré, endommagé ou trop volumineux. Utilisez PDF, PNG ou JPG dans les limites.|File non supportato, cifrato, danneggiato o troppo grande. Usare PDF, PNG o JPG entro i limiti.|Archivo no compatible, cifrado, dañado o demasiado grande. Use PDF, PNG o JPG dentro de los límites.|الملف غير مدعوم أو مشفر أو تالف أو كبير. استخدم PDF أو PNG أو JPG ضمن الحدود.|Arquivo incompatível, criptografado, danificado ou grande demais. Use PDF, PNG ou JPG dentro dos limites.|Файл не поддерживается, зашифрован, повреждён или слишком большой. Используйте PDF, PNG или JPG в пределах ограничений.
outputError|Archivierung fehlgeschlagen; nichts gedruckt. Erneut versuchen oder Dokumente reduzieren.|保管できなかったため印刷していません。再試行するか書類数を減らしてください。|Archivage impossible ; rien n’a été imprimé. Réessayez ou réduisez les documents.|Archiviazione non riuscita; nulla è stato stampato. Riprovare o ridurre i documenti.|No se pudo archivar; no se imprimió nada. Reintente o reduzca documentos.|تعذرت الأرشفة ولم تُطبع أي مستندات. أعد المحاولة أو قلل عددها.|Não foi possível arquivar; nada foi impresso. Tente novamente ou reduza os documentos.|Не удалось архивировать; печать не выполнена. Повторите или сократите число документов.
included|In Ausgabe aufnehmen|出力に含める|Inclure dans la sortie|Includere nell’uscita|Incluir en la salida|تضمين في الإخراج|Incluir na saída|Включить в вывод
portrait|Hochformat|縦|Portrait|Verticale|Vertical|عمودي|Retrato|Книжная
landscape|Querformat|横|Paysage|Orizzontale|Horizontal|أفقي|Paisagem|Альбомная
formTitle|Dokumenttitel|文書タイトル|Titre du document|Titolo del documento|Título del documento|عنوان المستند|Título do documento|Заголовок документа
currentWork|Aktuelle Arbeitseingaben|今回の作業入力値|Données du travail actuel|Dati del lavoro attuale|Datos del trabajo actual|بيانات العمل الحالي|Dados do trabalho atual|Данные текущих работ
edit|Bearbeiten|編集|Modifier|Modifica|Editar|تحرير|Editar|Редактировать
newRow|Zeile hinzufügen|行を追加|Ajouter une ligne|Aggiungere riga|Añadir fila|إضافة صف|Adicionar linha|Добавить строку
newColumn|Spalte hinzufügen|列を追加|Ajouter une colonne|Aggiungere colonna|Añadir columna|إضافة عمود|Adicionar coluna|Добавить столбец
actualOnly|Je Arbeit ausfüllen oder leer lassen.|作業ごとに入力するか、空欄にしてください。|À remplir pour chaque travail ou à laisser vide.|Compilare per ogni lavoro o lasciare vuoto.|Complete para cada trabajo o deje vacío.|يُملأ لكل عمل أو يُترك فارغاً.|Preencha em cada trabalho ou deixe em branco.|Заполнять для каждых работ или оставлять пустым.
original|Zeichnungsoriginal|図面原本|Original du plan|Originale del disegno|Original del plano|أصل المخطط|Original do desenho|Оригинал чертежа
printReady|Ausgabe archiviert. Erneut drucken oder herunterladen möglich.|出力本を保管しました。再印刷・ダウンロードできます。|Sortie archivée. Vous pouvez la réimprimer ou la télécharger.|Uscita archiviata. È possibile ristampare o scaricare.|Salida archivada. Puede imprimirla o descargarla de nuevo.|تمت الأرشفة. يمكنك الطباعة أو التنزيل مجدداً.|Saída arquivada. Você pode imprimir ou baixar novamente.|Выпуск архивирован. Можно повторно распечатать или скачать.
drawHelp|Werkzeug wählen und ziehen. Mit Auswahl verschieben, am Griff skalieren; nach dem Zoomen scrollen.|ツールを選んでドラッグします。選択で移動、ハンドルでサイズ変更、拡大後はスクロールできます。|Choisissez un outil et faites glisser. Sélectionnez pour déplacer, utilisez la poignée pour redimensionner et défilez après zoom.|Scegliete uno strumento e trascinate. Selezionate per spostare, usate la maniglia per ridimensionare e scorrete dopo lo zoom.|Elija una herramienta y arrastre. Seleccione para mover, use el asa para cambiar tamaño y desplácese tras ampliar.|اختر أداة واسحب. حدد للنقل واستخدم المقبض لتغيير الحجم ثم مرر بعد التكبير.|Escolha uma ferramenta e arraste. Selecione para mover, use a alça para redimensionar e role após ampliar.|Выберите инструмент и тяните. Выделение перемещает, маркер меняет размер; после увеличения прокручивайте.
previous|Zurück|前へ|Précédent|Precedente|Anterior|السابق|Anterior|Назад
next|Weiter|次へ|Suivant|Successivo|Siguiente|التالي|Próximo|Далее
`;
for (const line of rows.trim().split('\n')) {
  const [key, ...values] = line.split('|');
  if (values.length !== languages.length || values.some(v => !v)) throw Error(`Incomplete workspace translation: ${key}`);
  languages.forEach((l, i) => { workPackageTranslations[l][key] = values[i]; });
}
