// Application checklists with separate Australian model and Singapore scopes.
export const AU_SG_TASK_VERSION = '2026-10-06.22';
const source = (title, url, scope, basis = 'regulation') => ({ title, url, scope, basis, checkedAt: '2026-10-06' });
const swa = (title, url, scope) => source(`Safe Work Australia · ${title}`, url, scope, 'model-code');
const sso = (id, title, scope) => source(`Singapore · ${title}`, `https://sso.agc.gov.sg/SL/${id}`, scope);
const auLocal = source('Safe Work Australia · Local legal effect', 'https://www.safeworkaustralia.gov.au/law-and-regulation/legislation', 'Model codes are not automatically local law; Victoria has not adopted model WHS laws. Confirm adoption, variations, licensing and sector rules.', 'official-guidance');
export const AU_SG_TASK_REVIEW = {
  'AU.height': { fields: ['anchorCheck', 'trainingEvidence', 'rescueReadiness', 'fallServiceRelease', 'heightAccessCheck'], sources: [auLocal, swa('Falls · October 2018 (2022 file), sections 1–10', 'https://www.safeworkaustralia.gov.au/sites/default/files/2022-10/Model%20Code%20of%20Practice%20-%20Managing%20the%20Risk%20of%20Falls%20at%20Workplaces%2021102022_0.pdf', 'Model hierarchy, access/fragile surfaces/ladders, competent inspection, withdrawal after defects or arrest, training and tested rescue. SWMS trigger does not exempt lower falls; scaffold/anchor engineering and state adoption separate.')] },
  'AU.confined': { fields: ['planReference', 'trainingEvidence', 'rescueReadiness', 'atmosphericBasis', 'entryAuthorisation', 'standbyArrangement', 'restartReview'], note: 'auEntryReviewNote', sources: [auLocal, swa('Confined spaces · November 2024, sections 1–5', 'https://www.safeworkaustralia.gov.au/sites/default/files/2024-11/model_code_of_practice-confined_spaces-nov24.pdf', 'Model scope/classification, written assessment/permit, isolation, atmosphere, outside standby and practised rescue, permit revalidation, all-out acknowledgement and incident-dependent retention. Local rules and Victoria remain distinct.')] },
  'AU.electrical': { fields: ['licenceScope', 'personalLockRegister', 'isolationHandover', 'countryProcedure'], sources: [auLocal, swa('Electrical risks · 2018, sections 3–5', 'https://www.safeworkaustralia.gov.au/system/files/documents/1810/model-cop-managing-electrical-risks-in-the-workplace.pdf', 'Licensed/registered electrical worker, all supplies/stored energy, test-before-touch, locking/tagging, safe unfinished-work handover and restoration. Energised testing requires its separate route; supply-authority exclusions and local licences are not inferred.')] },
  'AU.hot': { fields: ['atmosphericBasis', 'weldingEquipmentCheck', 'hotFireProtection', 'trainingEvidence', 'multiEmployerRoles'], sources: [auLocal, swa('Welding processes · July 2020, sections 1–4', 'https://www.safeworkaustralia.gov.au/sites/default/files/2020-07/model_code_of_practice_welding_processes.pdf', 'Current publication-hub download checked: consultation/training, fire/explosion, fumes/ventilation, cylinders, equipment inspection and surrounding work. Confined entry and hot-work procedures remain separate; no nationwide permit or watch-duration mandate.')] },
  'SG.height': { fields: ['planReference', 'trainingEvidence', 'rescueReadiness', 'heightAccessCheck', 'permitCloseout', 'restartReview'], sources: [sso('WSHA2006-S223-2013', 'Work at Heights · 2–18, 20–30, First Schedule', 'Current SSO parts and schedule read. General fall prevention and scheduled fall plan versus factory hazardous-WAH permits, access/roof/fragile/ladder controls, training/supervision, shift inspection, posting/review/reapplication and completion notification. Rope engineering and scaffold-specific rules separate.')] },
  'SG.confined': { fields: ['planReference', 'trainingEvidence', 'rescueReadiness', 'atmosphericBasis', 'standbyArrangement', 'entryAuthorisation', 'permitCloseout', 'permitRecord', 'restartReview', 'multiEmployerRoles', 'sgRescueInspection'], note: 'sgEntryReviewNote', sources: [sso('WSHA2006-S462-2009', 'Confined Spaces · 2–23', 'Current SSO consolidation effective 2024-06-01: necessary entry, appointed assessor/manager/attendant, ordered calibrated testing, endorsement/issue, posted permit, daily review, expiry/new application, hazardous atmosphere exit/new permit, rescue inspection and two-year test/inspection records. Reg 10(2) exception is not automatically authorised.')] },
  'SG.electrical': { fields: ['countryProcedure', 'isolationSequence', 'isolationHandover', 'restorationRelease', 'trainingEvidence'], note: 'sgElectricalBoundaryNote', sources: [source('EMA · Licensed Electrical Workers', 'https://www.ema.gov.sg/consumer-information/electricity/engaging-licensed-workers', 'Verify valid licence, class, load/voltage and supervision scope; generic competence is not a licence.', 'official-guidance'), sso('354A-RG1?DocDate=20260929&ProvIds=P1III-', 'General Provisions · 14, 16', 'Current canonical SSO text read: safe equipment, shock protection and instructed lock-out procedures covering all energy sources and prevention of inadvertent energisation.'), sso('EA2001-RG5?ProvIds=P1IV-', 'Electrical Installations · 23–26', 'High-voltage route: authorised switching engineer, appointed appropriate-class LEW, dedicated permits, key custody, completion/cancellation and external-supply certificate. This general isolation record does not issue that permit.')] },
  'SG.hot': { fields: ['sgMarineEquipmentCheck', 'sgFireEscalation', 'atmosphericBasis', 'hotFireProtection', 'trainingEvidence', 'containerHistory'], sources: [sso('WSHA2006-S270-2008', 'Shipbuilding/Ship-Repairing · 23–24, 27–37, 53–65', 'Current SSO marine scope: serialised permit, exact location and joint assessment, trained fire watch and SCDF escalation, electrical shock protection/6-month preventor test, gas backflow/flashback/leak devices, wet-work prohibition, ventilation and container controls. Existing 14/30-day and annual register checks retained.')] },
};
export function applyAuSgTaskReview(records) {
  const result = structuredClone(records);
  for (const [id, review] of Object.entries(AU_SG_TASK_REVIEW)) {
    const [country, topic] = id.split('.'), record = result[country][topic];
    record.fields = [...new Set([...record.fields, ...review.fields])];
    record.additionalNotes = [...new Set([...(record.additionalNotes || []), ...(review.note ? [review.note] : [])])];
    record.sources = [...new Map([...record.sources, ...review.sources].map(s => [s.url, s])).values()];
    record.version = AU_SG_TASK_VERSION;
    record.checkedAt = '2026-10-06';
    record.evidence = 'regional-au-sg-task-review-20261006.md';
    record.remaining = 'Application task-prompt checklist compared under the recorded model/national/sector scope. Local adoption, site decisions, engineered designs, incorporated standards and statutory permits remain separate; see evidence.';
  }
  result.SG.height.sources.push(source('WSHC · Fall prevention planning', 'https://www.tal.sg/wshc/topics/work-at-height/preventing-falls-from-heights', 'Site-specific fall plan includes training, inspection/maintenance and emergency response; factory permit scope remains controlled by the regulation.', 'official-guidance'));
  return result;
}
