// Task-level starter records. Titles do not claim to replace an enterprise-wide
// DUERP, DVR, PGR, statutory register or task-specific permit system.
const cc = { title: 'CCOHS · Job Safety Analysis', url: 'https://www.ccohs.ca/oshanswers/hsprograms/job-haz.html' };
const kinds = ['risk_assessment', 'method_statement', 'permit_to_work', 'toolbox_talk', 'inspection'];
const profile = (language, titles, sources, extra, organisationRecord = '') => ({ language, titles: Object.fromEntries(kinds.map((k,i) => [k,titles[i]])), sources, extra, organisationRecord });
export const REGIONAL_CATALOG = {
  US: profile('en', ['Job Hazard Analysis (JHA)', 'Safe Job Procedure', 'Permit to Work', 'Toolbox Talk', 'Safety Inspection Checklist'], [{ title: 'OSHA · Job Hazard Analysis', url: 'https://www.osha.gov/sites/default/files/Job_Hazard_Analysis_Worksheet.pdf' }], 'Local procedures, interfaces and responsible roles'),
  CA: profile('en', ['Job Safety Analysis (JSA)', 'Safe Work Procedure', 'Permit to Work', 'Toolbox Talk', 'Workplace Inspection Checklist'], [cc], 'Worker consultation and reassessment triggers'),
  'CA-AB': profile('en', ['Hazard Assessment', 'Safe Work Procedure', 'Safe Work Permit', 'Toolbox Meeting', 'Workplace Inspection Checklist'], [cc, { title: 'Alberta OHS · Hazard assessment and control', url: 'https://ohs-pubstore.labour.alberta.ca/el003' }], 'Worker consultation and reassessment triggers'),
  'CA-ON': profile('en', ['Job Safety Analysis (JSA)', 'Safe Work Procedure', 'Permit to Work', 'Safety Talk', 'Workplace Inspection Checklist'], [cc, { title: 'Ontario · Workplace hazards', url: 'https://www.ontario.ca/page/workplace-hazards' }], 'Local procedures, interfaces and responsible roles'),
  'CA-BC': profile('en', ['Risk Assessment', 'Safe Work Procedure', 'Permit to Work', 'Toolbox Meeting', 'Workplace Inspection Checklist'], [cc, { title: 'WorkSafeBC · Assessing risks', url: 'https://www.worksafebc.com/en/health-safety/create-manage/managing-risk/assessing-risks' }], 'Worksite conditions and lone work arrangements'),
  'CA-QC': profile('fr', ['Analyse de la sécurité des tâches (AST)', 'Méthode de travail sécuritaire', 'Permis de travail', 'Rencontre de sécurité', 'Liste d’inspection du milieu de travail'], [cc, { title: 'CNESST · Identifier les risques', url: 'https://www.cnesst.gouv.qc.ca/fr/prevention-securite/organiser-prevention/sante-securite-travail-pour-tous/demarche-prevention/identifier-risques-milieu-travail' }], 'Prevention plan reference and follow-up'),
  DE: profile('de', ['Gefährdungsbeurteilung – Tätigkeit', 'Arbeitsanweisung – sicheres Arbeiten', 'Arbeitserlaubnis', 'Sicherheitskurzbesprechung', 'Sicherheitscheckliste'], [{ title: 'BAuA · Gefährdungsbeurteilung', url: 'https://www.baua.de/DE/Themen/Arbeitsgestaltung/Gefaehrdungsbeurteilung/Handbuch-Gefaehrdungsbeurteilung/Grundlagenwissen' }], 'Effectiveness checks and review date'),
  JP: profile('ja', ['作業リスクアセスメント', '安全作業手順書', '作業許可書', '危険予知活動（KY）記録', '安全点検表'], [{ title: '厚生労働省 · リスクアセスメント資料', url: 'https://www.mhlw.go.jp/bunya/roudoukijun/anzeneisei14/100119-1.html' }], 'Priority hazards and team action commitments'),
  FR: profile('fr', ['Évaluation des risques – fiche de tâche', 'Mode opératoire de sécurité', 'Permis de travail', 'Causerie sécurité', 'Liste de contrôle de sécurité'], [{ title: 'INRS · Évaluation des risques et document unique', url: 'https://www.inrs.fr/demarche/document-unique/ce-qu-il-faut-retenir.html' }], 'Work unit and related prevention documents', 'DUERP'),
  IT: profile('it', ['Valutazione dei rischi – scheda di attività', 'Procedura di lavoro sicuro', 'Permesso di lavoro', 'Riunione di sicurezza', 'Lista di controllo della sicurezza'], [{ title: 'INAIL · Strumenti per la valutazione del rischio', url: 'https://www.inail.it/portale/prevenzione-e-sicurezza/it/prevenzione-e-sicurezza/prevenzione-per-la-salute-e-la-sicurezza-sul-lavoro/strumenti-per-la-valutazione-del-rischio.html' }], 'Local procedures, interfaces and responsible roles', 'DVR'),
  ES: profile('es', ['Evaluación de riesgos de la tarea', 'Procedimiento de trabajo seguro', 'Autorización de trabajo especial', 'Charla de seguridad', 'Lista de comprobación de seguridad'], [{ title: 'INSST · Evaluación de riesgos laborales', url: 'https://www.insst.es/noticias-insst/directrices-basicas-para-la-evaluacion-de-riesgos-laborales' }], 'Local procedures, interfaces and responsible roles'),
  SA: profile('ar', ['تقييم مخاطر المهمة', 'إجراء العمل الآمن', 'تصريح العمل الآمن', 'اجتماع السلامة قبل بدء العمل', 'قائمة فحص السلامة'], [{ title: 'HRSD · Occupational safety and health guidance', url: 'https://www.hrsd.gov.sa/en/knowledge-centre/labour-education-articles' }, { title: 'NCOSH · مركز المعرفة', url: 'https://www.ncosh.gov.sa/ar/knowledge-center/' }], 'Local procedures, interfaces and responsible roles'),
  BR: profile('pt', ['Análise de Risco da Tarefa (AR)', 'Procedimento de Trabalho Seguro', 'Permissão de Trabalho (PT)', 'Diálogo Diário de Segurança (DDS)', 'Lista de Verificação de Segurança'], [{ title: 'Ministério do Trabalho e Emprego · PGR', url: 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/pgr/principal' }], 'Prevention plan reference and follow-up', 'PGR — inventário de riscos / plano de ação'),
  RU: profile('ru', ['Оценка рисков при выполнении работ', 'Инструкция по безопасному выполнению работ', 'Разрешение на работы — рабочий шаблон', 'Обсуждение безопасности перед работой', 'Контрольный лист безопасности'], [{ title: 'Минтруд · Методы оценки профессиональных рисков', url: 'https://mintrud.gov.ru/docs/mintrud/orders/2220' }], 'Worker consultation and reassessment triggers'),
};
