// A complete batch of the 24 outstanding task combinations. Evidence gaps are
// retained explicitly; field availability is never a finding of legal compliance.
export const FINAL_TASK_VERSION = '2026-10-06.25';
const source = (title, url, scope, basis = 'regulation') => ({ title, url, scope, basis, checkedAt: '2026-10-06' });
const jp = (page, scope) => source(`厚生労働省 · 安衛則 · ${page}`, `https://www.mhlw.go.jp/web/t_doc?dataId=74003000&dataType=0&pageNo=${page}`, scope);
const qc = (kind, scope) => source(`Légis Québec · ${kind}`, kind === 'RSST' ? 'https://www.legisquebec.gouv.qc.ca/fr/document/rc/S-2.1,%20%20r.%2013?langcont=fr' : 'https://www.legisquebec.gouv.qc.ca/fr/document/rc/S-2.1,%20r.%204', scope);
const br = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/';
const it = source('INL · D.lgs. 81/2008, edizione ottobre 2026', 'https://www.ispettorato.gov.it/files/2026/10/TU-81-08-Ed.-Ottobre-2026.pdf', 'Agency-hosted coordinated text, printed pp.94–99 and 107: articles 111–116 and 148, including converted 2025 protection/ladder amendments. Editorial commentary is not legislation.', 'regulation-consolidation');
const openScope = 'Latest implementing/sector requirements remain unresolved; added blanks are site-review prompts, not verified statutory duties. See individual gaps in regional-final-task-review-20261006.md.';
const saCompany = source('Saudi Electricity Company · Life Saving Rules', 'https://www.se.com.sa/-/media/sec/Our-Partners/Join-Us/Life-Saving-Rules-booklet/Life-Saving-Rules-booklet-in-Arabic.ashx', 'Company rules 1, 2, 4, 6 and 7: isolation/shift communication, permit coordination, height checks, hot-work atmosphere and confined-space attendance/rescue. Supports site-procedure prompts only, not national legislation or licensing implementation.', 'company-guidance');
export const FINAL_TASK_REVIEW = {
  'JP.height': { fields: ['heightAccessCheck', 'fallServiceRelease', 'fallingObjects', 'trainingEvidence', 'rescueReadiness'], sources: [jp(9, '518–539 and 539-2–9: platforms/edges, anchors, pre-use inspection, weather, fragile surfaces, access and falling objects; conditional rope-work survey, plan, direction and daily checks. No blanket below-2m exemption.')] },
  'JP.confined': { fields: ['planReference', 'measurementCompetence', 'atmosphericBasis', 'standbyArrangement', 'rescueReadiness', 'restartReview', 'permitRecord', 'jpAtmosphereRecord'], note: 'jpEntryLifecycleNote', sources: [source('厚生労働省 · 酸素欠乏症等防止規則 · 第3–17条', 'https://www.mhlw.go.jp/web/t_doc?dataId=74105000&dataType=0&pageNo=1', 'Class-specific chief/training, pre-start/re-entry/abnormality tests, three-year daily-measurement records, ventilation without pure oxygen, equipment checks, headcounts, monitoring, evacuation and protected rescue. Numeric criteria and exceptions require actual classification.')] },
  'JP.electrical': { fields: ['electricalEligibility', 'isolationVerification', 'countryProcedure', 'trainingEvidence'], sources: [jp(8, '339–340 and 350: lock OR no-energisation notice OR watcher, stored-charge discharge, HV/EHV test and short-circuit earthing, safe restoration, appointed director and task/circuit briefing. No live-work authorisation.')] },
  'JP.hot': { fields: ['weldingEquipmentCheck', 'hotFireProtection', 'atmosphericBasis', 'trainingEvidence', 'restartReview', 'watchCloseout'], sources: [jp(7, '279 and 285–286: ignition exclusion in explosive atmospheres, container/pipe cleaning and no oxygen ventilation; no universal statutory written permit or numeric watch duration.'), jp(8, '331–333 and 336–338: welding electrical equipment, shock-prevention conditions and cable protection; device exceptions require a separate basis.')] },
  'IT.height': { fields: ['heightAccessCheck', 'ropeWorkPlan', 'trainingEvidence', 'rescueReadiness', 'fallServiceRelease'], replaceNote: 'itHeightCurrentNote', resolve: 'it-current-height-consolidation', sources: [it] },
  'IT.confined': { fields: ['itContractReview', 'planReference', 'assessmentEndorsement', 'atmosphericBasis', 'standbyArrangement', 'rescueReadiness', 'multiEmployerRoles', 'restartReview', 'permitRecord'], sources: [source('Gazzetta Ufficiale · DPR 177/2011, articoli 2–3', 'https://www.gazzettaufficiale.it/eli/id/2011/11/08/011G0219/sg', 'Company/worker qualification is distinct from attendance. Client information transfer, competent client representative and coordinated work/rescue procedure through every phase; retain qualification/training evidence and actual emergency arrangements.')] },
  'IT.electrical': { fields: ['electricalEligibility', 'countryProcedure', 'isolationHandover', 'permitRecord'], pending: 'Full CEI 11-27:2025 text and applicable corrections/procedure details remain unread. Public role summaries do not close that gap.', sources: [] },
  'IT.hot': { fields: ['hotFireProtection', 'combustibleSurroundings', 'restartReview', 'permitRecord'], sources: [source('INAIL · Rischi dell’estate negli stabilimenti PIR, 2022', 'https://www.inail.it/content/dam/inail-hub-site/documenti/2022/07/FactSheetRischi%20estate.pdf', 'PIR establishment guidance: vegetation/surroundings, explicit pre-work checks in permit and final latent-ignition inspection. Generic stop/record prompts support site procedure; not a universal legal permit or watch time.', 'official-guidance')] },
  'BR.height': { fields: ['heightAccessCheck', 'anchorCheck', 'fallServiceRelease', 'rescueReadiness', 'permitCloseout', 'restartReview'], resolve: 'br-current-nr35-publication-date', sources: [source('MTE · NR-35, atualização 16/07/2026', br + 'normas-regulamentadora/normas-regulamentadoras-vigentes/nr-35-atualizada-2025-1.pdf', 'Current downloaded header identifies Portaria 1.259 of 15 July, published 16 July 2026. 35.3–35.7 and annex III: planning, hierarchy, supervision, risk analysis, routine/non-routine PT, inspections, rescue and conditional ladder transitions.'), source('MTE · Treinamentos e escadas, 02/09/2026', 'https://www.gov.br/trabalho-e-emprego/pt-br/noticias-e-conteudo/2026/setembro/trabalho-em-altura-veja-o-que-muda-nos-treinamentos-e-nas-escadas-fixas-verticais', 'Corroborates July publication/effect, in-person training and conditional ladder transition. Resolves earlier June/July source-header conflict; no automatic exemption.', 'official-guidance')] },
  'BR.confined': { fields: ['assessmentEndorsement', 'planReference', 'trainingEvidence', 'atmosphericBasis', 'standbyArrangement', 'rescueReadiness', 'entryAuthorisation', 'permitDisplay', 'brPetSignatures'], sources: [source('MTE · NR-33, 33.3–33.5', br + 'arquivos/normas-regulamentadoras/nr-33-atualizada-2022-_retificada.pdf', 'Technical responsible person, supervisor/vigia/entrants, PET for each entry, current quantitative tests, supervisor AND vigia signatures, accessible copies, five-year retention, closure triggers and conditional extensions capped at 24 hours. Generic application form still links the separate PET.')] },
  'BR.electrical': { fields: ['electricalEligibility', 'trainingEvidence', 'isolationSequence', 'isolationVerification', 'restorationRelease', 'workLeader', 'countryProcedure', 'brServiceOrder'], sources: [source('MTE · NR-10 (2019 edition, valid through 2027-05-31)', br + 'arquivos/normas-regulamentadoras/nr-10-atualizada-2019-1.pdf', '10.5, 10.8 and 10.11–10.14: ordered isolation/restoration, formal technical justification for deviations, distinct qualification/authorisation, approved service order, work procedure, supervision, prior team review and stop-work. The June 2027 replacement is not applied now.')] },
  'BR.hot': { fields: ['weldingEquipmentCheck', 'hotFireProtection', 'trainingEvidence', 'atmosphericBasis', 'permitCloseout', 'permitCoordination'], sources: [source('MTE · NR-34, 34.4–34.5', br + 'arquivos/normas-regulamentadoras/nr-34-atualizada-2022.pdf', 'Naval industry only: APR/PT for work outside designated areas, shift validity/revalidation, five-year records, pre-inspection, trained observer when APR requires, gas/electrical equipment, stop shutoff and final ignition inspection.')] },
  'CA-QC.height': { fields: ['heightAccessCheck', 'fallServiceRelease', 'trainingEvidence', 'planReference', 'qcRescueSchedule'], sources: [qc('CSTC', '2.9.1–2.9.5.2: hierarchy and conditional exceptions, construction rescue procedure/training/drills and on-site readiness; 15-minute release and six-month drill interval belong to this construction framework, not every jurisdiction.')] },
  'CA-QC.confined': { fields: ['planReference', 'assessmentEndorsement', 'measurementCompetence', 'atmosphericBasis', 'standbyArrangement', 'permitRecord', 'qcEntryRecords'], note: 'qcEntryLimitsNote', resolve: 'qc-current-rsst-cstc-confined', sources: [qc('RSST', '296.1–312: qualified assessment, eligible entrants, written methods, class-specific atmosphere, testing/retesting and records, outside surveillant, unexpected-risk stop/qualified restart and practised rescue. Article 307 five-year retention concerns nonconforming readings, not all permits.'), qc('CSTC', '3.21.1–6: joint construction hazard record, distinct entry criteria and testing frequency, ventilation/access and special emergency conditions. Do not substitute RSST criteria/roles for CSTC.')] },
  'CA-QC.electrical': { fields: ['electricalEligibility', 'isolationSequence', 'isolationVerification', 'isolationHandover', 'restorationRelease', 'multiEmployerRoles', 'permitRecord'], sources: [qc('CSTC', '2.20.2–14: written energy procedure, individual locks, equivalent-method analysis, training, written principal-contractor authorisation, multiple-employer coordination, shift continuity and conditional cut-lock record. Electrical installations included with necessary adaptations.')] },
  'CA-QC.hot': { fields: ['hotFireProtection', 'weldingEquipmentCheck', 'atmosphericBasis', 'restartReview', 'permitRecord'], replaceNote: 'qcHotScopeNote', pending: 'Current RSST 313–319/CSTC 3.14 compared. Incorporated CSA welding-standard text and applicable adopted fire-code requirements remain unresolved.', sources: [qc('RSST', '313–319: ignition hazards, incorporated CSA chapters, screens, vessel history/cleaning/testing and gas/flashback protection. Full incorporated standards not read.'), qc('CSTC', '3.14: precautions, incorporated CSA W117.2-M87, container checks, arc screens, gas/flashback devices and electrical protection. Applicable fire-code review remains open.')] },
  'SA.height': { fields: ['heightAccessCheck', 'rescueReadiness', 'planReference', 'permitCoordination'], note: 'saTaskEvidenceNote', pending: openScope, sources: [] },
  'SA.confined': { fields: ['assessmentEndorsement', 'planReference', 'atmosphericBasis', 'standbyArrangement', 'rescueReadiness', 'restartReview', 'permitRecord'], note: 'saTaskEvidenceNote', pending: openScope, sources: [] },
  'SA.electrical': { fields: ['electricalEligibility', 'isolationHandover', 'planReference', 'permitCoordination'], note: 'saTaskEvidenceNote', pending: openScope, sources: [] },
  'SA.hot': { fields: ['hotFireProtection', 'atmosphericBasis', 'watchCloseout', 'permitCoordination'], note: 'saTaskEvidenceNote', pending: openScope, sources: [] },
  'RU.height': { fields: ['trainingEvidence', 'fallingObjects', 'permitCoverage', 'planReference'], note: 'ruTaskEvidenceNote', pending: openScope, sources: [source('Роструд · Очистка крыш от снега, 17/02/2021', 'https://git59.rostrud.gov.ru/upload/iblock/528/20691_rlu.pdf', 'Original regulator notice supports the height-work/naryad-dopusk terminology and roof-snow preparation, training and exclusion-zone prompts. Historical notice does not verify current full 782н.', 'official-guidance')] },
  'RU.confined': { fields: ['planReference', 'trainingEvidence', 'standbyArrangement', 'atmosphericBasis', 'rescueReadiness', 'permitCoverage'], note: 'ruTaskEvidenceNote', pending: openScope, sources: [source('ГИТ Рязанской области · Памятка 902н', 'https://git62.rostrud.gov.ru/upload/iblock/388/pamyatka-dlya-rabotodateley.pdf', 'Regulator-hosted rule presentation: ОЗП, naryad-dopusk and outside observing worker; supports role meaning and risk/testing/communication prompts. Undated consolidation is not current-amendment closure.', 'official-guidance')] },
  'RU.electrical': { fields: ['electricalEligibility', 'trainingEvidence', 'countryProcedure', 'isolationHandover', 'permitRecord'], note: 'ruTaskEvidenceNote', pending: openScope, sources: [] },
  'RU.hot': { fields: ['hotFireProtection', 'weldingEquipmentCheck', 'atmosphericBasis', 'restartReview', 'permitCoordination'], note: 'ruTaskEvidenceNote', pending: openScope + ' There is no automatic duration or expiry from historical material.', sources: [] },
};
export const FINAL_TASK_CLOSABLE_IDS = Object.keys(FINAL_TASK_REVIEW).filter(id => !FINAL_TASK_REVIEW[id].pending);

export function applyFinalTaskReview(records) {
  const result = structuredClone(records);
  for (const [id, review] of Object.entries(FINAL_TASK_REVIEW)) {
    const [country, topic] = id.split('.'), record = result[country][topic];
    record.fields = [...new Set([...record.fields, ...review.fields])];
    if (review.replaceNote) record.noteKey = review.replaceNote;
    record.additionalNotes = [...new Set([...(record.additionalNotes || []), ...(review.note ? [review.note] : [])])];
    record.sources = [...new Map([...record.sources, ...review.sources, ...(country === 'SA' ? [saCompany] : [])].map(s => [s.url, s])).values()];
    if (review.resolve) {
      record.partial = false;
      record.resolvedIssues = [...new Set([...(record.resolvedIssues || []), review.resolve])];
    }
    if (review.pending) record.partial = true;
    record.version = FINAL_TASK_VERSION;
    record.checkedAt = '2026-10-06';
    record.evidence = 'regional-final-task-review-20261006.md';
    record.remaining = review.pending || 'Application task checklist compared within the cited sources. Site measurements, competence, engineering, sector exceptions and statutory authorisations remain separate; see evidence.';
  }
  return result;
}
