// Evidence for the task-level form review, not a statutory compliance badge.
// A source's guidance status must not become a mandatory rule for every job.
const source = (title, url, basis = 'official-guidance') => ({ title, url, basis });
const canada = source('CCOHS · Job Safety Analysis', 'https://www.ccohs.ca/oshanswers/hsprograms/job-haz.html');
export const REGIONAL_REVIEW_SOURCES = {
  KR: [source('고용노동부 · 사업장 위험성평가에 관한 지침 (2024-76)', 'https://www.moel.go.kr/info/lawinfo/instruction/view.do?bbs_seq=20241201150', 'regulation')],
  GB: [source('HSE · Risk assessment template', 'https://www.hse.gov.uk/simple-health-safety/risk/risk-assessment-template-and-examples.htm'), source('HSENI · Five steps to risk assessment', 'https://www.hseni.gov.uk/publications/five-steps-risk-assessment'), source('HSE · Permit to work systems', 'https://www.hse.gov.uk/humanfactors/topics/ptw.htm')],
  AU: [source('Safe Work Australia · Risk management and worker consultation', 'https://www.safeworkaustralia.gov.au/safety-topic/managing-health-and-safety/identify-assess-and-control-hazards/managing-risks'), source('Safe Work Australia · High risk construction work and SWMS', 'https://www.safeworkaustralia.gov.au/duties-tool/construction/hazards-information/high-risk-construction-work-requiring-swms'), source('WorkSafe Victoria · SWMS', 'https://www.worksafe.vic.gov.au/safe-work-method-statements-swms')],
  SG: [{ title: 'Singapore Statutes Online · Risk Management Regulations, regulation 5', url: 'https://sso.agc.gov.sg/SL/WSHA2006-RG8?ProvIds=pr5-&ValidDate=20250101', basis: 'regulation', checkedAt: '2026-10-05', scope: 'Regulation 5 records of assessment and implemented measures/procedures: at least 3 years. This dated clause supplement does not assert a full current-rule review.' }, source('MOM · Risk management', 'https://www.mom.gov.sg/workplace-safety-and-health/safety-and-health-management-systems/risk-management'), source('MOM · When to review risk assessments', 'https://www.mom.gov.sg/faq/safety-and-health-management-systems/when-should-my-company-review-its-risk-assessment'), source('WSH Council · Code of Practice on Risk Management', 'https://www.tal.sg/wshc/-/media/tal/wshc/resources/publications/codes-of-practice/files/code-of-practice-risk-management-third-revision-2021.pdf'), source('MOM · Permit-to-Work systems (OPEC guidance)', 'https://www.mom.gov.sg/workplace-safety-and-health/safety-and-health-management-systems/permit-to-work-systems')],
  US: [source('OSHA · Job Hazard Analysis worksheet', 'https://www.osha.gov/sites/default/files/Job_Hazard_Analysis_Worksheet.pdf'), source('OSHA · Hazard prevention and control', 'https://www.osha.gov/safety-management/hazard-prevention')],
  CA: [canada],
  'CA-AB': [canada, source('Alberta OHS Code · Part 2, sections 7–9', 'https://search-ohs-laws.alberta.ca/legislation/occupational-health-and-safety-code/part-2-hazard-assessment-elimination-and-control/', 'regulation')],
  'CA-ON': [canada, source('Ontario · Workplace hazards', 'https://www.ontario.ca/page/workplace-hazards')],
  'CA-BC': [canada, source('WorkSafeBC · Assessing risks', 'https://www.worksafebc.com/en/health-safety/create-manage/managing-risk/assessing-risks')],
  'CA-QC': [canada, source('CNESST · Prevention framework from 1 October 2025', 'https://www.cnesst.gouv.qc.ca/fr/salle-presse/communiques/nouveau-reglement-prevention'), source('CNESST · Plan d’action', 'https://www.cnesst.gouv.qc.ca/fr/prevention-securite/organiser-prevention/mesures-specifiques-etablissements/appliquer-mecanismes-prevention-participation/mecanismes-prevention/faire-plan-action/plan-action')],
  DE: [source('BAuA · Documenting the assessment and effectiveness checks', 'https://www.baua.de/DE/Themen/Arbeitsgestaltung/Gefaehrdungsbeurteilung/Handbuch-Gefaehrdungsbeurteilung/Grundlagenwissen/Prozessschritte-der-Gefaehrdungsbeurteilung/Prozessschritte-der-Gefaehrdungsbeurteilung_dossier?pos=7')],
  JP: [
    { ...source('厚生労働省 · 印刷・製本作業におけるリスクアセスメントのすすめ方', 'https://www.mhlw.go.jp/content/11300000/001411913.pdf'), checkedAt: '2026-10-05', scope: 'Older printing/binding example used for method principles; not a universal sector form or current statutory consolidation.' },
    { ...source('厚生労働省 · ステップ7：リスクアセスメント実施状況の記録と見直し', 'https://www.mhlw.go.jp/content/11300000/001413029.pdf'), checkedAt: '2026-10-05', scope: 'Assessment records and review. This one-page source does not compare KY with risk assessment.' },
  ],
  FR: [source('INRS · DUERP and work units', 'https://www.inrs.fr/demarche/document-unique/ce-qu-il-faut-retenir.html'), source('INRS · External contractors and plan de prévention', 'https://www.inrs.fr/risques/entreprises-exterieures/cadre-reglementaire.html')],
  IT: [source('INAIL · Risk assessment tools', 'https://www.inail.it/portale/prevenzione-e-sicurezza/it/prevenzione-e-sicurezza/prevenzione-per-la-salute-e-la-sicurezza-sul-lavoro/strumenti-per-la-valutazione-del-rischio.html'), source('INAIL · DUVRI: interference risks', 'https://www.inail.it/content/dam/inail-hub-site/documenti/2016/03/ELABORAZIONE-DEL-DUVRI.pdf')],
  ES: [source('INSST · Risk assessment documentation', 'https://www.insst.es/documents/94886/2927460/Directrices%20evaluaci%C3%B3n%20de%20riesgos.pdf'), source('INSST · NTP 562: authorisation of special work', 'https://www.insst.es/documentacion/colecciones-tecnicas/ntp-notas-tecnicas-de-prevencion/16-serie-ntp-numeros-541-a-575-ano-2001/ntp-562-sistema-de-gestion-preventiva-autorizaciones-de-trabajos-especiales.')],
  SA: [source('HRSD · Toolbox talks and risk terminology', 'https://www.hrsd.gov.sa/sites/default/files/2023-02/29122022_0.pdf'), source('HRSD · Practical occupational safety guidance', 'https://www.hrsd.gov.sa/sites/default/files/2018-05/2016.10.01%20Booklet_0.pdf')],
  BR: [source('MTE · PGR inventory and action plan', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/pgr/principal'), source('MTE · NR-35 current publication page', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-35-nr-35')],
  RU: [source('Минтруд · Professional risk assessment methods (926)', 'https://mintrud.gov.ru/docs/mintrud/orders/2220'), source('Минтруд · Occupational safety instructions (772н)', 'https://mintrud.gov.ru/docs/mintrud/orders/2183', 'regulation')],
};
export const REGIONAL_REVIEW_VERSION = '2026-10-03.3';
export const REGIONAL_REVIEW_SCOPE = 'task-level terminology, assessment records and generic work-permit lifecycle';
