export default {
 business: {
  title:'Espacio de empresa', beta:'Beta gratuita', intro:'Prueba Pro y Business gratis durante 30 días. Sin tarjeta, pagos ni cobros automáticos. Tus documentos guardados seguirán disponibles para consulta al terminar la prueba.',
  free:'Free', freeDesc:'Crea documentos JSA, usa la biblioteca de pasos, exporta y reutiliza ejemplos públicos.', pro:'Beta Pro', proDesc:'Conserva las revisiones de tus documentos personales, consulta versiones anteriores y restáuralas como una nueva revisión.', business:'Beta Business', businessDesc:'Plantillas de empresa, roles, documentos privados del equipo y aprobación por versión.', start:'Iniciar prueba gratuita de Pro + Business', active:'Fin de la prueba', expired:'La prueba ha terminado. Los documentos guardados y el historial siguen disponibles para consulta.', login:'Inicia sesión para continuar', library:'Mi biblioteca', home:'Inicio', loading:'Cargando…', retry:'Reintentar', saved:'Guardado.', error:'No se pudo completar la solicitud. Actualiza e inténtalo de nuevo.', conflict:'Este documento ha cambiado. Actualiza y revisa la última versión antes de volver a intentarlo.', denied:'No tienes permiso para realizar esta acción.', expiredError:'La prueba ha terminado. Los datos existentes siguen disponibles para consulta.', reviewerError:'Elige a otro revisor que no haya editado esta versión.', unavailable:'La invitación ha caducado, se ha revocado o ya se ha utilizado.',
  organizations:'Organizaciones', chooseOrg:'Elegir una organización', name:'Nombre de la organización', create:'Crear organización', limit:'Hasta 3 organizaciones durante la prueba.', orgExpired:'Esta organización es de solo lectura porque ha terminado la prueba de su propietario.', documents:'Documentos del equipo', members:'Miembros e invitaciones', templates:'Plantillas de empresa', history:'Historial de revisiones personales', historyHint:'Las revisiones se registran al guardar documentos privados durante la prueba. La restauración crea una nueva revisión y conserva el historial. Se muestran las últimas 100 entradas.',
  source:'Mi documento privado', chooseSource:'Elegir un documento privado guardado', import:'Compartir una copia con esta organización', importHint:'Solo se copia el documento privado seleccionado, incluidos sus participantes y fotos. Todos los miembros de la organización pueden consultarlo. El original permanece en tu biblioteca.', importConfirm:'¿Compartir una copia de este documento, incluidos sus datos privados y fotos, con todos los miembros de la organización seleccionada?',
  empty:'Todavía no hay elementos.', open:'Abrir', revision:'Revisión', draft:'Borrador', submitted:'Pendiente de aprobación', approved:'Aprobado', rejected:'Cambios solicitados', reviewer:'Revisor', owner:'Propietario', editor:'Editor', viewer:'Lector', chooseReviewer:'Elegir un revisor', submit:'Solicitar aprobación', approve:'Aprobar esta versión', reject:'Solicitar cambios', comment:'Comentario de revisión (obligatorio al solicitar cambios)', reopen:'Crear una nueva revisión en borrador', withdraw:'Retirar la solicitud de aprobación', replace:'Reemplazar el borrador con mi documento seleccionado', restore:'Restaurar como nueva revisión', restoreConfirm:'¿Crear una nueva revisión a partir de este estado? Se conservará el historial anterior.', preview:'Vista previa', editCopy:'Editar una copia privada', editHint:'Para modificar un documento del equipo, edita y guarda una copia privada, selecciónala arriba y reemplaza este borrador. Las versiones enviadas y aprobadas están bloqueadas.', audit:'Historial de revisiones y aprobaciones', actor:'Por',
  invite:'Crear invitación de un solo uso', inviteHint:'El enlace caduca en 7 días y cualquier persona que lo tenga puede usarlo una vez. Cópialo y envíalo tú mismo. No se envía ningún correo.', copy:'Copiar enlace', copied:'Enlace copiado.', revoke:'Revocar', remove:'Eliminar miembro', removeConfirm:'¿Retirar a este miembro el acceso a la organización?', join:'Aceptar invitación', joinHint:'Al aceptar, accederás a la organización con el rol elegido por su propietario.', leave:'Abandonar organización', leaveConfirm:'¿Abandonar esta organización y perder el acceso a sus documentos privados?',
  companyHint:'Usa las plantillas de empresa en el diseñador de documentos. Selecciona allí una organización para aplicar o guardar un diseño compartido.', chooseTemplate:'Elegir una plantilla de empresa', templateName:'Nombre de la plantilla', saveTemplate:'Guardar nueva plantilla de empresa', updateTemplate:'Actualizar la plantilla de empresa seleccionada', deleteTemplate:'Eliminar la plantilla de empresa seleccionada', templateConfirm:'¿Actualizar o eliminar esta plantilla compartida para todos los miembros?', apply:'Aplicar plantilla', noOrg:'Crea una organización o únete a una desde el espacio de empresa.',
  interest:'Preferencia de futuro plan de pago (sin compra)', interestedPro:'Me interesa Pro', interestedBusiness:'Me interesa Business', current:'Versión actual', close:'Cerrar vista previa', refresh:'Actualizar', trialIncludes:'La prueba incluye las funciones de Pro y Business. Los planes de pago aún no están disponibles.',
 },
 storage: {
  title:'Almacenamiento de documentos privados', used:'{used} / {limit} guardados', trial:'{used} guardados · prueba gratuita activa', full:'El almacenamiento Free está lleno (3 documentos). Elimina un documento que no necesites o consulta la prueba gratuita para guardar otro. Los documentos existentes se pueden seguir editando y exportando.', expired:'Tu prueba ha terminado. Se conservan los documentos existentes; los nuevos guardados están sujetos al límite Free.', hint:'Free incluye 3 documentos privados guardados. No se limitan los pasos ni los riesgos por documento, la edición ni la exportación a PDF. Los borradores y favoritos públicos no ocupan estos espacios.', cta:'Ver prueba gratuita', error:'No se pudo cargar el uso del almacenamiento. El servidor seguirá comprobando el límite al guardar.', retry:'Actualizar', limitError:'Free permite guardar 3 documentos privados. Se conserva tu borrador actual. Elimina un documento guardado que no necesites o consulta la prueba gratuita.',
 },
};
