export default {
 business: {
  title:'Espace entreprise', beta:'Bêta gratuite', intro:'Essayez Pro et Business gratuitement pendant 30 jours. Aucune carte bancaire, aucun paiement ni facturation automatique. Vos documents enregistrés restent consultables après l’essai.',
  free:'Free', freeDesc:'Créez des documents JSA, utilisez la bibliothèque d’étapes, exportez et réutilisez des exemples publics.', pro:'Bêta Pro', proDesc:'Conservez les versions de vos documents personnels, consultez les versions précédentes et restaurez-les comme nouvelle révision.', business:'Bêta Business', businessDesc:'Modèles d’entreprise, rôles, documents privés d’équipe et approbation par version.', start:'Démarrer l’essai gratuit Pro + Business', active:'Fin de l’essai', expired:'L’essai est terminé. Les documents enregistrés et leur historique restent consultables.', login:'Se connecter pour continuer', library:'Ma bibliothèque', home:'Accueil', loading:'Chargement…', retry:'Réessayer', saved:'Enregistré.', error:'Impossible de terminer la demande. Actualisez et réessayez.', conflict:'Ce document a été modifié. Actualisez et vérifiez la dernière version avant de réessayer.', denied:'Vous n’avez pas l’autorisation d’effectuer cette action.', expiredError:'L’essai est terminé. Les données existantes restent consultables.', reviewerError:'Choisissez une autre personne chargée de la vérification qui n’a pas modifié cette version.', unavailable:'L’invitation a expiré, a été révoquée ou a déjà été utilisée.',
  organizations:'Organisations', chooseOrg:'Choisir une organisation', name:'Nom de l’organisation', create:'Créer une organisation', limit:'Jusqu’à 3 organisations pendant l’essai.', orgExpired:'Cette organisation est en lecture seule, car l’essai de son propriétaire est terminé.', documents:'Documents d’équipe', members:'Membres et invitations', templates:'Modèles d’entreprise', history:'Historique des révisions personnelles', historyHint:'Les révisions sont enregistrées lors de la sauvegarde de documents privés pendant l’essai. Une restauration crée une nouvelle révision et conserve l’historique. Les 100 dernières entrées sont affichées.',
  source:'Mon document privé', chooseSource:'Choisir un document privé enregistré', import:'Partager une copie avec cette organisation', importHint:'Seul le document privé sélectionné est copié, avec ses participants et ses photos. Tous les membres de l’organisation peuvent le consulter. L’original reste dans votre bibliothèque.', importConfirm:'Partager une copie de ce document, y compris ses informations privées et ses photos, avec tous les membres de l’organisation sélectionnée ?',
  empty:'Aucun élément pour le moment.', open:'Ouvrir', revision:'Révision', draft:'Brouillon', submitted:'En attente d’approbation', approved:'Approuvé', rejected:'Modifications demandées', reviewer:'Vérificateur', owner:'Propriétaire', editor:'Éditeur', viewer:'Lecteur', chooseReviewer:'Choisir un vérificateur', submit:'Demander l’approbation', approve:'Approuver cette version', reject:'Demander des modifications', comment:'Commentaire de vérification (obligatoire pour demander des modifications)', reopen:'Créer une nouvelle révision brouillon', withdraw:'Retirer la demande d’approbation', replace:'Remplacer le brouillon par mon document sélectionné', restore:'Restaurer comme nouvelle révision', restoreConfirm:'Créer une nouvelle révision à partir de cet état ? L’historique précédent sera conservé.', preview:'Aperçu', editCopy:'Modifier une copie privée', editHint:'Pour modifier un document d’équipe, modifiez et enregistrez une copie privée, puis sélectionnez-la ci-dessus pour remplacer ce brouillon. Les versions soumises et approuvées sont verrouillées.', audit:'Historique des révisions et approbations', actor:'Par',
  invite:'Créer une invitation à usage unique', inviteHint:'Le lien expire au bout de 7 jours et peut être utilisé une fois par toute personne qui le possède. Copiez-le et transmettez-le vous-même. Aucun courriel n’est envoyé.', copy:'Copier le lien', copied:'Lien copié.', revoke:'Révoquer', remove:'Retirer le membre', removeConfirm:'Retirer à ce membre l’accès à l’organisation ?', join:'Accepter l’invitation', joinHint:'En acceptant, vous accédez à l’organisation avec le rôle choisi par son propriétaire.', leave:'Quitter l’organisation', leaveConfirm:'Quitter cette organisation et perdre l’accès à ses documents privés ?',
  companyHint:'Utilisez les modèles d’entreprise dans le concepteur de documents. Choisissez-y une organisation pour appliquer ou enregistrer une mise en page partagée.', chooseTemplate:'Choisir un modèle d’entreprise', templateName:'Nom du modèle', saveTemplate:'Enregistrer un nouveau modèle d’entreprise', updateTemplate:'Mettre à jour le modèle d’entreprise sélectionné', deleteTemplate:'Supprimer le modèle d’entreprise sélectionné', templateConfirm:'Modifier ou supprimer ce modèle partagé pour tous les membres ?', apply:'Appliquer le modèle', noOrg:'Créez ou rejoignez une organisation dans l’espace entreprise.',
  interest:'Préférence pour une future offre payante (sans achat)', interestedPro:'Intéressé par Pro', interestedBusiness:'Intéressé par Business', current:'Version actuelle', close:'Fermer l’aperçu', refresh:'Actualiser', trialIncludes:'L’essai inclut les fonctionnalités Pro et Business. Les offres payantes ne sont pas encore disponibles.',
 },
 storage: {
  title:'Stockage des documents privés', used:'{used} / {limit} enregistrés', trial:'{used} enregistrés · essai gratuit actif', full:'Le stockage Free est plein (3 documents). Supprimez un document inutile ou consultez l’essai gratuit pour en enregistrer un autre. Les documents existants restent modifiables et exportables.', expired:'Votre essai est terminé. Les documents existants sont conservés ; la limite Free s’applique aux nouveaux enregistrements.', hint:'Free comprend 3 documents privés enregistrés. Les étapes et risques par document, la modification et l’export PDF ne sont pas limités. Les brouillons et favoris publics n’occupent pas ces emplacements.', cta:'Consulter l’essai gratuit', error:'Impossible de charger l’utilisation du stockage. Le serveur vérifiera tout de même la limite lors de l’enregistrement.', retry:'Actualiser', limitError:'Free permet d’enregistrer 3 documents privés. Votre brouillon actuel est conservé. Supprimez un document enregistré inutile ou consultez l’essai gratuit.',
 },
};
