export default {
 business: {
  title:'Spazio aziendale', beta:'Beta gratuita', intro:'Prova Pro e Business gratis per 30 giorni. Nessuna carta, pagamento o addebito automatico. I documenti salvati resteranno consultabili dopo la prova.',
  free:'Free', freeDesc:'Crea documenti JSA, usa la libreria delle fasi di lavoro, esporta e riutilizza esempi pubblici.', pro:'Beta Pro', proDesc:'Conserva le revisioni dei documenti personali, consulta le versioni precedenti e ripristinale come nuova revisione.', business:'Beta Business', businessDesc:'Modelli aziendali, ruoli, documenti privati del gruppo e approvazione per versione.', start:'Avvia la prova gratuita Pro + Business', active:'Fine della prova', expired:'La prova è terminata. I documenti salvati e la cronologia restano consultabili.', login:'Accedi per continuare', library:'La mia libreria', home:'Pagina iniziale', loading:'Caricamento…', retry:'Riprova', saved:'Salvato.', error:'Impossibile completare la richiesta. Aggiorna e riprova.', conflict:'Questo documento è stato modificato. Aggiorna e controlla l’ultima versione prima di riprovare.', denied:'Non hai il permesso di eseguire questa azione.', expiredError:'La prova è terminata. I dati esistenti restano consultabili.', reviewerError:'Scegli un altro revisore che non abbia modificato questa versione.', unavailable:'L’invito è scaduto, è stato revocato o è già stato utilizzato.',
  organizations:'Organizzazioni', chooseOrg:'Scegli un’organizzazione', name:'Nome dell’organizzazione', create:'Crea organizzazione', limit:'Fino a 3 organizzazioni durante la prova.', orgExpired:'Questa organizzazione è in sola lettura perché la prova del proprietario è terminata.', documents:'Documenti del gruppo', members:'Membri e inviti', templates:'Modelli aziendali', history:'Cronologia delle revisioni personali', historyHint:'Le revisioni vengono registrate quando salvi documenti privati durante la prova. Il ripristino crea una nuova revisione e mantiene la cronologia. Vengono mostrate le ultime 100 voci.',
  source:'Il mio documento privato', chooseSource:'Scegli un documento privato salvato', import:'Condividi una copia con questa organizzazione', importHint:'Viene copiato solo il documento privato selezionato, inclusi partecipanti e foto. Tutti i membri dell’organizzazione possono consultarlo. L’originale resta nella tua libreria.', importConfirm:'Condividere una copia di questo documento, inclusi dati privati e foto, con tutti i membri dell’organizzazione selezionata?',
  empty:'Nessun elemento per ora.', open:'Apri', revision:'Revisione', draft:'Bozza', submitted:'In attesa di approvazione', approved:'Approvato', rejected:'Modifiche richieste', reviewer:'Revisore', owner:'Proprietario', editor:'Redattore', viewer:'Lettore', chooseReviewer:'Scegli un revisore', submit:'Richiedi approvazione', approve:'Approva questa versione', reject:'Richiedi modifiche', comment:'Commento di revisione (obbligatorio per richiedere modifiche)', reopen:'Crea una nuova revisione in bozza', withdraw:'Ritira la richiesta di approvazione', replace:'Sostituisci la bozza con il mio documento selezionato', restore:'Ripristina come nuova revisione', restoreConfirm:'Creare una nuova revisione da questo stato? La cronologia precedente verrà conservata.', preview:'Anteprima', editCopy:'Modifica una copia privata', editHint:'Per modificare un documento del gruppo, modifica e salva una copia privata, poi selezionala sopra e sostituisci questa bozza. Le versioni inviate e approvate sono bloccate.', audit:'Cronologia delle revisioni e approvazioni', actor:'Autore dell’azione',
  invite:'Crea invito monouso', inviteHint:'Il link scade dopo 7 giorni e può essere usato una volta da chiunque lo possieda. Copialo e invialo personalmente. Non viene inviata alcuna email.', copy:'Copia link', copied:'Link copiato.', revoke:'Revoca', remove:'Rimuovi membro', removeConfirm:'Revocare a questo membro l’accesso all’organizzazione?', join:'Accetta invito', joinHint:'Accettando accedi all’organizzazione con il ruolo scelto dal proprietario.', leave:'Esci dall’organizzazione', leaveConfirm:'Uscire da questa organizzazione e perdere l’accesso ai suoi documenti privati?',
  companyHint:'Usa i modelli aziendali nel designer di documenti. Scegli lì un’organizzazione per applicare o salvare un layout condiviso.', chooseTemplate:'Scegli un modello aziendale', templateName:'Nome del modello', saveTemplate:'Salva nuovo modello aziendale', updateTemplate:'Aggiorna il modello aziendale selezionato', deleteTemplate:'Elimina il modello aziendale selezionato', templateConfirm:'Aggiornare o eliminare questo modello condiviso per tutti i membri?', apply:'Applica modello', noOrg:'Crea un’organizzazione o entra a farne parte nello spazio aziendale.',
  interest:'Preferenza per un futuro piano a pagamento (nessun acquisto)', interestedPro:'Mi interessa Pro', interestedBusiness:'Mi interessa Business', current:'Versione attuale', close:'Chiudi anteprima', refresh:'Aggiorna', trialIncludes:'La prova include le funzionalità Pro e Business. I piani a pagamento non sono ancora disponibili.',
 },
 storage: {
  title:'Spazio per documenti privati', used:'{used} / {limit} salvati', trial:'{used} salvati · prova gratuita attiva', full:'Lo spazio Free è pieno (3 documenti). Elimina un documento non necessario o consulta la prova gratuita per salvarne un altro. I documenti esistenti restano modificabili ed esportabili.', expired:'La prova è terminata. I documenti esistenti vengono conservati; ai nuovi salvataggi si applica il limite Free.', hint:'Free include 3 documenti privati salvati. Fasi e rischi per documento, modifica ed esportazione PDF non sono limitati. Le bozze e i preferiti pubblici non occupano questi posti.', cta:'Scopri la prova gratuita', error:'Impossibile caricare l’utilizzo dello spazio. Il server controllerà comunque il limite al salvataggio.', retry:'Aggiorna', limitError:'Free consente di salvare 3 documenti privati. La bozza attuale viene conservata. Elimina un documento salvato non necessario o consulta la prova gratuita.',
 },
};
