export default {
 business: {
  title:'Espaço da empresa', beta:'Beta gratuito', intro:'Experimente o Pro e o Business grátis por 30 dias. Sem cartão, pagamento ou cobrança automática. Seus documentos salvos continuam disponíveis para consulta após o período de teste.',
  free:'Free', freeDesc:'Crie documentos JSA, use a biblioteca de etapas, exporte e reutilize exemplos públicos.', pro:'Beta Pro', proDesc:'Guarde revisões dos seus documentos pessoais, visualize versões anteriores e restaure-as como uma nova revisão.', business:'Beta Business', businessDesc:'Modelos da empresa, funções, documentos privados da equipe e aprovação por versão.', start:'Iniciar teste gratuito do Pro + Business', active:'Fim do teste', expired:'O teste terminou. Os documentos salvos e o histórico continuam disponíveis para consulta.', login:'Entre para continuar', library:'Minha biblioteca', home:'Início', loading:'Carregando…', retry:'Tentar novamente', saved:'Salvo.', error:'Não foi possível concluir a solicitação. Atualize e tente novamente.', conflict:'Este documento foi alterado. Atualize e confira a versão mais recente antes de tentar novamente.', denied:'Você não tem permissão para esta ação.', expiredError:'O teste terminou. Os dados existentes continuam disponíveis para consulta.', reviewerError:'Escolha outro revisor que não tenha editado esta versão.', unavailable:'O convite expirou, foi revogado ou já foi utilizado.',
  organizations:'Organizações', chooseOrg:'Escolha uma organização', name:'Nome da organização', create:'Criar organização', limit:'Até 3 organizações durante o teste.', orgExpired:'Esta organização está em modo de leitura porque o teste do proprietário terminou.', documents:'Documentos da equipe', members:'Membros e convites', templates:'Modelos da empresa', history:'Histórico de revisões pessoais', historyHint:'As revisões são registradas ao salvar documentos privados durante o teste. A restauração cria uma nova revisão e mantém o histórico. As últimas 100 entradas são exibidas.',
  source:'Meu documento privado', chooseSource:'Escolha um documento privado salvo', import:'Compartilhar uma cópia com esta organização', importHint:'Somente o documento privado selecionado é copiado, incluindo participantes e fotos. Todos os membros da organização podem consultá-lo. O original permanece na sua biblioteca.', importConfirm:'Compartilhar uma cópia deste documento, incluindo dados privados e fotos, com todos os membros da organização selecionada?',
  empty:'Ainda não há itens.', open:'Abrir', revision:'Revisão', draft:'Rascunho', submitted:'Aguardando aprovação', approved:'Aprovado', rejected:'Alterações solicitadas', reviewer:'Revisor', owner:'Proprietário', editor:'Editor', viewer:'Leitor', chooseReviewer:'Escolha um revisor', submit:'Solicitar aprovação', approve:'Aprovar esta versão', reject:'Solicitar alterações', comment:'Comentário de revisão (obrigatório ao solicitar alterações)', reopen:'Criar nova revisão em rascunho', withdraw:'Retirar solicitação de aprovação', replace:'Substituir o rascunho pelo meu documento selecionado', restore:'Restaurar como nova revisão', restoreConfirm:'Criar uma nova revisão a partir deste estado? O histórico anterior será mantido.', preview:'Prévia', editCopy:'Editar uma cópia privada', editHint:'Para alterar um documento da equipe, edite e salve uma cópia privada, selecione-a acima e substitua este rascunho. As versões enviadas e aprovadas ficam bloqueadas.', audit:'Histórico de revisões e aprovações', actor:'Por',
  invite:'Criar convite de uso único', inviteHint:'O link expira em 7 dias e pode ser usado uma vez por qualquer pessoa que o tenha. Copie e envie o link por conta própria. Nenhum e-mail é enviado.', copy:'Copiar link', copied:'Link copiado.', revoke:'Revogar', remove:'Remover membro', removeConfirm:'Remover o acesso deste membro à organização?', join:'Aceitar convite', joinHint:'Ao aceitar, você terá acesso à organização com a função escolhida pelo proprietário.', leave:'Sair da organização', leaveConfirm:'Sair desta organização e perder o acesso aos documentos privados dela?',
  companyHint:'Use os modelos da empresa no designer de documentos. Escolha uma organização lá para aplicar ou salvar um layout compartilhado.', chooseTemplate:'Escolha um modelo da empresa', templateName:'Nome do modelo', saveTemplate:'Salvar novo modelo da empresa', updateTemplate:'Atualizar o modelo da empresa selecionado', deleteTemplate:'Excluir o modelo da empresa selecionado', templateConfirm:'Atualizar ou excluir este modelo compartilhado para todos os membros?', apply:'Aplicar modelo', noOrg:'Crie ou entre em uma organização no espaço da empresa.',
  interest:'Preferência de futuro plano pago (sem compra)', interestedPro:'Tenho interesse no Pro', interestedBusiness:'Tenho interesse no Business', current:'Versão atual', close:'Fechar prévia', refresh:'Atualizar', trialIncludes:'O teste inclui os recursos Pro e Business. Os planos pagos ainda não estão disponíveis.',
 },
 storage: {
  title:'Armazenamento de documentos privados', used:'{used} / {limit} salvos', trial:'{used} salvos · teste gratuito ativo', full:'O armazenamento Free está cheio (3 documentos). Exclua um documento desnecessário ou confira o teste gratuito para salvar outro. Os documentos existentes continuam disponíveis para edição e exportação.', expired:'Seu teste terminou. Os documentos existentes são mantidos; novos salvamentos seguem o limite Free.', hint:'O Free inclui 3 documentos privados salvos. Não há limite para etapas e riscos por documento, edição ou exportação em PDF. Rascunhos e favoritos públicos não ocupam essas vagas.', cta:'Ver teste gratuito', error:'Não foi possível carregar o uso do armazenamento. O servidor ainda verificará o limite ao salvar.', retry:'Atualizar', limitError:'O Free permite salvar 3 documentos privados. Seu rascunho atual será mantido. Exclua um documento salvo desnecessário ou confira o teste gratuito.',
 },
};
